### ISSUE TITLE
[Bug] $var list when using nested modals appears outside of the firebot window boundary

### ISSUE THREAD

**Issue by Concede** [crowbartools/Firebot#1008]
**Describe the bug**
$var Tooltip/modal exits boundary of the window and you cannot see the top/filter section of it when you have multiple nested modals.

**To Reproduce**
1. Create a new command
2. Click Advanced mode
3. Add effect 'Show HTML'
4. Click the $vars link in the "HTML" box.

**Expected behavior**
Tooltip/Modal with all variables is shown correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/9073058/103547113-e0012180-4e9b-11eb-83a2-f160efd8a342.png)

**Firebot Version:**
5.34.0

**Computer OS:**
Win 10

**Comment by ebiggz** [comment]
Thank you for the detailed bug report. This will be fixed in the next update.

**Comment by ebiggz** [comment]
Bugfix is out in v5.35.0
