### ISSUE TITLE
[Feature Request] User defined Event Cooldowns

### ISSUE THREAD

**Issue by MageEnclave** [crowbartools/Firebot#1012]
**Describe the solution you'd like**
I'd like a delay restriction on events. If this even has been fired recently, then do not fire it again until the time is up.

**Additional context**
Everytime someone puts the catJAM emote in chat I want to show a catJAM video on screen. Right now I can only trigger this on EVERY emote that comes through. So, if things get really exciting then you could end up with dozens or more videos trying to play on top of each other.

**Comment by ebiggz** [comment]
Events don't use the Restrictions system (they use Filters). 

However the logic to support event "cooldowns" is already in place - we use it internally for various events such as Follow, Host, etc to prevent those from being spammed. So we'd just need to surface a field in the Add/Edit Event Modal where the user can specify a custom cooldown for their given event.
