### ISSUE TITLE
[Feature Request] Stream Online Event

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#1013]
**Describe the solution you'd like**
I'd like a stream online event. Basically, you could put in a username to check against and if that stream comes online then the event would fire.

**Additional context**
1. I'd like to automatically post a discord, twitter, or other message when the stream goes live.
2. I'd like to automatically post to discord when friends go online.
3. I'd like to automatically post a chat message when the stream goes live. If the stream drops, sometimes people need to refresh when the stream comes back again. A chat message would let them know to refresh.

**Comment by CaveMobster** [comment]
This will be something to consider when EventSub supports websocket connection in production.

**Comment by Firebottle** [comment]
https://www.npmjs.com/package/twitchonlinetracker

**Comment by zunderscore** [comment]
The **Stream Online** and **Stream Offline** events were added with EventSub support in 5.60.0
