### ISSUE TITLE
[Bug] Discord "allowed_mentions" of null

### ISSUE THREAD

**Issue by MageEnclave** [crowbartools/Firebot#1014]
**Describe the bug**

I tried to include ``**$date**`` to make the date bold in the discord message. Once I removed that part then everything worked fine again.

"There was an error running effect of type discord:send-message. "Cannot set property 'allowed_mentions' of null".

**Comment by MageEnclave** [comment]
It seems like adding ( or ) to the discord message also causes this error. For example a stream title of "Blah blag (VR, VIVE)" will error out and not send to discord.

**Comment by MageEnclave** [comment]
I have the name of the game I'm playing in a discord message. It errors out for "Beyond Good and Evil" and I'm not sure why...

But in general, this effect seems to error out a lot on a bunch of different kinds of text.

**Comment by ebiggz** [comment]
@MageEnclave Man sorry you are having this issue. Im trying to figure out whats going on. Struggling to replicate. I've put all the text you listed as examples here and its working fine for me. So wondering if something else weird is going on. Per chance, have you tried readding the Webhook in Settings > Integrations > Discord > Configure?

**Comment by MageEnclave** [comment]
I ended up just using the stream embed to show everything I was playing. I haven't tested this in awhile and I don't think anyone else has reported it. I'm going to go ahead and close this since it is stale and I'll open it up again later if I run into something again.
