### ISSUE TITLE
[Feature Request] Sort Tags in !commands webpage

### ISSUE THREAD

**Issue by darkfreak** [crowbartools/Firebot#1049]
**Describe the solution you'd like**
An option to sort or "Show only" commands with certain tags on the webpage that lists all commands (!commands)

**Additional context**
If you add a lot of commands with the tag "Sound", and someone wants to view only sound-related commands, they can select "Sounds" to only see those on the !commands-webpage.

**AND/OR**
Make it so that you can show only a certain tag's commands linked to a command, for example:
Sort Tag: "Sounds"
Command: !sounds
Shows: All commands with the 'Sounds' tag (in a webpage like !commands)

**Comment by ebiggz** [comment]
Profile page now displays command sort tags ![image](https://user-images.githubusercontent.com/3515161/144377437-66e8d678-7199-4bc8-8aa6-d244881fb024.jpeg)
