### ISSUE TITLE
[Feature Request] Group preset effect lists

### ISSUE THREAD

**Issue by CaveMobster** [crowbartools/Firebot#1084]
**Describe the solution you'd like**
Currently the preset effect lists are one big list, but that can get confusing really fast if you use a lot of them for a variety of reasons. For example, I have an end credits system that uses multiple preset effect lists, but I also have one for sending out a go-live message, and one to clear sound effects. Having groups would help to keep things organized. Event sets would be a good inspiration for the UI.

**Comment by ebiggz** [comment]
This is a good idea!!

However I think we should start with implementing "Sort Tags" (used in Commands and Events) first and see if that is sufficient. "Event Sets" are special in that there is app functionality tied to them: they allow the user to quickly enable or disable groups of events which is useful for having different groups of events for different games, holidays, etc. So Sets are different from UI organization. Sort tags are intended to be the mechanism for sorting/organization within the UI and its why Events have both Sort Tags and Sets.

**Comment by CaveMobster** [comment]
Oh that's a great point! So if I understand this correctly, with the sort tags it would be more like how the commands are sorted right?

**Comment by ebiggz** [comment]
@CaveMobster Yep, exactly like that. Both Events and Commands use Sort Tags:

![image](https://user-images.githubusercontent.com/3515161/115939302-53d33400-a463-11eb-9a6b-cc5eb4765411.png)

![image](https://user-images.githubusercontent.com/3515161/115939342-77967a00-a463-11eb-8ba6-04ebf2d65512.png)

**Comment by CaveMobster** [comment]
@ebiggz I'd like to start working on this soon, so I did some looking into the code. Do you think it's a good idea to convert the Preset Effect Lists view to the Firebot item table that the Channel Rewards use before adding sort tags? And if so, is it okay if I do that, or would that mess with your planning?

**Comment by ebiggz** [comment]
@CaveMobster Yep go for it! I created the `<firebot-item-table>` element to be as reusable as possible so we can use it for all pages that share the same UI (something that should of happened long ago).
