### ISSUE TITLE
[Feature Request] Anonymous user filter for bits and gift sub events

### ISSUE THREAD

**Issue by CaveMobster** [crowbartools/Firebot#1086]
**Describe the solution you'd like**
It might be nice to add a filter for bits and gift subs, to check whether they were given by an anonymous user.

**Comment by CaveMobster** [comment]
@ebiggz This one isn't done yet, it only works for bits at the moment. Shall I reopen this one, or make a new issue?

**Comment by ebiggz** [comment]
@CaveMobster  ah shoot - so sorry about that!
