### ISSUE TITLE
[Feature Request] Use Authorization/Header with $readApi

### ISSUE THREAD

**Issue by mrsnuudles** [crowbartools/Firebot#1094]
**Describe the solution you'd like**
To be able to specify a header when making a $readAPI call (i.e. authorization bearer string).

**Additional context**
This would allow use of the Twitter API (i.e. to get latest or list of tweets).

**Comment by ebiggz** [comment]
Hi there @mrsnuudles! I believe we finally have a solution to this use case. v5.46.4 added a new `HTTP Request` effect which enables you to define headers. It can also put the response body into a custom variable so you can reference the data in other effects however you need. Thanks for the patience on this!
