### ISSUE TITLE
[Bug] $rewardMessage context lost if after an effect list

### ISSUE THREAD

**Issue by Runesun** [crowbartools/Firebot#1162]
**Describe the bug**
Chat message loses $rewardMessage context after a Preset Effect List

**Steps To Reproduce**
1. Go to a Channel Reward Redeem
2. Add a Run Effect List with a Preset List
3. Add a Chat Effect after the effect list

**Expected behavior**
$rewardMessage shows the reward message instead of just $rewardMessage

**Screenshots**
![image](https://user-images.githubusercontent.com/83992396/117741888-77231080-b1d1-11eb-8923-689903422ec6.png)

**Firebot Version:** 5.38.1

**Computer OS:** Windows

**Side Note:**
Using two chat messages back to back seems to work fine, message shows for both messages. Might be tied to losing context post effect list.

**Comment by ebiggz** [comment]
Thanks for this! It should be fixed in 5.38.2
