### ISSUE TITLE
[Bug] Autoupdater 404 on Linux build

### ISSUE THREAD

**Issue by crabcrabcam** [crowbartools/Firebot#1168]
**Describe the bug**
Enter a clear and concise description of what the bug is.
The app doesn't update automatically due to a 404 for the autoupdater. 

**Steps To Reproduce**
1. Open the app after an update
2. You're there

The requestUrl https://raw.githubusercontent.com/crowbartools/firebot/master/auto_updater.json gives a 404: Not Found

**Expected behavior**
Enter a clear and concise description of what you expected to happen.
The app to update

**Screenshots**
![image](https://user-images.githubusercontent.com/13933264/117813533-193b0b00-b25b-11eb-810f-a1b7548dcb00.png)

This comes up when you launch during the update (image text: 
```
    req: { '$ref': '$["response"]["socket"]["_httpMessage"]' },
    requestUrl: 'https://raw.githubusercontent.com/crowbartools/firebot/master/auto_updater.json',
    body: '404: Not Found'
```

**Firebot Version:**
All since 5.35 (since I started using Firebot)

**Computer OS:**
Void Linux

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by brumoen** [comment]
Linux builds have to be updated manually as we haven't made them work with auto updates yet, so you have to download the package and unpack it over the old one.

So I'll close this is as it technically falls under #546

**Comment by SReject** [comment]
Some more info on this:

We use an auto-packager to create the binaries of Firebot. Its that auto-packager that provides auto-update support. Sadly it only supports MacOS and windows.

For linux users, you will have to routinely check for updates and unpack updates over your old install.

**Comment by crabcrabcam** [comment]
Would it be possible to get the updater download attempt removed for Linux? If you don't want to update you have to spend 3 minutes waiting for it to fail to be able to use it. A warning of an update instead would be good, if that's possible (since it seems auto update will never be on Linux)

**Comment by brumoen** [comment]
If you push ESC when the "Downloading Update" popup shows it goes away so you don't have to wait for it to fail before it goes away.
And yes, we could probably change the popup so it just tells you there is a new update, and a link to the release page, if the client is running on Linux instead of "trying" to download something that will fail.
