### ISSUE TITLE
[Bug] Commands List Ordering

### ISSUE THREAD

**Issue by THECorranHorn** [crowbartools/Firebot#1219]
**Describe the bug**
Commands list doesn't order alphabetically so similar commands are grouped together. 

**Steps To Reproduce**
Go to commands list
Add a command
Add a command with a different spelling
Add a command with same initial spelling as first command

**Expected behavior**
All commands will order together alphabetically automatically

**Screenshots**

**Firebot Version:**
Release v5.39.2

**Computer OS:**
Windows 10

**Comment by ebiggz** [comment]
This is not a bug or something we will implement as the command list order can be managed by the user via the handles in the table. 
<img width="1003" alt="Screen Shot 2021-06-01 at 3 00 49 PM" src="https://user-images.githubusercontent.com/3515161/120383196-34dd8280-c2ea-11eb-822e-9d75af764fa3.png">

**Comment by THECorranHorn** [comment]
got it, thanks for the info
