### ISSUE TITLE
[Bug] Viewer Arrived Does Not Correctly Filter Non-English Characters in Usernames

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#1247]
**Describe the bug**
Bug discovered by Cake (🎂Cake🎂®#7437) in Discord.

When a User has a non-english character based name, Firebot doesn't correctly filter by Viewer Roles during the Viewer Arrived Event, and fires even when the User is not part of the group.

**Steps To Reproduce**
1. Create a Viewer Role called 'Auto-Shoutouts', and add no Users
2. Create a Viewer Arrived Event that greats a user when they arrive if they're part of the 'Auto-Shoutout' Viewer Role
3. Have a non-english character name chat (보라색 태양) - the Viewer Arrived event will incorrectly fire.

**Expected behavior**
Firebot should not trigger the Viewer Arrived event because the viewer is not in the Viewer Role 'Auto-Shoutouts'

**Screenshots**
![image](https://user-images.githubusercontent.com/10332351/125344896-191bc200-e315-11eb-9cbe-a141c863b9f1.png)
![image](https://user-images.githubusercontent.com/10332351/125344902-1c16b280-e315-11eb-8c2c-2dca9830d166.png)

**Comment by EpistemicPolymath** [comment]
I am still having this issue. Viewers with non-english character names cannot collect or generate points.
![JapaneseCharactersName](https://user-images.githubusercontent.com/16484276/182033392-7bb29ae1-d200-425f-adb0-59c1cc6137f1.png)

**Comment by zunderscore** [comment]
Released in v5.62.0
