### ISSUE TITLE
[Feature Request] Add support for regex on banned words

### ISSUE THREAD

**Issue by davidneedham** [crowbartools/Firebot#1259]
**Describe the solution you'd like**
When creating the list of banned words, I'd like to have the option to use regex. This will make it significantly easier to add checks that auto-block well-known spambots on Twitch.

**Additional context**
Here are some of the steps and regex written for other bots (Nightbot, StreamLabs, and StreamElements): https://docs.google.com/document/d/1ofG0g_95tZizwfsET9O05abwbDw__3wdNQOhwges1pg/edit#.

**Comment by Somnophobe** [comment]
As the person who wrote that resource @davidneedham shared, and as a streamer and a mod, I very much support this. I'd love to include Firebot as a featured and supported bot in the doc, because it's such a good tool and this is one of the few limitations I've run into on it.
