### ISSUE TITLE
[Feature Request] Twitch Hype Train Integration

### ISSUE THREAD

**Issue by TioMecanico** [crowbartools/Firebot#1265]
**Describe the solution you'd like**
Pull Twitch Hype Train information (hype train level as a variable and/or hype train events [hype train start, hype train end, hype train level up]) from Twitch

**Additional context**
Could be used to trigger all sorts of visual and audio chaos when hype trains start, level up, and then clean up when they end.

I don't know if this is possible based on what information twitch makes visible to the bot, but I do know they have to distribute it for viewers to be aware of the hype train.

This isn't particularly high priority, but could be a very nice enhancement.

**Comment by ericwebster** [comment]
Is it possible to get an update on this issue? Thanks.
