### ISSUE TITLE
[Bug] Frontend - Settings are lost when reopening a "Run Effect List" effect that is using a preset.

### ISSUE THREAD

**Issue by FineWolf** [crowbartools/Firebot#1286]
**Describe the bug**
When re-opening a saved "Run Effect List" effect that is using a preset, settings will fail to restore properly in the UI.

**Steps To Reproduce**
1. Add a "Run Effect List" effect
2. Select List Type "Preset"
3. Select a preset you've created.
4. Save
5. Reopened the saved effect

**Expected behavior**
Settings are properly restored as they were previously.

**Screenshots**

**Firebot Version:** v5.40.1

**Computer OS:** Windows 10

**Note:** Will implement fix

**Comment by CaveMobster** [comment]
Nice and elaborate! Please make sure to look through the issue list first, before you add tickets. :D I'm closing my tickets because these are more elaborate, but it helps for clarity and extra work.

**Comment by FineWolf** [comment]
> 
> 
> Nice and elaborate! Please make sure to look through the issue list first, before you add tickets. :D I'm closing my tickets because these are more elaborate, but it helps for clarity and extra work.

Sorry @CaveMobster . I did see #1284 but when I read it it didn't seem related. I misunderstood the original issue.
