### ISSUE TITLE
[Bug] Send to Overlay list not populated when using Google Cloud Text-to-Speech script

### ISSUE THREAD

**Issue by SMERKIN5000** [crowbartools/Firebot#1304]
**Describe the bug**
I am using the https://github.com/heyaapl/firebot-script-google-cloud-tts script, when configuring the effect I select Send To Overlay for the Audio Output Device there is no additional drop down menu where I can select the overlay I want to send it to.

**Steps To Reproduce**
1. Add an Effect using Google Cloud Text-to-Speech script (third party)
2. Click on Audio Output Device and select "Send To Overlay"
3. The Overlay drop down list does not appear

**Expected behavior**
The Overlay drop down list should appear.

**Screenshots**
N/A

**Firebot Version:**
5.41.0

**Computer OS:**
Windows

**Comment by CaveMobster** [comment]
This is an issue with the script, not with Firebot's core code. It's best if you create an issue in the script's repository.
