### ISSUE TITLE
[Feature Request] Text-To-Speech does not provide an Audio Output Device option

### ISSUE THREAD

**Issue by SMERKIN5000** [crowbartools/Firebot#1305]
**Describe the solution you'd like**
When creating the standard Text-To-Speech effect there is no Audio Output Device option when I could then select to Send To Overlay.

**Comment by FineWolf** [comment]
This one might be impossible to implement ("other than the Send to Overlay option") as the [Web SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis) API doesn't provide any facilities to select the output sound device.

**Comment by SMERKIN5000** [comment]
I'll close this then, at least there is a record here of why it's not possible.
