### ISSUE TITLE
[Feature Request] stream marker

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1321]
**Describe the solution you'd like**
Enter a clear and concise description of what you want to happen.

being able to in a command effect create a stream marker its in the api this will make it easy for  recording a stream then going back and editing the vod for  a video 

**Additional context**

here is the api info. 
https://dev.twitch.tv/docs/api/reference#create-stream-marker

**Comment by CaveMobster** [comment]
There is a stream marker command in the system commands, I think that is what you're looking for?

**Comment by CKY-** [comment]
I was looking for more of an effect, that can be added to counter commands. for things like death couthers and the such to get markers in the vods. but knowing that the marker command is there, I think, I can run the run command effect to run the command to make the marker.

**Comment by CKY-** [comment]
never mind that won't work either because system commands aren't exposed to the run command effect. so back to the original question can we have an effect to create stream markers.

**Comment by CaveMobster** [comment]
Ahaa, I think I misunderstood when you said command effect. I do think there is a ticket somewhere to add system commands to the Run Command effect. We can at least do that and if it then turns out that a separate effect is still more convenient, we can look into that too.

**Comment by CKY-** [comment]
thank you

**Comment by CaveMobster** [comment]
Closing this issue because of the following: https://github.com/crowbartools/Firebot/issues/941
