### ISSUE TITLE
[Feature Request] variable to expose a users created_at date 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1335]
**Describe the solution you'd like**
Enter a clear and concise description of what you want to happen.
samples:
Var $accountage[$user]
Var $accountdate[$user]

pulled from 

the user endpoint 
https://dev.twitch.tv/docs/v5/reference/users#get-user
has the created_at date  would be cool if we can expose it  to variables 

**Additional context**

**Comment by CKY-** [comment]
This was removed?

**Comment by CaveMobster** [comment]
@CKY- It's been back for a while now.
