### ISSUE TITLE
[Feature Request] Be able to pull the top for a metadata

### ISSUE THREAD

**Issue by whatupcraig** [crowbartools/Firebot#1339]
**Describe the solution you'd like**
Have a variable be used to be able to pull the data of the top x of a particular metadata. Similar to how the currency tracking system works. 

Example:
metadata(slaps, 1, username) - generate the username of the person with the most slaps
metadata(slaps, 1, count) - generate the number of slaps by the #1 person
$topmetadata(slaps) - would generate a top 10 list of the most slaps by a person

**Comment by jstnrp** [comment]
This will be in the next release.
