### ISSUE TITLE
[Bug] The live broadcast information is not initialized properly

### ISSUE THREAD

**Issue by KaiShu1** [crowbartools/Firebot#1349]
**Describe the bug**
When I opened the software for the first time and logged in to my twitch account, the related information in the live broadcast room was not initialized correctly

**Steps To Reproduce**
1. Open Firebot for the first time
2. Show welcome page
2. Add twitch streamer
3. Skip
4. Done

**Expected behavior**
Show live room information after login

**Screenshots**
-

**Firebot Version:**
5.40.0

**Computer OS:**
Win 10

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by brumoen** [comment]
What exactly do you mean by "Show live room information after login"?

I just followed your steps on a new setup and this is what I see after signing in my Twitch profile, no bot account, skipped the setup of overlay and skipped the next step then clicked the "I'm so ready" button.
![image](https://user-images.githubusercontent.com/4147439/131968081-b1dc60f6-0b89-4bbf-9d40-22b011fa0c02.png)
And this is what it is supposed to show, until you click the connect button.

**Comment by KaiShu1** [comment]
Okay, I made a mistake
