### ISSUE TITLE
[Feature Request] Hide affiliate features for non-affiliates

### ISSUE THREAD

**Issue by CaveMobster** [crowbartools/Firebot#1353]
**Describe the solution you'd like**
I got the feedback that users that are not affiliated tried to use things like the channel points and were confused that it didn't work. I think it may be nice to hide those features (and things like sub/bit events etc) to avoid confusion.

**Comment by ebiggz** [comment]
@CaveMobster I know you did some work regarding this. Can it be closed or is there still more you want to do?

**Comment by CaveMobster** [comment]
@ebiggz There's more, I'll close it when I'm done. 😀
