### ISSUE TITLE
[TechDebt] Clean up eslint warnings

### ISSUE THREAD

**Issue by SReject** [crowbartools/Firebot#1358]
Currently, we allow release checks to pass if eslint outputs warning. As a result we've accumulated quite a few warnings that should be addressed before they amount to a huge task similar to before

**Comment by zunderscore** [comment]
We've gotten a LOT of this done. Mostly what's left is a bunch of `any` types that need to be either sorted out or ignored.

**Comment by Firebottle** [comment]
We can probably go ahead and close this one then. This seems like something that we're going to gradually get to over time regardless of whatever else we're doing.
