### ISSUE TITLE
[Feature Request] Custom Role Actions

### ISSUE THREAD

**Issue by THECorranHorn** [crowbartools/Firebot#1362]
**Describe the solution you'd like**
Add customizable extra roles that are managed by firebot that can also have group currency commands, so you can do something like a "regulars" group, and have the ability to run 1 command to add a specified amount of currency to everyone in that group. Also make all the functionality work while live and while not live. 

**Additional context**
NA

**Comment by Firebottle** [comment]
The update currency effect has the ability to add currency to a specific role, but only for users who are online in that role. @THECorranHorn are you requesting that we add the ability to add currency to ALL users in the role online or offline?

Or are you requesting more than that?

**Comment by THECorranHorn** [comment]
> The update currency effect has the ability to add currency to a specific role, but only for users who are online in that role. @THECorranHorn are you requesting that we add the ability to add currency to ALL users in the role online or offline?
> 
> Or are you requesting more than that?

Online & Offline would be really helpful if possible, lots of broadcasters don't always remember to do everything they want online. Would come in handy for preparations for special broadcasts where things like raffles/etc are planned, as well as post broadcast final adjustments/corrections.

**Comment by Firebottle** [comment]
Closing as stale. Please re-open if this is still an issue.
