### ISSUE TITLE
[Feature Request] Commands Page Link 

### ISSUE THREAD

**Issue by THECorranHorn** [crowbartools/Firebot#1363]
**Describe the solution you'd like**
Add a spot in Firebot settings that shows your commands page link for ease of access when not live

**Additional context**
NA

**Comment by CaveMobster** [comment]
This is not currently possible since the links change occasionally. It would mean we need to switch to static page hosting and that's not on the agenda for now.

**Comment by Firebottle** [comment]
This is probably going to be a v6 issue.

**Comment by Firebottle** [comment]
I'm actually going to make this as a duplicate of #1199 as once that change is made this URL will definitely appear in the app, as well as on commands, etc..
