### ISSUE TITLE
[Feature Request] Confirm application exit when connected

### ISSUE THREAD

**Issue by Rumbledethumps** [crowbartools/Firebot#1365]
When connected to twitch (the power button icon is green) confirm exiting the application when pressing the window title [X], Alt-F4, etc. Similar to how browsers ask you to confirm when you have multiple tabs open.

Why? Because I've shut down Firebot by mistake while streaming.

Normally, I'd ask that an application like this close to the system tray, but it seems like that is troublesome. See #934.

**Comment by ebiggz** [comment]
Hi @Rumbledethumps , apologies for the extreme delay in response. I think this is a great idea. I agree that ideally the app should minimize to tray but as you mentioned, there's some hurdles with Playing Sounds that we need to solve first.
