### ISSUE TITLE
[Feature Request] An effect to reset a timer

### ISSUE THREAD

**Issue by Rumbledethumps** [crowbartools/Firebot#1366]
We can enable, disable, and toggle timers. I'd like to reset a timer too. This is mainly to implement a one-shot timed event that might be cancelled. A simple example would be: Push stream deck button to start a reminder to drink water in 15 minutes. If I drink before the timer fires, pushing the same button would reset the timer.

I originally enabled a timer and had the timer disable itself when triggered. This didn't allow me to cancel the timer properly.

Right now I have a counter that decrements every minute. The counter can be reset. The timer has a bunch of conditionals. The conditionals are a clickfest to manage and the logic is spread out in multiple parts of the app. Resetting a timer would make the simple use cases a lot easier to manage.

**Comment by ebiggz** [comment]
Hi @Rumbledethumps, thank you for the feature request and for the patience. We've got this implemented as a "Reset Timer" effect and it will be released in the next version (v5.47.2)
