### ISSUE TITLE
[Feature Request] Effect to purge currency

### ISSUE THREAD

**Issue by whatupcraig** [crowbartools/Firebot#1387]
**Describe the solution you'd like**
Under the update currency effect add an effect to purge a currency. 

**Additional context**

**Comment by CaveMobster** [comment]
@whatupcraig You should be able to achieve this in the effect by choosing the Set operation, and then choose 0. Does that solve your problem?

**Comment by whatupcraig** [comment]
> 
The set doesn't seem to work. I select for online users as well as all viewers but nothing changes. The add and remove points work fine.

**Comment by SReject** [comment]
Resolved with v5.52.0
