### ISSUE TITLE
[Feature Request]  live/offline  event 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1390]
**Describe the solution you'd like**
have an event trigger when the streamer account  is online or offline.

**Additional context**
this would be useful for automating sub/follow/emote only modes when  a stream starts or stops among auto posting into  discord live notifications.

**Comment by ebiggz** [comment]
Hey @CKY- Sorry for the extreme delay in replying to this. You could technically accomplish this by using the latest update of our [OBS Control script](https://github.com/ebiggz/firebot-script-obs-control) as it adds Stream Started/Stopped events. Not a native solution, but might be a decent alternative for now!

**Comment by CKY-** [comment]
I just updated. i use your script for a lot of cool things for controlling firebot and obs. would be nice if the script was native, still advanced but in the main application.
