### ISSUE TITLE
[Bug] twitch-pubsub-client ERROR Disconnected unexpectedly: [1006]

### ISSUE THREAD

**Issue by dev-kain** [crowbartools/Firebot#1442]
**Describe the bug**
```
[2021-10-28T06:25:05.336Z] ❌ twitch-pubsub-client ERROR Disconnected unexpectedly: [1006] 
debug: ViewerDB: Setting last seen date for 6 users
debug: ViewerDB: Compaction should be happening now. Compaction Interval: 30000
debug: Checking for command in message...
debug: Combining message segments...
debug: Searching for command...
debug: Incrementing timer chat line counters...
debug: Updating user StreamElements's "online" ttl to 450 secs
debug: Updating user StreamElements's "active" ttl to 300 secs 300
debug: ViewerDB: Compaction should be happening now. Compaction Interval: 30000
debug: Running currency timer...
[2021-10-28T06:26:14.302Z] ❌ twitch-pubsub-client ERROR Disconnected unexpectedly: [1006]
```

**Steps To Reproduce**
1. Login & connect
2. Wait a second
3. Got disconnected unexpectedly

**Expected behavior**
It won't disconnected unexpectedly or can reconnect.

**Screenshots**
![image](https://user-images.githubusercontent.com/44948284/139199211-eca701a8-3785-47fa-a2bb-bfae28d79834.png)
![image](https://user-images.githubusercontent.com/44948284/139199249-3a0c42c7-e0c0-421d-9b01-10409c17e737.png)

**Firebot Version:**
v5.45.0

**Computer OS:**
macOS big sur 11.2.3

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi @kaylooklook, thanks for well made bug report and apologies for the delay! We've had a number of updates since v5.45.0, many of which focused on improving the underlying libraries we use to connect to twitch. Are you still experiencing this issue when compiling the latest (v5.46.5)?

**Comment by kaylooklook** [comment]
I haven't paying attention to this problem for a long time, because it doesn't actually affect the use of pubsub.

**Comment by CaveMobster** [comment]
I'm gonna close this issue, but feel free to comment to comment on it if there are still any issues, @dev-kain.
