### ISSUE TITLE
[Bug] !command (systemcommand) is not working anymore

### ISSUE THREAD

**Issue by Mindless999** [crowbartools/Firebot#1443]
**Describe the bug**
!commands is not working / posting links

**Steps To Reproduce**
1. System commands
2. make sure !commands is enabled
3. Firebot Connected to chat (and verified)
4. do !commands in chat

**Expected behavior**
A link towards all the commands that are available

**Actual behavior**
No links or anything posted

**Firebot Version:**
v5.46.2

**Computer OS:**
Windows 10

**Comment by ebiggz** [comment]
This ha been resolved in the latest update. Thanks for the patience on this!
