### ISSUE TITLE
[Feature Request] Get Clip URL

### ISSUE THREAD

**Issue by MrCanerican** [crowbartools/Firebot#1446]
Query the Twitch "Get Clips" API: https://dev.twitch.tv/docs/api/reference#get-clips For more information.
As I read the API, we should be able to feed it a $user as [broadcaser_id], and limit the number of clip objects it returns with [first]. I would like to be able to iterate through the given [ended_at] and [started_at tags], to find the "freshest" clips. For my requested use case, I do not intend to pull more than 1 clip at a time, and thus the pagination is unneeded for me. But that does not make it useless for others, obviously.
I intend to use the returned object/array in a Show HTML effect, to play Twitch Clips on stream, as part of auto-raid shoutouts.

**Comment by MrCanerican** [comment]
Did not mean to add the tag. Can't seem to remove it. Apologies

**Comment by MrCanerican** [comment]
I am uncertain, as I have only read about it today. It may. I can figure out how to use that, as long as it is some kind of URL or array of URLs of clips, which our existing "YouTube Video" effect can play, perhaps with some scripting first of course.

**Comment by CaveMobster** [comment]
So what's the purpose of this issue? I don't see a problem that is related to Firebot.

**Comment by MrCanerican** [comment]
It's meant to be a feature request, so I can use that part of the Twitch API? But perhaps I already can and don't know how

**Comment by CaveMobster** [comment]
It shouldn't return a single URL as far as I know? It returns an array `clips` with one object in it, which has a `url` property.

**Comment by CaveMobster** [comment]
Closing this issue in favor of: https://github.com/crowbartools/Firebot/issues/1447

**Comment by MrCanerican** [comment]
These seem like different feature requests to me

**Comment by CaveMobster** [comment]
What is the difference?

**Comment by MrCanerican** [comment]
In this one, I am trying to use a part of the twitch API I cannot currently use. In the other, I want to be able to play Twitch Clips with their URL

**Comment by CaveMobster** [comment]
Right, I see! Sorry about that. I'll re-open it, but we would need to find an alternative to the v5 endpoint since we don't support v5 anymore. Just to clarify: do you want this to be a variable?

**Comment by MrCanerican** [comment]
I guess it would be a "variable" in FireBot lingo? $vars as it were. My usage would likely be like the rest of the Twitch API, which are also "variables", correct? Apologies for being uncertain here. I think so, yes.
I suspect I would feed a $twitchTopClip[arg1,arg2,arg3] variable, and it would return an array/object I could then address to get the element/piece needed (URL for clip image, URL for clip playback, clip title, view count, ETC) as needed.

**Comment by MrCanerican** [comment]
And I just noticed the specific API I am referencing is v5, so let me find the updated API we would need to use

**Comment by ebiggz** [comment]
Hi @MrCanerican!

The recently released **HTTP Request** effect should meet the use case described here as you can tell it to use Twitch auth and you can also tell it store the response data in a custom variable.

**Comment by MrCanerican** [comment]
That's perfect

**Comment by MrCanerican** [comment]
Thanks!!
