### ISSUE TITLE
[Feature Request] Ability to show Twitch clips with the Play Video effect

### ISSUE THREAD

**Issue by MrCanerican** [crowbartools/Firebot#1447]
Under the current, "Show Video" Effect, using the YouTube URL ability, feed it the URL for a twitch clip instead and have that play in the overlay. That, or have the drop-down option to choose "Twitch Clip", and feed it the URL.

**Comment by CaveMobster** [comment]
I edited the title for clarity.

**Comment by ebiggz** [comment]
Hi @MrCanerican this feature has been released. 

Additionally:
- Also added a "Random Clip" mode to Play Video effect where you supply a username for which to play a clip from
- Create Clip effect has been updated so it can play the created clip in the overlay.

**Comment by MrCanerican** [comment]
That's great. Thanks!!
