### ISSUE TITLE
[Bug] Profile Renaming 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1463]
**Describe the bug**
Enter a clear and concise description of what the bug is.

Unable to rename profiles. 

**Steps To Reproduce**
1. Go to '...' manage profile 
2. Click on '...' rename profile 
3. Change Name to '...' I set mine to main

**Expected behavior**
Enter a clear and concise description of what you expected to happen.

the profile file folder and profile should be renamed.. 
nothing happens. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8982158/142863234-4ce8c2c8-4308-4177-a06b-f0580e02cab5.png)
![image](https://user-images.githubusercontent.com/8982158/142863326-177408c9-05fd-480d-93e2-c4f6d41a4507.png)
![image](https://user-images.githubusercontent.com/8982158/142863367-962c8f49-1a1b-4e1e-83a5-87c130c292db.png)
![image](https://user-images.githubusercontent.com/8982158/142863399-8724e355-da13-4e3d-9b66-1ebd9f1c9cd7.png)

**Firebot Version:**

**Computer OS:**

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Looks like this bug is also in stable channel and not beta specific. Has been fixed for next release.
