### ISSUE TITLE
[Support] [Wiki] Unable to clone wiki on Windows due to special characters in page titles

### ISSUE THREAD

**Issue by zunderscore** [crowbartools/Firebot#1465]
**Help Request**
Unable to clone the wiki to make local edits on Windows because the following pages have special characters in the title:

[Developer: Building Games In Firebot V5](https://github.com/crowbartools/Firebot/wiki/Developer:-Building-Games-In-Firebot-V5)
[Tutorial: Changing Scenes with the Group Change effect](https://github.com/crowbartools/Firebot/wiki/Tutorial:-Changing-Scenes-with-the-Group-Change-effect)
[Going to get a new computer or doing a fresh reinstall of Windows on your current computer?](https://github.com/crowbartools/Firebot/wiki/Going-to-get-a-new-computer-or-doing-a-fresh-reinstall-of-Windows-on-your-current-computer%3F)

Per [GitHub's docs](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#about-wiki-filenames), wiki page titles shouldn't contain the special characters ```\ / : * ? " < > |``` because they can cause this issue.

**Comment by SReject** [comment]
Updated those entries
