### ISSUE TITLE
[Bug] is not possible to use defaultValue in $customVariable

### ISSUE THREAD

**Issue by Roger** [crowbartools/Firebot#1470]
**Describe the bug**
If `propertyPath` is not used, is not possible to use the defaultValue in $customVariable, I tough that `null` should be used as second argument if `propertyPath` was not needed, but looks like [here](https://github.com/crowbartools/Firebot/blob/master/backend/common/custom-variable-manager.js#L122) is trying to compare it as the type `null` but the argument is passed as an string `"null"`

**Steps To Reproduce**
Use anywhere something like this `$customVariable[name, null, "my default value"]`

**Expected behavior**
The custom variable replaced with "my default value" if is not set

**Firebot Version:**
v5.46.6

**Computer OS:**
Archlinux

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Roger** [comment]
I can submit a PR for this, but I don't know if `propertyPath == null || propertyPath == "null"` is the right way to handle it, I saw that Firebot is doing those kind of comparisons already

**Comment by ebiggz** [comment]
@Roger Good catch. I can't think of a markedly better approach over the `propertyPath == null || propertyPath === "null"` check. Our variable parser always returns arguments as strings so that was an oversight on my part.

**Comment by Roger** [comment]
Thanks for the feedback! just created the PR
