### ISSUE TITLE
[Bug] tts lost system voice and don't work

### ISSUE THREAD

**Issue by ohhiKot** [crowbartools/Firebot#1474]
**Describe the bug**
tts not working

**Steps To Reproduce**
1. triggered event w/ tts
2. nothing is happening

**Expected behavior**
read a chat message

**Screenshots**

**Firebot Version:** v5.47.1

**Computer OS:** win 10 and win 11
![image](https://user-images.githubusercontent.com/95049736/143491117-be6b2529-1b34-40d5-b966-dc5bac80abb2.png)

**Comment by ebiggz** [comment]
Thanks for this report @ohhiKot. We got a fix place and it will be in the next hotfix release going out tonight.

**Comment by ebiggz** [comment]
Fixed in v5.47.2
