### ISSUE TITLE
[Feature Request] sorting the event list, like the commands timers and preset effects 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1479]
**Describe the solution you'd like**
just to make everything conform and all UX the same, this would be nice. the only place I have noticed this is missing  is in the events lists. 

**Additional context**

**Comment by ebiggz** [comment]
This will be eventually resolved by #1195 so I am going to close this.

To be fully transparent, this will not be an easy task despite the request seeming simple enough. So it may not happen right away. I've spent many hours trying to get this to work and ultimately discovered that a complete page rewrite is in order as the way we handle event sets is incompatible with the sorting module we use.
