### ISSUE TITLE
[Feature Request] Pop out chat?

### ISSUE THREAD

**Issue by WatchersArcade** [crowbartools/Firebot#1485]
Hi I am a single screen lap top user that lives by your product. But even with another device it is hard to read chat and answer questions. Might you ever be able to put a screen overlay for full screen games so single monitor streams can interact better with chat and not have to worry if they chat is working without something spamming it?

**Comment by Firebottle** [comment]
I think this might be out of the scope of Firebot. Creating a full screen overlay that could show over full screen applications seems like an edge case that would need quite a bit of development work. I'm going to close for now and we'll gauge interest over time.
