### ISSUE TITLE
[Bug] [Wiki]

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1486]
**Describe the bug**
[Wiki]
[https://github.com/crowbartools/Firebot/wiki/Writing-Custom-Scripts#template-script](https://github.com/crowbartools/Firebot/wiki/Writing-Custom-Scripts#template-script)

For reference, it uses types that are defined here
the link returns 404 
https://github.com/crowbartools/firebot-custom-scripts-types/blob/main/index.d.ts
and should be
**https://github.com/crowbartools/firebot-custom-scripts-types/blob/main/types/index.d.ts**
## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by SReject** [comment]
Fixed
