### ISSUE TITLE
[Bug] Manage Fonts in settings opens the get Overlay path dialog instead

### ISSUE THREAD

**Issue by mdamaged** [crowbartools/Firebot#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click Manage Fonts in settings, it opens the get Overlay path dialog.

### Expected Behavior

To open the Manage Fonts dialog.

### Steps To Reproduce

1. Open settings.
2. Open Overlay
3. Click Manage Fonts

### Version

5.48.0

### What operating system are you using Firebot on?

Windows 10

**Comment by ebiggz** [comment]
Thanks for the heads up on this. 

We'll get a fix in and do a hotfix release today.

**Comment by ebiggz** [comment]
@mdamaged Fix is live with v5.48.1
