### ISSUE TITLE
[Support] Parse $floor and other numerical modifiers to $top outputs

### ISSUE THREAD

**Issue by Spedunkle** [crowbartools/Firebot#1494]
**Describe the solution you'd like**
Some metadata that I set doing which math looks like this: 3.8000000000000025. 

I would like to be able to do this: $topMetadataUser[metaData, 1, $floor[amount]]

For the output: 3

**Comment by CaveMobster** [comment]
@Spedunkle You have to use it like this: `$floor[$topMetadataUser[metaData, 1, amount]]`, since `amount` is only an argument to tell Firebot that you want the amount.

**Comment by CaveMobster** [comment]
@Spedunkle I'm going to close this issue. If this still doesn't work for you, please feel free to leave a comment here.
