### ISSUE TITLE
[Support] $customVariable[var] data will not be set with $randomActiveViewer[role]

### ISSUE THREAD

**Issue by Spedunkle** [crowbartools/Firebot#1495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

$customVariable[var] data will not be set with $randomActiveViewer[role] after the first pass for data. The output is the user who first triggered the event until Firebot resets, even if the $customVariable[var] is set to expire

If a new update to the $customVariable[var] is ran, and the first user is not in the Roles, it will output [Unable to get random active users].

After restarting Firebot to Enable Debug Logs and testing again, output for $customVariable[var] became null.

### Expected Behavior

$customVariable[var] updated randomly with a user from the role list using $randomActiveViewer[role] as the $customVariable[var] data.

### Steps To Reproduce

1. Create a New Role 'RoleTest'.
2. Create a Custom Variable.
2. Set the Name to Var1.
3. Set the Data to $randomActiveViewer[RoleTest].
4. Set UserX to RoleTest.
5. Run a Chat Effect with $customVariable[Var1].
6. Remove UserX from RoleTest.
7. Add UserY to RoleTest.
8. Run a Chat Effect with $customVariable[Var1].
9. Output should be [Unable to get random active users].

### Version

5.48.2

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Paying out 99 currency (a270c3e0-4542-11ec-9372-47c05a28ea00) for online users:
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] role ids 
[ 'efb104b0-4cb5-11ec-a67e-01cc984ab3a3' ]
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] user ids 
[ '42284265', '46953634', '746533520' ]
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Currency: Adjusting 99 currency to blackcloudzttv. a270c3e0-4542-11ec-9372-47c05a28ea00
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Currency: Adjusting 99 currency to spedunkle. a270c3e0-4542-11ec-9372-47c05a28ea00
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Currency: Adjusting 99 currency to yomomaho001. a270c3e0-4542-11ec-9372-47c05a28ea00
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Looking and handling replace variables...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Running firebot:set-user-metadata(b0b186b0-4cc7-11ec-a67e-01cc984ab3a3) effect...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Looking and handling replace variables...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Running firebot:set-user-metadata(894a88e0-4f3f-11ec-8d49-85ba958a1020) effect...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Looking and handling replace variables...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Getting random active viewer...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Running firebot:chat(b6137f60-4cb7-11ec-a67e-01cc984ab3a3) effect...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Sending message as bot.
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Looking and handling replace variables...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Running firebot:delay(878a08cc-4dc1-11ec-a67e-01cc984ab3a3) effect...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Checking for command in message...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Combining message segments...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Searching for command...
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Updating user spedunklebot's "online" ttl to 450 secs
13:42:26 GMT-0600 (Central Standard Time) - debug: [v5.48.2] Updating user spedunklebot's "active" ttl to 3600 secs 3600
```

### Contact Details (Optional)

Spedunkle#8383

**Comment by CaveMobster** [comment]
@Spedunkle Do you update the custom variable after you set it? Because the custom variable will not literally contain `$randomActiveViewer[RoleTest]`, it will contain the random active viewer's username. If you want it to update, you need to run the custom variable effect every time.

**Comment by CaveMobster** [comment]
@Spedunkle I'm going to close this issue. If this still doesn't work for you, please feel free to leave a comment here.
