### ISSUE TITLE
[Feature Request] Add the ability through the API to get the username or value from a particular position

### ISSUE THREAD

**Issue by whatupcraig** [crowbartools/Firebot#1507]
**Describe the solution you'd like**
Be able to get the top username of a currency or the top value of a currency. Similar to how the $topCurrencyUser[Points, 1, username] and the $topCurrencyUser[Points, 5, amount] works. 

**Additional context**

**Comment by CaveMobster** [comment]
@whatupcraig What you describe that you want to see, is exactly what the `$topCurrencyUser` does. To get the top username of a currency you use `$topCurrencyUser[Points, 1, username]`, and to get the top value you use `$topCurrencyUser[Points, 1, amount]`. Or am I misinterpreting your request?

**Comment by whatupcraig** [comment]
Ya this works great in the bot but I wanted to see if this is possible through the API. Right now I can get the currency amount for a particular user but not the top user or amount of a particular currency.

**Comment by CaveMobster** [comment]
In custom scripts you mean? I'm not currently very up-to-date with how custom scripts work, but it seems you should be able to access the currency DB? https://github.com/crowbartools/firebot-custom-scripts-types/blob/main/types/modules/currency-db.d.ts

**Comment by whatupcraig** [comment]
Kind of but having the ability to use GET through the API to retrive the information. Not through firebot itself but through the API.

**Comment by CaveMobster** [comment]
The next release will add a `/currency/:currencyName/top` endpoint, with which you can get the top currency holders of a given currency, with an optional `count` query parameter (default is 10) to get a custom list length.
