### ISSUE TITLE
[Feature Request] Reword the  ignore related gifted sub events option on the triggers page of settings.

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1522]
**Describe the solution you'd like**
the ignore related gifted sub events option on the triggers page of settings to be reworded. 

this is currently how it reads. 

Ignore Related Gift Sub Events
When this is enabled, Firebot will attempt to ignore subsequent Gift Sub events after a Community Gift Sub event. This means only the Community Sub event would fire instead of the **_Community Sub_** event AND an additional Gift Sub event for every 

I think it;s meant to read. 

Ignore Related Gift Sub Events
When this is enabled, Firebot will attempt to ignore subsequent Gift Sub events after a Community Gift Sub event. This means only the Community Sub event would fire instead of the **_Gift Sub_** event AND an additional Gift Sub event for every recipient.

**Additional context**

**Comment by CaveMobster** [comment]
No, the current wording is correct. I'll try to break it down to make it a bit easier to read:
If you choose to ignore: The Community Sub event fires 
If you choose **not** to ignore: The Community Sub event fires, but the Gift Sub event fires too for every recipient.

Does that clarify it a bit?

**Comment by CKY-** [comment]
Wait what? 
the wording used is  "This means only the Community Sub event would fire instead of the Gift Sub event AND an additional Gift Sub event for every recipient." so the community event sub will fire instead of the community event sub? maybe this is a grammar issue and a comma is needed? I'm not the best at grammar.
and maybe add the word both?

"This means only the Community Sub event would fire, instead of both the Community Sub event AND an additional Gift Sub event for every recipient."

it's the wording that is the struggle for some.

**Comment by CaveMobster** [comment]
Your description implies that only the first Gift Sub event triggers when that setting is enabled, which is not true because it's the Community Gift Sub event that triggers, not the Gift Sub event. Those are two separate events.

I'm not inclined to change it honestly.
