### ISSUE TITLE
[Bug] Heist Game and Currency Payout

### ISSUE THREAD

**Issue by valkariye** [crowbartools/Firebot#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The command for the heist game to check your current balance is sending out messages twice, and the Currency Payout is not paying out any users in the allotted time. 
![Capture](https://user-images.githubusercontent.com/97483518/148852090-c77b2f19-c6f1-4a05-a88e-26922ba7ccbb.PNG)

### Expected Behavior

The command should only send the message once, and payout is expected to happen in the allotted time.

### Version

v5.49.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Valk#4509

**Comment by ebiggz** [comment]
Thanks for the report @valkariye ! This have been fixed in v5.49.3 which was just released

https://github.com/crowbartools/Firebot/releases/tag/v5.49.3
