### ISSUE TITLE
[Feature Request] a filter that can't be bypassed by the simulate events.

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1547]
**Describe the solution you'd like**
when simulating events  it would be nice to ignore the simulation in an event. 

Example: 
outputting to files having a host event that will write to a file and another that will play the event such as chat message and overlay.
selecting the ignore simulation will allow  the overlay and chat messages to be displayed but not  amend any information to files. this will allow the simulation  without the need of reseting anything if used in this manor. 

I tried using  username is not firebot and username contains bot  but simulate event seems to bypass all filters adding a field that is I dont know canSimulate to events and a checkbox that is default checked on the event ui would be good  cause you can still bypass the filters that as is  and be able to turn off simulation for that events effects. 

**Additional context**

**Comment by CaveMobster** [comment]
We recently implemented an option to disable effects in an effect list, would that help to solve your issue?

**Comment by CKY-** [comment]
not really, I have event sets, and each type in is there own set, so i have 3DEvents, Credits, OBS, General so at any given time i have 3 sub events active or 3 host events or 3 of any event that can come in. could i disable the credits event list Yes but not while im live. its the live testing that i do that adds firebot to the credits list while i simulate an event. I do a lot of live creation of firebot events and effects. especially when im adding to the stream. i will have a 8-10 hour stream building 3d assets  just to apply to the overlays and when im done and during the development of it  its nice to see how firebot is handing object data or whatever so simulating it is the most effencet way. and if a user subs or follows or hosts  and i have it disabled during testing they wont be included in the credits. I understand this may be an edge case but i think you can see the reasoning for it. because sometimes you can also get someone stopping by asking how you did this and that and then you want to show it off somehow and then it triggers all the triggers and writes to file and stuffs.

**Comment by CaveMobster** [comment]
I see! That makes sense, thank you for explaining your case. I think it would definitely be nice to have some more control over it.

**Comment by CKY-** [comment]
adding a condition to the setups that ignores username:firebot works thank you all for your time im going to retract this, and close it
