### ISSUE TITLE
[Bug] VIP Users not getting VIP role

### ISSUE THREAD

**Issue by Runesun** [crowbartools/Firebot#1556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

VIP users do not seem to be getting the VIP role.

As such VIP features do not work for them such as showing up in the right place on the Dashboard or any actions that are VIP based.

### Expected Behavior

VIP is granted to VIP users.

### Steps To Reproduce

1) Give a user VIP. 
2) Have them join the chat.  (unsure if this is necessary)
3) VIP not granted in Firebot.

### Version

v5.49.4

### What operating system are you using Firebot on?

Windows 10

**Comment by CaveMobster** [comment]
Yes, this is a known issue and has been fixed for the next release. Thank you for reporting it!
