### ISSUE TITLE
[Bug] Ban Effect has Unhandled Promise Rejection For Already Banned Users

### ISSUE THREAD

**Issue by Patchshifter** [crowbartools/Firebot#1557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When that ban effect is run nothing happens, except there is a console log:
ERROR Unhandled promise rejection already_banned

When you use the command on a user that isn't banned you will a message in OBS saying it banned the user (patchshifter banned (user). Reason: Banned by Firebot.), however there is no feedback given for trying to use it on someone thats banned already.

This does not occur with the unban action, only the ban action.

### Expected Behavior

The exception could be handled, and some sort of notification should indicate the user is already banned.
Twitch chat handles this by saying (user is currently banned in this channel.)

### Steps To Reproduce

1. Create an effect with the Ban action, and set Target Username to a user that is already banned.
2.  Run that effect

### Version

5.49.4

### What operating system are you using Firebot on?

Windows 10

**Comment by CaveMobster** [comment]
I'm changing this into an Enhancement, as this is not necessarily a bug but something we haven't implemented.
