### ISSUE TITLE
[Support] Follow Events Not Showing Up in Firebot

### ISSUE THREAD

**Issue by Patchshifter** [crowbartools/Firebot#1560]
**Help Request**

I am working on an issue for a friend whose follower alerts aren't working.  His other alerts (Subs, Hosts, Raids, etc) are working, but Follows are not.  When he previews the event trigger all the effects play as normal, but when an actual follow comes in the event does not trigger, and the follows do not show up in the Activity Feed on the Dashboard.

This is on Version 5.49.4

We've done the following for troubleshooting:

* Deleted the event trigger and re-created it
* Uninstalled Firebot, deleted the leftovers in %APPDATA%, and reinstalled Firebot (we have 
* Ensured the Event is enabled in the Activity Feed
* Tested follows with real accounts with the Developer Tools Console open.  There aren't any errors, or any information related to a following coming in. 
* Turned on Debugging and looked at the logs after we followed with accounts again (different accounts than the previous step).  I have the log file, and can attach it if needed

The Event is relatively simple, it consists of the following effects:
* Chat
* Play Sound
* Show Text
* Show Image/GIF

All of them work with the preview, as well.

I'm not really sure where to go from here, the only thing that differs from a setup that I've done for myself is that he's not using firebot with a bot account--just the streamer account.  I am not sure if this could be causing the issue, as like I said before the other events for Hosts, Bits, Raids, Subs, etc all work.

**Comment by CaveMobster** [comment]
@Patchshifter Is this the Twitch Follow event? Or is it the Follow event from one of the integrations?

**Comment by Patchshifter** [comment]
> @Patchshifter Is this the Twitch Follow event? Or is it the Follow event from one of the integrations?

oops, these are the Twitch follow events

**Comment by CaveMobster** [comment]
Right, thank you! A log file would be useful, so if you could attach that, that would be great. 😃

**Comment by Patchshifter** [comment]
Here you go
[2022-01-31 (1).log](https://github.com/crowbartools/Firebot/files/7984135/2022-01-31.1.log)
!

**Comment by CaveMobster** [comment]
Interesting! I don't see anything that's going wrong. It's worth noting that Firebot doesn't receive Follows the same way it receives Hosts, Raids, etc. Since Twitch don't offer an event for it through the connection we use, Firebot check the follower list every 10 seconds to see if there are new followers.

Is it still not coming in after waiting for 10 seconds?

**Comment by Patchshifter** [comment]
Yea, that was the thing for me too, I saw nothing in the logs either--but no, nothing happens after 10 seconds either, the alert doesn't show up, and it doesn't show up in activity feed either

**Comment by CaveMobster** [comment]
@Patchshifter Did you also try logging out and back in with the streamer account? Otherwise it might help to delete `auth-twitch.json` in `%AppData%/Firebot/v5/profiles/[selected-profile]`.

**Comment by Patchshifter** [comment]
Sorry for the delay on this, was side tracked with a new game--but I talked to them and they had tried logging out and in again.  I"m going to see if I can get one of his back up zips and load it into another profile on my firebot and see if the issue is there, too, and he will try deleting the auth-twitch.json file

**Comment by Patchshifter** [comment]
Just checked with him, deleting the auth-twitch.json didn't fix it.

I also took one of his backups and have it loaded in my firebot now and am seeing the same thing 🤔 , no follow alerts.

**Comment by CaveMobster** [comment]
@Patchshifter Did you change the logins to your own in that backup? Or did you leave his accounts in?

**Comment by Patchshifter** [comment]
@CaveMobster The logins are still his account.  I can try switching it to mine today

**Comment by Patchshifter** [comment]
Alright, so this is weird.  The follow alerts work on my firebot now--I think it was my issue (i didn't actually connect to twitch, whoops). 

However, it still doesn't work on his, and over a screenshare i made sure he was connected to twitch.  

This issue is unique to his system, at least, and I'm not even sure it's a firebot issue at this point

**Comment by CaveMobster** [comment]
@Patchshifter Oops, so sorry for the late reply. Do you know if the follow alerts work for other parties like StreamElements, Streamlabs, etc? Not only in the bot, but on their own sites as well?

**Comment by Patchshifter** [comment]
@CaveMobster i am so sorry for the late reply on this. I’m not sure this is an issue still, the person wound up using a different service for alerts. I’m going to request this to be closed since I can’t reproduce it anymore
