### ISSUE TITLE
[Support]  Make an API request (JSON response) to get access over a custom variable.

### ISSUE THREAD

**Issue by bradhard** [crowbartools/Firebot#1575]
I tried to get access to the data of an API request (JSON). 
At the Custom Variable Inspector i get "[object Object]" back.
e.g. if i try **$readApi[https://api.disneyapi.dev/characters, data.3.name]** > i got the right data and can save a single value.
But if i want to save the whole JSON-Object inside my Custom Variable can´t get access later.

(If i write the data as JSON directly into the custom variable data-field it work as aspected.)

Do i something wrong or is this a bug?

Workflow: 
1. Create new !command with a Custom Variable Effect (Name: LoadDataAPI) with a readapi request (response JSON).
2. Repuest: `$readApi[https://api.disneyapi.dev/characters]`
3. Create a second effect e.g. show HTML an try to output a single value from the custom variable. `<div>$customVariable[LoadDataAPI, data.3.name]</div>`
4. Output: null

thanks and best regards

**Comment by CaveMobster** [comment]
@bradhard Try the HTTP Request Effect instead. `$readApi` can be used to output and display data directly, but isn't meant to manipulate data like that.
