### ISSUE TITLE
[Bug] Stream Loots Gifted Packs Broken

### ISSUE THREAD

**Issue by dadthegamer** [crowbartools/Firebot#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Firebot does not catch when someone is gifting packs to the community. It will recognize when someone buys an individual pack but not gifted packs.

### Expected Behavior

When someone gifts packs on Stream Loots website an event will trigger. I have setup a test event within Firebot to trigger when someone gifts but nothing happened. 

### Steps To Reproduce

1. Go to streamloots.com
2. Gift a pack
3. Wait for Firebot

### Version

5.50.3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Dad The Gamer#5318

**Comment by CaveMobster** [comment]
@whatupcraig 

What filters and effects do you use in your event?

**Comment by CaveMobster** [comment]
Okay. Can you verify that you have the alerts for gifted packs enabled in Streamloots?

**Comment by whatupcraig** [comment]
> 

I do. I have all alerts enabled.

**Comment by whatupcraig** [comment]
So I am doing a little testing and noticing that if I run a test on stream loots page on purchasing or gifting it will trigger, however, if I actually gift a chest using my bot account it does not trigger.

**Comment by zunderscore** [comment]
As there have been no updates for over a year, closing this issue. If you're still experiencing a problem, please create a thread in the issues channel of our Discord.
