### ISSUE TITLE
[Feature Request] Api effect custom variable option 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1587]
**Describe the solution you'd like**
Api effect  has one option to send as chat 

can we add  a variable option to it for use  with TTS and other effects 

**Additional context**
CC:
SheriffMcLawdog — Today at 11:17 AM
Hey there! I was elated to find firebot and have been using it for a little while. Its exactly what I had been searching for. I was wondering if someone could help me out. I have the dadjokes api set up as a !dadjoke command and i would like to have tts read out the response but i can't figure out how to set it up with variables. I have figured out using target and arg and chatmessage variables in other instances but can seen to get this to work. Thank you so much.

https://discord.com/channels/372817064034959370/372818514312167424/942484770724675594

**Comment by CKY-** [comment]
closing this in favor of 
#1740 
If this could be included in that.

**Comment by SReject** [comment]
Resolved with release v5.53.0
