### ISSUE TITLE
[Bug] RegEX ignores Case

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/crowbartools/Firebot/blob/5e71ffd98fdd0c7b59a43ade6d1c5aed592cbfc1/backend/events/filters/builtin/message.js#L53 regex match is set up with gi, or global case insensitive

discussion in discord:
 https://discord.com/channels/372817064034959370/842172237553336361/944694961616617523

### Expected Behavior

 regex match should wait for user to specify [a-z|A-Z|0-9]{2,}\.[a-z|A-Z]{2,}

### Steps To Reproduce

impot the setup in the discord thread type more than 9 lowercase letters 

### Version

5.50.4

### What operating system are you using Firebot on?

Windows 10

**Comment by SReject** [comment]
This has been added in the next version in the form of new filters:

Renamed case-insensitive filters to `matches regex (case-insensitive)` and `doesn't match regex (case insensitive)`

Added `matches regex` and `doesn't match regex` for case sensitivity.

Past regex filters will be assumed as case-insensitive
