### ISSUE TITLE
[Feature Request] Programmatic access to adding quotes 

### ISSUE THREAD

**Issue by TioMecanico** [crowbartools/Firebot#1597]
**Describe the solution you'd like**
A way to add quotes to the quote system without going through the standard !quote command

**Additional context**
Two examples of ways it could be used:
A channel point redemption that adds a quote to the list
A custom command that adds a quote to the list with an additional effects as well

**Comment by SReject** [comment]
For clarity, do you mean something of a "Add Quote" Effect?

**Comment by TioMecanico** [comment]
Yeah, basically. Something that takes input (either in one or two arguments) and acts as if someone had done `!quote add` with them, but without using the `!quote add` Command.

**Comment by zunderscore** [comment]
@TioMecanico, with the stuff added between the Add Quote effect and the new API endpoints, does that satisfy what you were looking for here? If not, what else would help?

**Comment by SReject** [comment]
Resolved with v5.52.0
