### ISSUE TITLE
Guides [Support] 

### ISSUE THREAD

**Issue by Somnophobe** [crowbartools/Firebot#1598]
**Help Request**
I wrote some guides for Firebot to help some of the people I collaborate with, and they seem to be proving helpful. This isn't really a request for help so much as a request to make them available to anyone who needs them, I guess? IDK.

Here's the link to the parent folder: [link](https://drive.google.com/drive/folders/1Ens8vumImkhKHmSz4-2f0BWNSub-S6T8?usp=sharing)

**Comment by brumoen** [comment]
Thanks for these, they seem to cover the basic needs for most users venturing into Firebot for the first time.

Added information about your written guides and heyappl's video tutorials to the Getting Started page in the Wiki for now, we are working on another wiki where it will be easier for users to contribute and add stuff like this.

[Firebot Wiki](https://github.com/crowbartools/Firebot/wiki/Getting-Started)
