### ISSUE TITLE
[Bug] Quick Action Settings don't persist

### ISSUE THREAD

**Issue by TioMecanico** [crowbartools/Firebot#1599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Quick actions disabled in Quick Action Settings restore when clicking off of dashboard and back into it.

### Expected Behavior

Disabled actions remain disabled across sessions and tab changes.

### Steps To Reproduce

From Dashboard, click Quick Action Settings
Disable any quick action
Close settings
Click to another tab (tested Commands, Events, Timers)
Click back to Dashboard
> Quick action has re-enabled

### Version

5.50.4 (also happened in 5.50.3)

### What operating system are you using Firebot on?

Windows 10

**Comment by AdamOfGeekheim** [comment]
Beat me by 2 hours! I just discovered the quick actions and thought i was going crazy when they kept coming back.
