### ISSUE TITLE
[Bug]  In the Update Currency Effect set all 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

not setting  all viewers  selected currency to 0

### Expected Behavior

set all users to whatever value is supplied 

### Steps To Reproduce

https://discord.com/channels/372817064034959370/372818514312167424/946503933826842726

### Version

v5.50.4

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
there are no errors in the devtools or logs
```

**Comment by SReject** [comment]
Resolved with v5.52.0
