### ISSUE TITLE
[Bug] Events not working properly.

### ISSUE THREAD

**Issue by valkariye** [crowbartools/Firebot#1604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I test an event, the "play sound", "show text" and "show image/GIF" events aren't working. They don't show up on screen, nor do I hear the alert.

### Expected Behavior

I expected the effect queue to play the alert as it was set up. This is not the case. It has worked before.
![Capture](https://user-images.githubusercontent.com/97483518/155751372-412c600f-c910-4a53-9d6c-898f9ed86525.PNG)

### Version

v5.50.4

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Valk#4509

**Comment by TioMecanico** [comment]
This sounds like the overlay isn't loaded/loading.

So just to double check: you've got the overlay loaded in OBS and in the relevant scene, yeah?

**Comment by zunderscore** [comment]
Hey @valkariye, just checking if this is still an issue. If it is, I would recommend joining the Discord and seeing if someone can help troubleshoot. If not, I'll go ahead and close this ticket.

**Comment by Firebottle** [comment]
I'm going to go ahead and close this as it's been a week without response. @valkariye if you still need support, please see our discord!
