### ISSUE TITLE
[Bug] custom variable effect appends data to json array

### ISSUE THREAD

**Issue by mystery-e204** [crowbartools/Firebot#1630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting a custom variable via effects to a single value and the variable was previously a JSON array, the value is appended to the array.

### Expected Behavior

The custom variable that was previously a JSON array should be overwritten to *only* contain the new single value.

### Steps To Reproduce

* Add new command
* Go to advanced mode
* Add new effect "Custom Variable"
  * Set Variable Name to `test`
  * Set Variable Data to `[1,2]`
  * Leave Property Path empty
* Add new effect "Custom Variable" after the previous effect
  * Set Variable Name to `test`
  * Set Variable Data to `3`
  * Leave Property Path empty
* Check custom variable inspector
* Result will be `[1,2,3]` and not `3`

### Version

5.50.4

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

Mystery#4183

**Comment by SReject** [comment]
This is intentional behavior, see: https://github.com/crowbartools/Firebot/wiki/Advanced-Uses#arrays

To overwrite a custom variable that is an array, use a Custom Variable effect to set the value to `null`, then use a second to set the new value.
