### ISSUE TITLE
[Feature Request] Regex capture groups

### ISSUE THREAD

**Issue by mystery-e204** [crowbartools/Firebot#1631]
It would be nice to have a variable, say `$regexGroups[string, expression, flags]`, that returns a JSON array containing all capture groups. For example:
`$regexGroups["foo69bar420", "(\d+)bar(\d+)"]`
should return
`[ 69, 420 ]`
as a JSON array. This can technically be done with a `$replace` but I have run into numerous issues on more complicated strings, especially when they contain symbols from `"[],`.

**Comment by SReject** [comment]
> especially when they contain symbols from "[],

our expression parser supports block escaping in the form of double backticks:

```
$replace[ ``[],``, ``[``, ''] returns ']
```

**Comment by mystery-e204** [comment]
Ahh, that's neat, thx for the quick response. I was unaware of the double back ticks. This should make writing more regex patterns a lot easier. I'll try it out and see if it works the way I imagine it.

**Comment by mystery-e204** [comment]
So, after playing around with it for a while, I found it sufficient to use `$replace` to create a JSON array from a regex query like above. I'm closing this.
