### ISSUE TITLE
[Bug] $vars Menu on HTTP Request URL 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

it's not a bug it's more of an annoyance that the menu is covered up and not searchable. can it please be moved down under the text field.

when you click on the $vars button the modal opens up too far up.

![image](https://user-images.githubusercontent.com/8982158/159692594-2ac9aeeb-1479-437b-a4d6-fdae80f956c7.png)

### Expected Behavior

the modal to be in view and searchable. 

### Version

v5.50.4

### What operating system are you using Firebot on?

Windows 10

**Comment by SReject** [comment]
Resolved with v5.52.0
