### ISSUE TITLE
[Bug] ArrayFind result on an array of strings should return index

### ISSUE THREAD

**Issue by Samuel38** [crowbartools/Firebot#1638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We create custom variable 
`test` with content `["test1", "test2", "test3"]`
Using `$arrayFind[test, "test2"]` will return `test2`
Using `$arrayFind[test, "test4"]` will return `null`

### Expected Behavior

Using `$arrayFind[test, "test2"]` should return `2`
Using `$arrayFind[test, "test4"]` should return `null`

In the current state, running `$arrayFind` on an array of strings doesn't return relevant information. 
While we would be looking at the location of the string in the array, it only returns the string we have input if it existed. So aside from telling us that the array actually contains that string, it doesn't say anything. 

### Version

5.50.4

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Alastor#8593 in discord

**Comment by ebiggz** [comment]
Hi @Samuel38! Thanks for the report. 

The current behavior is actually indeed the intended behavior. The biggest use case is most evident with the second example provided in the app when you are looking to find objects in an array:
```
$arrayFind["[{\\"username\\": \\"ebiggz\\"},{\\"username\\": \\"MageEnclave\\"}]", ebiggz, username]
```
Imagine you have an array of user data you are tracking and you want to get the object for a specific person. You can use their username to find the full object. This behavior is intended to mirror the `array.find` functionality in javascript.

The functionality you expect is valid and would be useful too though. So perhaps we create a secondary variable for that functionality ie:
```
$arrayFindIndex[...]
```

**Comment by Samuel38** [comment]
Hi, 
Thanks for your answer. 

I do see the use case in extracting objects from an array, and I'm not suggesting to change that one. 
My thought was that what is returned in the case where no property path is given makes it useless. Adding another function would be fine too, but would have the drawback of multiplying functions and maybe overwhelming a little bit the users that are less experienced in programming. 
On the other hand, my suggestion makes the behaviour of this function less consistent. 
I guess a middle ground could be to add an optionnal argument to explicitly ask for the index `$arrayFind[name, match, path=null, giveIndex=false]`.
