### ISSUE TITLE
[Feature Request] Preset effect list should prompt for parameters on test run

### ISSUE THREAD

**Issue by Samuel38** [crowbartools/Firebot#1653]
**Describe the solution you'd like**
When you hit "Test effects" on a preset effect list that has input parameters, it should open a window prompting for the value to use for the input parameters specified. 
It would also be nice to have the option for this window to appear when called from a quick action slot

**Additional context**
This would allow to run things with variable inputs without possibly entering sensitive info into chat, or generally, without necessarily cluttering it.

**Comment by SReject** [comment]
Resolved with v5.52.0
