### ISSUE TITLE
[Feature Request] : Stream Summary

### ISSUE THREAD

**Issue by PSingletary** [crowbartools/Firebot#1656]
# Stream Summary
- Hype Trains - How Many at each level (1 train at level 5, 2 trains at level 3)
- Gifted Subs - Who gave How Many (Gifter 1 gave 5 subs, Gifter 2 gave 10 subs)
- Bits - Who Gave
- Subscribed/Resusbscribed - Who
- New Followers - How Many
- Total Followers - How Many

# Additional context
## Twitch OAuth scopes
https://dev.twitch.tv/docs/authentication#scopes
### Required Scopes
- channel:read:hype_train
- channel:read:subscriptions
- bits:read

- [ ] Extend schema of _statsDatabase.js_ or _userDatabase.js_  counting events, and tracking participants
- [ ] Read Hype Train End at what Level (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelhype_trainend)
- [ ] Count Hype Trains of Each Level - Data Storage
- [ ] Read Subs Gifted (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelsubscriptiongift)
- [ ] For Each Chatter Total Count of Subs Gifted - Data Storage
- [ ] Read Bits Cheered (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelcheer)
- [ ] Read Subscribe and record each chatter (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelsubscribe)
- [ ] Read ReSubscribe and record each chatter (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelsubscriptionmessage)
- [ ] Read New Followers (https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#channelfollow) *NO SCOPE NEEDED*
- [ ] Total Count of New Followers during stream - Data Storage
- [ ] _Keep for a Stream Summary Overlay Feature?_ (another feature to replicate ~tream~abs ~nd ~redits)
- [ ] Write data to webhook (Like Discord / Slack / Teams )
- [ ] _Dispose of data?_ (Was thinking send & forget, but design for another feature of leaderboard?)

**Comment by brumoen** [comment]
We don't use eventsub due to Firebot being a local application that doesn't rely on third-party server solutions, so none of these are possible at the moment with the current version of Firebot.

But there is a Credits script/setup available that keeps track during your stream made by CaveMobster:
https://github.com/CaveMobster/firebot-setup-end-credits/releases

**Comment by PSingletary** [comment]
Ahh, then it seems all i want to do is go there and request that all that information gets push out as a webhook.
THX! 🎉
