### ISSUE TITLE
[Feature Request] Elgato Light Strip support

### ISSUE THREAD

**Issue by zunderscore** [crowbartools/Firebot#1657]
**Describe the solution you'd like**
I'd like to see support for controlling Elgato Light Strips, like the existing support for Elgato Key Lights.

**Additional context**
The existing helper library/integration detects both Key Lights and Light Strips but doesn't properly control Light Strips because of API differences. I built an [updated library](https://www.npmjs.com/package/@zunderscore/elgato-light-control) that fixes the issues (and uses axios instead of request, and cleans up a bunch of the code, etc.). So we could bring in the new library, fix the code for Key Lights, then add the additional effect for Light Strips.

I'm probably gonna go ahead and work on this.

**Comment by SReject** [comment]
Resolved with v5.52.0
