### ISSUE TITLE
[Feature Request] Corrective Naming for game/category 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1661]
**Describe the solution you'd like**
Uniformed naning for "category" 
in event it is "Category Changed"
in effect list it is "Set Stream Game"
in vars it is "$game"

changing the vars will probably cause issues 
so maybe 
in event it is "Game Changed"
in effect list it is "Set Game"
in vars it is "$game"

or 

I dont know 
having 3 different names that are the same things is a bit confusing

**Comment by SReject** [comment]
Resolved with v5.52.0
