### ISSUE TITLE
[Feature Request] Implement Announcements

### ISSUE THREAD

**Issue by JRawly** [crowbartools/Firebot#1665]
**Describe the solution you'd like**
When adding a command/timer/etc the ability to be able to use /announce (and the other colour commands) so that messages from the bot can be announced rather than just said.

**Additional context**
See: https://twitter.com/TwitchSupport/status/1509634525982302208 for the twitter announcement re this functionality on twitch.

In addition to being able to select either /announce or /announcecolour perhaps a random option to randomly select one of the colours when posting

**Comment by SReject** [comment]
Resolved with v5.52.0
