### ISSUE TITLE
[Feature Request] Bot account should always be considered an active user

### ISSUE THREAD

**Issue by Samuel38** [crowbartools/Firebot#1668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently, if you check that the bot account is an active user, it will not count even if it just talked. 

### Expected Behavior

I'd expect the bot (and the streamer) to always be considered active users, even if they haven't chatted recently, as they are the 2 accounts you can actually always consider active. 
At the very least the bot account should take into account when it talks to chat as making it active. 

### Version

5.51.0

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

Alastor#8593 in discord

**Comment by brumoen** [comment]
This is by design, but you can adjust this. Open the viewer model for the streamer or bot account and remove the tick on the "Don't allow on active user list"

**Comment by zunderscore** [comment]
I've verified that this is working correctly in 5.51.0. Both my streamer and bot accounts are allowed on the active user list and they both will be returned in the `$randomActiveUser` variable.

**Comment by SReject** [comment]
To clarify:

When the streamer and bot accounts are allowed to be treated as active users, the request is for an option to always treat them as active.
