### ISSUE TITLE
[Bug] topMetadata variable fails replace due to missing checks

### ISSUE THREAD

**Issue by brumoen** [crowbartools/Firebot#1686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you query the database for more records of a certain metadata key then it has available it fails to parse the data into the variable.

### Expected Behavior

Output of the queried data into the variable, limited to the amount of records that has the correct key.

### Steps To Reproduce

Create a chat effect with `$topMetadata[lurk, 5]` where you don't have 5 records in the database with the given metadata key(lurk).
Run the command and it outputs `$topMetadata[lurk, 5]` in chat instead of the expected data.

### Version

5.51.0

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
warn: Unable to parse variables for value: '$topMetadata[lurk, 5]' 
{
  message: "Cannot read property 'lurk' of undefined",
  stack: "TypeError: Cannot read property 'lurk' of undefined\n" +
    '    at /home/perry/Development/Firebot/backend/variables/builtin/top-metadata.js:39:76\n' +
    '    at Array.map (<anonymous>)\n' +
    '    at Object.evaluator (/home/perry/Development/Firebot/backend/variables/builtin/top-metadata.js:38:48)\n' +
    '    at async VariableToken.evaluate (/home/perry/Development/Firebot/node_modules/expressionish/src/tokens/variable.js:66:24)\n' +
    '    at async evaluate (/home/perry/Development/Firebot/node_modules/expressionish/src/evaluate.js:50:21)\n' +
    '    at async findAndReplaceVariables (/home/perry/Development/Firebot/backend/common/effect-runner.js:29:37)\n' +
    '    at async runEffects (/home/perry/Development/Firebot/backend/common/effect-runner.js:113:9)'
}
```

**Comment by SReject** [comment]
Resolved with v5.52.0
