### ISSUE TITLE
[Feature Request]  shoutout Overlay text "LAST SEEN PLAYING" to be modifiable.

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1691]
Please make allow for custom user input of the text fields  on the shoutout Overlay so that the verbiage of  "LAST SEEN PLAYING" can be modified.
 
CC discord: Gede — Today at 8:34 AM
i want change the text "LAST SEEN PLAYING"

**Comment by DickerSauerlaender** [comment]
The overlaytext should be editable, absolutely!

**Comment by SReject** [comment]
Resolved with v5.52.0
