### ISSUE TITLE
[Feature Request] Remove whispers from bid game

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1706]
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/8982158/165846208-cc11ae55-1752-436f-a20f-041e313e0f46.png)
there is no way to set what the the message is or how its sent  or to turn off messages in the bid command, Whispers are unreliable. 
**Additional context**

**Comment by SReject** [comment]
Resolved with v5.52.0
