### ISSUE TITLE
[Feature Request]  A way to mute a video that is playing as an effect

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1714]
**Describe the solution you'd like**
CC: V1perN3st
A way to mute videos on play in the overlay. 

`The idea would be to mute the video's audio completely and play a separate sound file using the "Run Effect List" at the same time. Or just to have the video play without audio, but also allow other videos to play with audio within the same overlay.`
**Additional context**

**Comment by SReject** [comment]
Resolved with v5.52.0
