### ISSUE TITLE
[Bug] Clear effect dropdown not showing "Default" when selected

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/8982158/167019213-be2934f6-105d-4dbf-8acc-3e0e8a372fb8.png)
selecting "Default" overlay is not rendering in the item selection of the dropdown menu,
I have checked html and text both work and I can't find a change that would have broken it  in the last week or so. 

### Version

 current dev build 2022-05-05

### What operating system are you using Firebot on?

Windows 10

**Comment by ebiggz** [comment]
Simplified title as this is a 4 month old bug not tied to any recent dev build

**Comment by SReject** [comment]
Resolved with v5.52.0
