### ISSUE TITLE
[Bug] regex variable when used in chat effect display in chat and other effect without evaluation 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

$regexExec[string, expression, flags]  and $regexExec[string, expression]
using this variable returns itself as the message  
![image](https://user-images.githubusercontent.com/8982158/167482751-4e1bbab6-0b20-4ec2-b08f-9406ced601d0.png)
using it in log message
![image](https://user-images.githubusercontent.com/8982158/167482878-89e4ed00-8883-4f63-8c21-fdf481512c92.png)

### Expected Behavior

return the text of the variable 

### Version

5.51.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

cky#0495

**Comment by CKY-** [comment]
to clarify i have tried it both ways 
![image](https://user-images.githubusercontent.com/8982158/167486029-defe34b5-735e-4c82-a782-4d42f79efe6b.png)
![image](https://user-images.githubusercontent.com/8982158/167486096-9c0daf2c-16f9-4e34-8eec-6d86af99124f.png)

**Comment by SReject** [comment]
Resolved with v5.52.0
