### ISSUE TITLE
[Bug] Commands Currency auto deduction is being removed while command is on cooldown 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

create a command  
use the currency  restriction with 
Automatically deduct currency from user if restrictions pass enabled 
set a cooldown user and global 
while the command is on cooldown the command still Automatically deducts currency from user

CC:discord via Shen Nung 
Hello, I'm trying to set up a currency system where viewers can purchase an image and it stays on screen for the duration of the stream.  Each image can only be bought once per stream and I've set the global cooldown to a high number to ensure that.  The restriction used is currency >= cost and I have auto-deduction of currency on.  The only issue I'm having is that if the command is used while on cooldown, it still auto-deducts the currency (the cooldown message appears in chat as normal).  Any suggestions?

### Expected Behavior

do Nothing while on cool down 

### Version

v5.52.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

cky

**Comment by SReject** [comment]
Resolved with release v5.53.0
