### ISSUE TITLE
[Feature Request] Integrate Twitch Predictions and Polls

### ISSUE THREAD

**Issue by dadthegamer** [crowbartools/Firebot#1750]
**Describe the solution you'd like**
Be able to trigger effects when there is a new twitch prediction or poll.

**Comment by iamdadmin** [comment]
Blocked in Firebot-v5. Requires a webhook to retrieve this data from EventSub, which isn't currently possible in v5.

**Comment by meza** [comment]
Would really appreciate this, it's the only missing piece of my migration from Lumia
