### ISSUE TITLE
[Feature Request] manage alias(es) for custom commands through chat 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1751]
**Describe the solution you'd like**

Please add the ability to add alias of custom commands,

**Additional context**

CC:Discord: S1D3WYZ
is there a chat-based command [system command] that can edit command [custom] aliases .. eg custom command: !burger ... want to add alias !hamburger , know it's possible to alias in app, but looking at system command options for mod control through chat , not seeing !command alias !yourCommand !yourAlias or similar listed

**Comment by S1D3WYZ** [comment]
not quite what my query was aiming at : **aliasing custom command via chat**

in app you can alias custom commands. is this possible via chat?

i was looking at system commands that lists the subcommands usable in chat re: custom commands - you can edit their response, cooldown, permissions etc. 

similar to `!command response !burger new response here` and `!command cooldown !burger 5 5' etc i was hoping to find `!command alias !burger !hamburger`

not asking to alias system subcommands .. looking for system "command" subcommand "alias" (or similar) that .. adds an alias to a custom command

**Comment by SReject** [comment]
Resolved with release v5.53.0
