### ISSUE TITLE
[Feature Request] Run Command with subcommands 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1752]
**Describe the solution you'd like**

Please add sub commands to run command, 

**Additional context**
CC: DIscord: JuanmaMQD 
Hi, I created a new command with a subcommand in it and I added a Quick Action in the dashboard to run the subcommand using the effect Run Command but it seems is only running the main command, can you please let me know what I'm doing wrong? thank you!

**Comment by SReject** [comment]
Resolved with release v5.53.0
