### ISSUE TITLE
[Bug] Effect Update Currency "Message to send"

### ISSUE THREAD

**Issue by Badhabits** [crowbartools/Firebot#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the Effect Update currency under "Message to send" there is no blue box for $var . While minor since you can copy paste or just memorize $var it does help out to have this amazing feature. It is not urgent and could be classified as a feature request.

### Expected Behavior

I believe the amazing blue $var should be there to choose variables from in the "Message to send"

### Steps To Reproduce

Go to effects
add update currency
go to the effect update currency you just made
scroll down to Message to Send and see that there is missing and blue box in the right hand corner that says $var.

### Version

5.52.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Badhabitz#8988

**Comment by SReject** [comment]
Resolved with release v5.53.0
