### ISSUE TITLE
[Bug] Subcommand Fallback no longer works if you copy the command 

### ISSUE THREAD

**Issue by Badhabits** [crowbartools/Firebot#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you copy a command that has subcommands and specifically a "Fallback" subcommand, that copy's "Fallback" command does not work. It has to be deleted and remade for it to work once again.

### Expected Behavior

When you copy a command that has subcommands and specifically a "Fallback" subcommand, that copy's "Fallback" command should still work as the original command you copied did.

### Steps To Reproduce

1. Create a Command called !test
2. Create a Subcommand using custom, name it 1
3. Create a Subcommand using Fallback
4. Create a chat effect with the response "hi" in the Fallback subcommand
5. Copy !test command
6. New command !testcopy is made
7. Type !testcopy hello
8. No response is given back until you delete the !testcopy Fallback subcommand and remake it.

### Version

5.52.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Badhabitz#8988

**Comment by SReject** [comment]
Resolved with release v5.53.0
