### ISSUE TITLE
[Feature Request] Emulate Control effect 'Enter Key'

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1780]
**Describe the solution you'd like**
Can we please add the ability to send return newline in the Emulate Control effect

to clarify when the modal is open and the field is selected  using the number keyboard enter key  or the main keyboard enter key  nothing is registering but typing the word enter is working. 

**Additional context**

**Comment by zunderscore** [comment]
This already exists, you just have to start typing the word **enter** into the **Key To Press** field and select it from the dropdown.

Closing this ticket.
