### ISSUE TITLE
[Feature Request] adding a delete button and expanding the view in the viewers tab

### ISSUE THREAD

**Issue by TOWUK** [crowbartools/Firebot#1781]
1 ) Hello, in the viewers menu, where all the viewers' data are indicated (the start date of viewing, the time of viewing streams, the number of coins) I would like to see the "delete viewer/viewers" buttons and the multi-viewer selection mode appear!
2) The list of viewers displays very few viewers, please make more space!!!

**Дополнительный контекст**
It could look like this:
![image](https://user-images.githubusercontent.com/28830162/170858861-4dd4c0b0-1b94-497f-933b-f0d8077169ff.png)

**Comment by brumoen** [comment]
2) This can already be achieved by going into Settings -> Database:
![image](https://user-images.githubusercontent.com/4147439/170858957-4e170109-63b5-4617-88f3-d02ff17fda08.png)
