### ISSUE TITLE
[Bug] Play Video Effect Not Respecting "Enforce 16:9" Setting

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#1788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding a Play Video effect, the "Enforce 16:9" is always set, and is not respected. Custom Pixel height/width values are only used to size according to 16:9 aspect ratio.

### Expected Behavior

This checkbox should be respected - if disabled, custom-pixel settings should be used.

### Steps To Reproduce

1. Add a Play Video effect
2. Set a pixel set of 500x500
4. Uncheck "Enforce 16:9"
5. The video will not be resized to be a square, it will only be shown in 16:9

### Version

5.52.0

### What operating system are you using Firebot on?

Windows 11

**Comment by SReject** [comment]
To be clear, you are requesting video's be stretched, correct?

**Comment by Firebottle** [comment]
Closing as stale, feel free to recreate if this is still an issue.
