### ISSUE TITLE
[Bug] event model effects menu slides under save button

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/8982158/175819805-108a5092-f3d0-439e-a98e-67469ff22598.png)
event model effects menu slides under the save button when in focus when  not in focus it sits atop the save button. 

### Expected Behavior

event model effects menu should always be above the save button.

### Version

5.52.0

### What operating system are you using Firebot on?

Windows 10

**Comment by arblane** [comment]
On a similar topic, this also occurs with the 'Save All' feature. The label is off the screen.

![Screenshot 2024-03-06 104242](https://github.com/crowbartools/Firebot/assets/121884837/5a16fa87-fee0-4e60-b63e-67589c3f336d)

**Comment by zunderscore** [comment]
Released in v5.62.0
