### ISSUE TITLE
[Bug] !giveaway reset/draw commands takes a very long time

### ISSUE THREAD

**Issue by Ironova** [crowbartools/Firebot#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After starting a giveaway, using the command `!giveaway draw` or `!giveaway reset`, it takes a long time (at least 1 minute, sometimes more) to actually register the command and do reply accordingly.

### Expected Behavior

Get a response almost instantly after doing these commands, like the `!giveaway start ...` command.

### Steps To Reproduce

1. Start a giveaway
2. Use either `!giveaway draw` or `!giveaway reset` in chat 
3. Wait a long time for the response.

### Version

v5.52.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Ironova#9018

**Comment by zunderscore** [comment]
The `!giveaway` command is not a built in command, but rather provided by an external setup created by a community member. You'll need to get support from the person who created your giveaway command/setup or from someone who can help you investigate further. I highly suggest asking in the scripts and setups section of the Firebot Discord. As this is not native Firebot functionality, closing this issue.
