### ISSUE TITLE
[Feature Request] Allow Simulate Event to force event to retrigger if previous event is still cached

### ISSUE THREAD

**Issue by sheuronazxe** [crowbartools/Firebot#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I set up play sound effect when someone follow. Using Simulate Event > Follow (twitch) button only play sound once, next time if I use same username simulate event does nothing.

### Version

5.53

### What operating system are you using Firebot on?

Windows 11

**Comment by CKY-** [comment]
This is working as intended there is a feature request to have it changed 
https://github.com/crowbartools/Firebot/issues/1782

**Comment by zunderscore** [comment]
Closing as duplicate of #1782
