### ISSUE TITLE
Don’t trigger auto updater if OS isn’t windows or running in dev environment

### ISSUE THREAD

**Issue by ebiggz** [crowbartools/Firebot#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently Firebot will always trigger auto updater if it detects there is a released version greater than current regardless of OS but we currently only support autoupdates for the windows build.

This causes confusion for Linux users and can be an annoyance in the dev environment 

### Expected Behavior

Don’t trigger auto update unless OS is windows and not dev environment 

### Version

Latest

### What operating system are you using Firebot on?

Linux Distro

**Comment by zunderscore** [comment]
Related to #1824
