### ISSUE TITLE
[Bug] Shoutout video won't stop

### ISSUE THREAD

**Issue by JR-Cash1** [crowbartools/Firebot#1827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used to have shoutout videos enabled, but I decided to disable it as they played too loud and I could not control the volume.  However, although they no longer show on my stream, a few seconds of a video's audio still plays in the background for some reason and I cannot get it to stop.

### Expected Behavior

No video audio should play when I have disabled it.

### Version

5.53.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

 ﻿ JR Cash#9548

**Comment by zunderscore** [comment]
@JR-Cash1 Can you please attach relevant logs from when this occurred, along with screenshots of your shoutout video configuration/effects setup?

**Comment by zunderscore** [comment]
@JR-Cash1 Just wondering if you're still having problems with this. If not, I'll close this issue.
