### ISSUE TITLE
[Bug] Chat as Bot is sending message as streamer

### ISSUE THREAD

**Issue by Pigmess** [crowbartools/Firebot#1831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Command effects that I have configured to Chat as Bot - and which have functioned without issue in this manner previously - are now chatting as my streamer account. Both accounts still appear to be logged in when viewing the Firebot UI; checking the command settings I can see they have not been altered from Chat as Bot.

### Expected Behavior

The effect should chat as bot.

### Version

5.53.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Pigmess#7403

**Comment by CKY-** [comment]
Try this 
- Press Windows Key + R
- Paste in %appdata%\Firebot\v5\profiles\, hit Enter then open your profile folder
- Delete auth-twitch.json
- Restart Firebot and login

**Comment by zunderscore** [comment]
@Pigmess, were you able to try CKY's steps above to attempt to resolve?

**Comment by Pigmess** [comment]
Ah - sorry. Here’s an update.

1. The issue appears to have resolved itself. Not sure if this happened as
a result of an update, or what. I do know that program relaunch and system
restart had no effect prior to this.

2. For any interested or experiencing the same, note that I later
discovered (while the issue was still occurring) that chatting as bot in
the dashboard chat was also affected.

**Comment by zunderscore** [comment]
Glad to hear it's working! Going ahead and closing this for now. If the issue happens again, feel free to jump into the Discord for assistance or re-open this issue.
