### ISSUE TITLE
[Bug] using $rewardMessage with Timeout effect dont work and freeze the list

### ISSUE THREAD

**Issue by sheuronazxe** [crowbartools/Firebot#1845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding Timeout effect to channel reward and using the $rewardMessage variable as username does nothing and any effect after that is not running.

### Expected Behavior

Viewer buy a channel reward, enter another viewer name as text. $rewardMessage is used to timeout user 10 minutes.

### Steps To Reproduce

I created a channel reward where you require viewer to enter text. The purpose is to allow viewers timeout other viewers.
+ Added Timeout effect, Target $rewardMessage, Time 600 seconds
+ Added Chat effect. Message to send "The user $rewardMessage is 10 minutes out"

The timeout command is not working and any effect added after timeout command like chat message is not working.

If I replace the variable $rewardMessage with any username the channel rewards works properly, does the timeout and write to chat.
Also tested Timeout effect as a command using variable $presetListArg[name] and works properly.

### Version

5.53.2

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
@sheuronazxe Can you please add relevant log messages in order to help us debug?

**Comment by sheuronazxe** [comment]
[2022-08-03.log](https://github.com/crowbartools/Firebot/files/9255695/2022-08-03.log)

**Comment by zunderscore** [comment]
Verifying if this is still an issue. If not, I will close this ticket.
