### ISSUE TITLE
[Feature Request] Channel Reward Add a way to save old rewards

### ISSUE THREAD

**Issue by Badhabits** [crowbartools/Firebot#1875]
**Describe the solution you'd like**
I currently have different channel rewards for different games. Even when I disable rewards it goes towards the 50 "Reward Limit" so I have to delete old rewards even though I'm just temporarily not using them. Not sure how the system works but "disabling" a reward should make it stop counting towards the limit. If this can't happen then add a "Backup" toggle that we can toggle it to stop counting towards rewards but enable/re-enable them with an "Effect" we create if we swap games mid stream. Anything that would accomplish this goal would be nice.

Thank you for your time!

**Comment by zunderscore** [comment]
This isn't an artificial limit imposed by Firebot. This is a limit imposed by Twitch, no matter how you created the redemptions. Per Twitch docs, the service hard caps the number of channel point rewards at 50, whether they are enabled or not. 

Doc reference: https://help.twitch.tv/s/article/channel-points-faq

I would suggest that you leave feedback on Twitch's UserVoice site or upvote existing suggestions related to this. I've included a link to a suggestion already reported regarding this:

https://twitch.uservoice.com/forums/932221-channel-points/suggestions/43669374-more-rewards-and-rewards-library


As there is nothing we can do about Twitch's service limits, I'm closing this issue. If their policy changes in the future, we can explore this further.

**Comment by Badhabits** [comment]
I think my request was misunderstood, I apologize that I wasn't able to convey it properly. My request was not pertaining to increasing the twitch imposed limit.  It was for a way to make a backup or a way to save old rewards because there is a 50 limit with twitch. So you would have 50 enabled rewards which would be the Limit ,but also have Firebot have a separate place to store disabled rewards that don't go towards the twitch limit.  So what I was meaning maybe a "backup toggle" is

50 Active Enabled rewards

249 Inactive Disabled rewards (Backups)

Reward Limit 50/50

Right now if you hit the 50 limit enabled or disabled it counts towards it. Yes there is a 50 limit that you have no control over, but firebot should be able to delete it from twitch but still have it saved in an inactive state in firebot somewhere that doesn't count towards the 50 limit. Then when you re-enable it, it just remakes it on twitch and now counts towards the 50 limit. I thought this is what "disable" and "enable" did since there is a "pause" and "unpause" ,but it doesn't so I was thinking of a second "back up" toggle that could do it. 

Hopefully I made myself clearer, if not feel free to hit me up on discord. However, if you think my idea is not worth it, I understand and 0 hard feelings. I'm just trying to make it so you can swap out rewards quickly based on a game and save ones that would take a great deal to remake again. Thank you for your time and all the hard work that you do it is very much appreciated :D again I'm sorry I wasn't able to convey it properly the 1st time.  Much respect -Badhabitz
@zunderscore @SReject

**Comment by fffaria** [comment]
Is there anything on prod from what has been said here? I like the idea of having this reward management in Firebot. 
Sure, Twitch has 50 reward limits, but that doesn't mean we couldn't manage the offline ones ourselves in Firebot. This would be an awesome addition for those who use a lot of rewards like me, especially if you use Tags to set which reward should be online or offline.
