### ISSUE TITLE
[Feature Request] API Enhancements

### ISSUE THREAD

**Issue by whatupcraig** [crowbartools/Firebot#1876]
Get the value of a counter via api
Manage timers ie get the status of a timer, timer id. similar to the currency route
Manage roles ie get users assigned to a role, remove and add users to roles. similar to the currency route
Option for an api key to be used

**Comment by zunderscore** [comment]
Added most of this in #1877. API keys/auth will most likely be v6 work.

**Comment by zunderscore** [comment]
Since the rest of this is done, tracking API auth separately in #1905.
