### ISSUE TITLE
[Feature Request] More Fonts in "Show Text" effect

### ISSUE THREAD

**Issue by Patchshifter** [crowbartools/Firebot#1894]
**Describe the solution you'd like**
I'd like to see more fonts than just the 11 that are currently there, or be able to enter my own font name in the editor.
Currently, I can edit the fonts manually if i go into the events or effects json file and change the font there.

**Comment by ebiggz** [comment]
Hi @Patchshifter, you can install more fonts via Settings > Overlay > Font Management. 👍🏻
