### ISSUE TITLE
Viewer Role Variable Request

### ISSUE THREAD

**Issue by GinjaFlame** [crowbartools/Firebot#1896]
**Describe the solution you'd like**
I have been getting much help with a command/event/viewer roles idea. 

1. I have created Many Roles.
2. Created an event with View Time Updated (This allows the roles to be automatically assigned to anyone who has a certain number of Skill Points (my currency name).
3. I had to manually write in specialist, Master Sergeant etc. instead of using a variable.
4. I also created a command named !sprank which would allow a user to pull their current rank aka Viewer Role (currently does not work)

The problem is FireBot does not have this capability to do so. With the help of CKY, I have been able to at least have the Viewer Roles to either Promote/Demote a viewer based on the amount of Currency they have. 

If firebot could add a variable that would allow for a Current Viewer Role that would be awsome. 

Thanks for the great bot as I just came here from MIU and I am loving it! 

Thank you for your effort and time in this matter. Would love some help to make it better as well if you would like too. (edited)

**Additional context**
https://cdn.discordapp.com/attachments/842172237553336361/1016494122607063132/unknown.png
https://media.discordapp.net/attachments/842172237553336361/1016494122326053006/unknown.png?width=806&height=299

**Comment by CKY-** [comment]
Additional context:

Describe the solution you'd like

It would be very useful to have $usersRole[$userName]
return object/array/list of roles custom and default for a given user;
Example could be
{
platForm[
mod,
vip
],
custom[
userRole1,
Group2
]
}

or

$usersRole[$userName, twitch]
[mod, vip]

$usersRole[$userName, custom]
[userRole1, Group2]

I could be missing a use case here but the idea is to have the userName passed and retrieve all associated roles returned
Additional context
Add any other context or screenshots about the feature request here.

**Comment by GinjaFlame** [comment]
Yes this is correct, I would like to be able to call Twitch Roles, Custom Roles using variables within Firebot. This will allow the user of a role to call it up to determine which roles they are are assigned.

**Comment by zunderscore** [comment]
I have a feeling this is gonna end up being extremely related to #1898

**Comment by zunderscore** [comment]
Added in v5.55.0
