### ISSUE TITLE
[Feature Request] Real Username Variable

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#1911]
**Describe the solution you'd like**
Real username variable for twitch user based events.

**Additional context**
Currently, the $user and $username variables return the Display Name, which can cause various issues with API, and builtin effects.

**Comment by SReject** [comment]
Added `$useridname` to return the user's underlaying username for instances where the Display name is ineffectual.

Currently its limited to chat-based events. If you notice events that should be supported but aren't, list them with this feature request

**Comment by dennisrijsdijk** [comment]
I believe this should be available for gift-related events as `$giftgifteridname` and `giftreceiveridname` (not community gift)
From what I've seen in the commit, this isn't available for regular sub, cheer, follow or raid events either. (omitting Host as it's being depricated soon)
I don't believe channel point redemptions are currently supported, I'll be able to check that once the nightly build happens.

**Comment by SReject** [comment]
Going through your list:
Announcements - implemented - `$useridname` refers to the person that created the announcement

Cheer/Bits - blocked - twurple does not provide the underlying username for cheer events

Cheer/Bits badge - blocked - twurple does not provide the underlying username for cheer badge events

Sub  Recipient (not community gift) - implemented - `$useridname` will refer to the recipient of the sub

Sub Gifter (not community gift) - not implemented - will be implemented as `$gifteridname`

Follow - implemented - `$useridname` will refer to the user in question

Raid - blocked - not implemented in firebot

**Comment by dennisrijsdijk** [comment]
Cheer/Bits provides the userId, which via API can lead to the real username.

**Comment by zunderscore** [comment]
Added in v5.55.0
