### ISSUE TITLE
[Feature Request] bHaptics Integration

### ISSUE THREAD

**Issue by V1perN3st** [crowbartools/Firebot#1926]
**Describe the solution you'd like**
It would be nice to have bHaptics integrated into Firebot so Twitch follows can redeem triggers on the vest, face mask, arms, etc. For those that do not know, bHaptics is a system that you were (normally during VR, but it can also be used with music or non-VR games if integration exist) and is meant to mimic feeling what is happening in VR. They have a vest, face mask, arm bands, and a couple other items and new ones coming out. They do have a JS/TS SDK that could be used to communicate with the software.

The SDK list can be found here:
https://www.bhaptics.com/support/developers

And this is the JS/TS SKD:
https://github.com/bhaptics/tact-js

**Additional context**
This can be done as a script as well. They use tact files that are mainly JSON files that tells the software what to do. These files need to be "registered" into the bHaptics JS/TS first before they can be called (I believe this is so the script can pass the JSON to the bHaptics program). There are also modes to allow for custom paths (not sure if this will work very well in Firebot, but the file version should be good).

**Comment by Firebottle** [comment]
This seems like a very specific use case that would be better as a plugin. This isn't completely off the table, but it's more likely to end up in v6 as a plugin and not part of core firebot.
