### ISSUE TITLE
[Bug] Toggle OBS Source Visibility don't show sources in groups

### ISSUE THREAD

**Issue by ebiggz** [crowbartools/Firebot#1927]
(Migrated issue from OBS script repo) 

I have a group with 2 sources, option toggle OBS source visibility only show de group and not the sub-sources.
Is it possible show too this sub-sources?

https://github.com/ebiggz/firebot-script-obs-control/issues/15

**Comment by SwooshyCueb** [comment]
Regarding your comment on the issue from your repo:
> There were limitations to websocket v4 that caused this.

`obs-cli`, which also uses websocket v4, is able to toggle visibility of sources inside groups if you know the name of the sources. It just can't *list* them.
For this exact reason, I have firebot run `obs-cli` as a workaround for this issue.

**Comment by zunderscore** [comment]
Right, it's the listing limitation that causes the issue. We rely on the integration to give us the names of the sources so that we can provide them in the UI. We'll investigate and see if the updated OBS plugin is able return sources inside groups.

**Comment by zunderscore** [comment]
Fixed in v5.55.0
