### ISSUE TITLE
[Feature Request] Elegantly throw error when using extra characters in names such as $ and [, ]

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1942]
**Describe the solution you'd like**
This applies to custom variables but could be extended to other names 

Name of custom variables if the data is not a valid variable it should warn the user. 

**Additional context**

**Comment by SReject** [comment]
if the user wishes to use `$` `[` or `]` as a variable name, they can escape those characters:

```
$customVariable[\$name]
```
