### ISSUE TITLE
[Bug] Command cooldowns resetting whenever command cache is refreshed

### ISSUE THREAD

**Issue by PonchoTaco** [crowbartools/Firebot#1947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am experiencing an issue where I have a command that has a user cooldown set for 28800s (8 hours) - basically I only want people to use it once per stream.

If I remain on the "Dashboard" tab, it works. The moment I go to the "Commands" tab and back to "Dashboard" tab, the cooldown resets and my chatters are able to use the command again.

### Expected Behavior

Cooldown should not reset when going between tabs in Firebot

### Steps To Reproduce

!command
Go to "Commands" tab
Go back to "Dashboard" tab
!command

### Version

5.54.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

PonchoTaco#0001

**Comment by PonchoTaco** [comment]
Actually, I'm able to replicate this doing multiple things - editing a different command, viewing other commands, different tabs, clicking all of these resets all my cooldowns

**Comment by CKY-** [comment]
can confirm this

**Comment by PonchoTaco** [comment]
Unfortunately, I need to move any commands (with cooldowns) I have over to a different bot as cooldowns are not useable on Firebot in the current state.

**Comment by zunderscore** [comment]
This also occurs after the Toggle Command effect

**Comment by MattyCanny** [comment]
This is actually quite frustrating, and it has taken me a long time to work out this is why my cooldowns are not working. 

As it has not been fixed though, I expect it is not as easy to fix as we would like.

**Comment by zunderscore** [comment]
Yes, because of the way we currently load/cache commands, this would be a fairly complicated fix. We'll continue to investigate this, but it may not be until v6 when we can implement a solution.
