### ISSUE TITLE
[Bug] sequential queues do not work with video file

### ISSUE THREAD

**Issue by franky349** [crowbartools/Firebot#1958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sequential queues does not work.  all effects overlap each other 

### Expected Behavior

the bot wait the end of the effect to start the next one

### Steps To Reproduce

channel reward redemption starts a video
command starts another video over the first one

### Version

5.54.2

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
Fixed in v5.55.0
