### ISSUE TITLE
/shoutout trigger

### ISSUE THREAD

**Issue by CurtisE7** [crowbartools/Firebot#1960]
Need to create an event that triggers on another channel shouting out mine. The twitch event shows in the activity feed but gets pushed down immediately by users following from the shoutout. Uses to create an audible alert for these situations to distinguish between these shoutouts and typical hate raids.

**Comment by CurtisE7** [comment]
Oh is this not an area to suggest this type of mechanism to be implemented into Firebot. I did follow the link in the app to feature suggestions. Firebot does have the ability to listen for follow and sub activity in a channel already. If the developers are not in this forum I can search them out elsewhere.

**Comment by zunderscore** [comment]
No, what I mean is that Twitch doesn't tell other tools when shoutouts occur. Not everything that's in the Twitch activity feed is available to non-Twitch apps, like Firebot. So we can't add this feature to Firebot until Twitch does work on their end to send this notification out.

**Comment by CurtisE7** [comment]
I see, so twitch doesn't send out any triggers to create a listener off of the same way follows and subs do. Okay I'll look into bringing this issue to the twitch development team. Thank you

**Comment by zunderscore** [comment]
This might be a great place to start: https://twitch.uservoice.com/forums/310201-chat/suggestions/45624622--feature-shoutout-chat-command

**Comment by zunderscore** [comment]
Just an update: Twitch has added the ability to create shootouts via their API in beta. Once this is generally available and the Twurple library has been updated to support it, we will add it.

**Comment by CKY-** [comment]
added in 5.57

**Comment by zunderscore** [comment]
Reopening this as this is for a shoutout event coming from another channel, not the use of the command itself.
