### ISSUE TITLE
[Bug] arrayFindIndex variable returns null 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1965]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

$arrayFindIndex["[\"a\",\"b\",\"c\"]", b] 
Returns 1 , the index of "b"

the example usage returns null.

### Expected Behavior

**$arrayFindIndex["[\"a\",\"b\",\"c\"]", b] 
Returns 1 , the index of "b"**

### Steps To Reproduce

add a chat event 
to it add ``the number of b is $arrayFindIndex["["a","b","c"]", b]``
``the number of b is `` will appear in chat,  

### Version

v5.54.2

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Fixed in v5.55.0
