### ISSUE TITLE
Timer[Bug] 

### ISSUE THREAD

**Issue by madmamas** [crowbartools/Firebot#1970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

New update took away my timers and I cannot create more

### Expected Behavior

It just gives me an error when I try making new timers. My already created timers are gone now too.

### Version

v5.54.2

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment]
Please join the discord server so we can diagnose this [Discord server](https://discord.gg/DegW792) reference bug #1970 in the issues form of the discord server.

**Comment by CKY-** [comment]
> It just gives me an error when I try making new timers. My already created timers are gone now too.

what is the error?
