### ISSUE TITLE
[Feature Request] Disconnect event

### ISSUE THREAD

**Issue by Deminosa** [crowbartools/Firebot#1979]
**Describe the solution you'd like**
Event for disconnect for Twitch.tv or other applications. eg.
- Disconnect Twitch
- Disconnect overlay
- Disconnect Streamlabs

etc.
Or if the connection is lost.

**Additional context**
It sometimes happens that the connection is lost during the stream. You can set that you hear a tone, but sometimes I don't hear it. It would therefore be practical to have individual events for this so that you can also work with the disconnect.

**Comment by Firebottle** [comment]
This can be done using effects that are already in place.
