### ISSUE TITLE
[Bug] Clicking the Twitch link in the ViewerModal for viewers with Non-English characters opens wrong page

### ISSUE THREAD

**Issue by brumoen** [crowbartools/Firebot#1988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking the Twitch link for a user with non-English characters Firebot opens the wrong Twitch page, uses DisplayName instead of username.
Example:
めり込まざる者 - https://www.twitch.tv/めり込まざる者

### Expected Behavior

When clicking the Twitch link for a user with non-English characters Firebot opens their Twitch page based on username
Example:
めり込まざる者 - https://www.twitch.tv/hns32

### Version

v5-source

### What operating system are you using Firebot on?

Linux Distro

### Contact Details (Optional)

Perry#8213

**Comment by zunderscore** [comment]
Fixed in v5.55.0
