### ISSUE TITLE
[Bug] Chat Message (Twitch) Event CoolDown is cooling down all  Chat Message (Twitch) events 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#1992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that the event Cooldown for Chat Message (Twitch) event puts all events on cooldown.

### Expected Behavior

the event that was ran be cooled down 

### Steps To Reproduce

add 3 Chat Message (Twitch) with different words 
add a 10-20 second cooldown 
type all 3 words in different messages the last 2 will not trigger.. 

### Version

5,54,3

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Fixed in v5.55.0
