### ISSUE TITLE
[Bug] discord send message custom embed integration is having issues with newLine  

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using \n to add a newLine to a discord message fails until you add a variable to the string any variable even $evalVars[\n] will work to add a new line to the message 

### Expected Behavior

\n should be sent un altered to discord 

### Steps To Reproduce

discord send message custom embed 
use ``test \n test``
then use ``test $evalVars[\n] test``

### Version

v5.54.3

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Technically, this IS being sent unaltered, because we're simply sending the `\n` text string and that field doesn't accept multiline input the way it's currently built. We might be able to change the Content field to a multiline text area.

**Comment by zunderscore** [comment]
While this won't convert \n to a newline character automatically, you will be able to just enter newlines in the Content box

**Comment by zunderscore** [comment]
Fixed in v5.55.0
