### ISSUE TITLE
[Feature Request] Event Effect for Stream Marker

### ISSUE THREAD

**Issue by vyressi** [crowbartools/Firebot#2008]
**Describe the solution you'd like**
Native event effect to add a stream marker with a way to pass variables such as $raidviewercount and $user to the description field of the API call.

I know I can accomplish this by manually creating API call but this is a big ask for some of my streamers, especially the ones that like flipping accounts.  

**Additional context**
https://dev.twitch.tv/docs/api/reference#create-stream-marker

**Comment by zunderscore** [comment]
Added in v5.55.0
