### ISSUE TITLE
[Feature Request] 'support right shift capturing and simulating' 

### ISSUE THREAD

**Issue by vyressi** [crowbartools/Firebot#2009]
**Describe the solution you'd like**
See if keytap can be used to simulate right shift key independently of shift key so that right and left can have binds to different functions that do not conflict with one another.

**Additional context**
https://discord.com/channels/372817064034959370/1056679468602753165

**Comment by Firebottle** [comment]
Closing as stale, please create a new ticket if this is still needed.
