### ISSUE TITLE
[Feature Request] Viewer Database add Viewer Effect

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2010]
**Describe the solution you'd like**
Can we please have an effect that will add a viewer to the database.

This would be useful for first time viewers that raid in who are not in the database already.
Allowing for metadata to be applied and currency's updated for things such as raid events and follow events 

**Additional context**

**Comment by corhean** [comment]
I believe I saw this in action earlier while doing some testing for Tab.  Honestly, it seems reasonable that any action to the viewer database should create and execute if someone doesn't already exist unless there's an edge use case for doing null detection?

**Comment by zunderscore** [comment]
Folding this into #1541
