### ISSUE TITLE
[Feature Request] Quote Api allow for author creator and game to be queried 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2016]
**Describe the solution you'd like**
 it would be nice if in the api for the quote included ``originator creator game and created`` in the endpoint  
currently ID is all that can be queried 

**Additional context**

**Comment by dennisrijsdijk** [comment]
I was working on an update to the variable that allows you to query the object, may apply to what you're looking for

**Comment by CKY-** [comment]
added with #2104
