### ISSUE TITLE
[Bug] Discord Not sending messages if the user added and removed either override

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Nothing happens in discord if the user adds an override for the name and or the avatar then removes them, 
the settings are being stored proper but not being deleted or ignored when sending it. 

### Expected Behavior

if the user removes the override it removes it from the settings file or if the setting is blank then it is ignored when sending to discord. 

### Steps To Reproduce

go to intagrations > discord
set a bot name save it
send message to discord 
delete the bot name save it
send message to discord 
nothing happened in discord
same is true with avatar 

### Version

5.54.3

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Fixed in v5.55.0
