### ISSUE TITLE
[Bug] $previousCurrencyAmount reports the same value as $newCurrencyAmount in the context of the Currency Update event

### ISSUE THREAD

**Issue by DragynsLair** [crowbartools/Firebot#2028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a Currency Update event $previousCurrencyAmount and $newCurrencyAmount report the same value

### Expected Behavior

$previousCurrencyAmount should be the value before the currency update
$newCurrencyAmount should be the value after the currency update

### Version

5.54.3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

dragynslair#1408

**Comment by zunderscore** [comment]
Fixed in v5.55.0
