### ISSUE TITLE
[Feature Request] Linux OBS Text Sources

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2032]
OBS On Linux uses the `Text (FreeType 2)` source with inputKind `text_ft2_source_v2` rather than GDI+

**Describe the solution you'd like**
The **Set OBS Source Text** effect should be updated to include support for FreeType 2 text sources.

**Additional context**
The settings object of the FreeType 2 text source is slightly different from GDI+. I have included it below.
```json
"inputSettings": {
    "from_file": true,
    "text": "some text",
    "text_file": "/home/dennis/Firebot/license.txt"
  }
  ```

**Comment by zunderscore** [comment]
Added in v5.55.0
