### ISSUE TITLE
[Feature Request] Save the Replay Buffer

### ISSUE THREAD

**Issue by dadthegamer** [crowbartools/Firebot#2034]
I know this technically can be triggered via a hot key but a better option would be to save the replay buffer via OBS web socket

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#replaybuffersaved

**Comment by dennisrijsdijk** [comment]
For now, you can implement this using the **Send Raw OBS Websocket Request** effect

**Comment by zunderscore** [comment]
Just realized this is a duplicate of #1955 you put in back in October, so closing this :)
