### ISSUE TITLE
[Feature Request] Viewer card metadata right click to edit

### ISSUE THREAD

**Issue by ballzzpta** [crowbartools/Firebot#2035]
While messing with metadata files on player cards, can we please have the right click feature added to that? We can right click to edit almost every other section when making edits. But we can't edit here

**Comment by zunderscore** [comment]
Not sure what the request is here. When you're on a viewer card, you can edit any metadata by clicking on the edit button on the right-hand side of the particular metadata value. Please see attached screenshot.

![image](https://user-images.githubusercontent.com/1764877/213788573-603bd9f7-e519-4e76-9530-5882ae7cc864.png)

Is this what you're looking for, or are you asking about something else?

**Comment by ballzzpta** [comment]
Thanks for the reply, Completely understand you can click the edit button there, I was making the request as I have found myself trying to right click when editing the metadata. In almost every other section of the bot, we are able to right click the element and edit, copy, delete, etc. I found that is the only area we are not able to right click to edit.

More of a simplistic feature vs a needed feature is all.

**Comment by Firebottle** [comment]
I'm not sure if this would add much. The right click menu would just have "edit" and "delete", since those are the only buttons on the item there. I'm going to go ahead and close this for now, but I do think when we are building v6 we should try our best to standardize the actions like this one.
