### ISSUE TITLE
[Bug] Video no longer plays on overlay (Audio plays)

### ISSUE THREAD

**Issue by Pigmess** [crowbartools/Firebot#2037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a few different "Play Video" preset effects, that when triggered used to play a video in the overlay.

Today I noticed that though the audio plays, the visual portion of the video does not.

This also applies to built-in visual effects such as Celebration > Fireworks.

The overlay browser source is properly configured, transformed, and visible - I have double checked every option.

### Version

5.54.3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Pigmess#7403

**Comment by CKY-** [comment]
Please join the crowbar discord and create an issue under issues and we will help you troubleshoot this

**Comment by zunderscore** [comment]
Verifying if this is still an issue. If not, I will close this issue.

**Comment by Firebottle** [comment]
Going to go ahead and close this issue. Support would more easily be handled in discord but if this does turn out to be a bug then we can re-open this one. If you don't have access to discord, or don't want to join, please feel free to make a new ticket and mention that.

Thanks!
