### ISSUE TITLE
[Bug] Anonymous community gift subs are not grouped into one event

### ISSUE THREAD

**Issue by mgway** [crowbartools/Firebot#2056]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Anonymous community gift subs do not get grouped together into one event like non-anonymous community gift subs. Can be observed in this clip: https://clips.twitch.tv/LitigiousCrazyMelonPartyTime-8VdOBiDaX883XdoB

This vaguely appears to be a regression of https://github.com/crowbartools/Firebot/pull/1798. Looking through the diff of 5.54.3 to 5.55.0, it seems like the anonymous fallback name is being set to "An Anonymous Gifter" for the community gift header and "Anonymous" for the individual subs, causing the community gift sub cache keys to not match:
https://github.com/crowbartools/Firebot/blob/c730740375a13e369b8e96fdd88a494c9e796c03/src/backend/chat/chat-listeners/twitch-chat-listeners.js#L126-L134

https://github.com/crowbartools/Firebot/blob/c730740375a13e369b8e96fdd88a494c9e796c03/src/backend/events/twitch-events/gift-sub.ts#L25

### Expected Behavior

Anonymous community gift subs get grouped together

### Version

5.55.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

oh_mg#1234

**Comment by zunderscore** [comment]
Thanks for letting us know! Fixed in v5.55.1
