### ISSUE TITLE
[Bug] Quote numbers reserved after being deleted

### ISSUE THREAD

**Issue by SpookyKristyn** [crowbartools/Firebot#2062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When deleting a quote the number is still reserved by the deleted quote for some reason. When adding new quotes it doesn't fill in the missing numbers which is extremely confusing to streamers and their communities and is a challenge when trying to redeem specific quote numbers. I'm not sure if changing this is possible or maybe giving streamers access to pick their own quote number when editing quotes is a possible option? 

### Expected Behavior

Missing quote number fills in or adjust when deleting a quote.

### Steps To Reproduce

![2023-02-05 (2)](https://user-images.githubusercontent.com/124526519/216839739-1aecca34-416c-48db-b7d1-0f7856faa377.png)

### Version

5.55.2

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
This is intended functionality. If you'd like to reuse any previously used quote numbers, you would need to use the **Recalculate Quote IDs** function under Settings > Advanced > Quote ID Recalculation. Note that this will renumber any quotes that are after ones that has been deleted.

For example: if you have 5 quotes with IDs of 1, 2, 3, 4, & 5, then you delete quotes 2 & 4 and recalculate, quote 3 will become 2 and quote 5 will become 3.

As this is intended functionality, closing this issue.
