### ISSUE TITLE
[Bug] Follow Check restriction / conditional intermittently rejects actual followers

### ISSUE THREAD

**Issue by ebiggz** [crowbartools/Firebot#2065]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Follow Check restriction / conditional will intermittently rejects viewers that are followers.

Reported by Bacon_und_Schnitzel

### Expected Behavior

Consistently resolve successfully for followers

### Version

latest

### What operating system are you using Firebot on?

Windows 10

**Comment by ebiggz** [comment]
I spent some time looking into the code and don't see any glaring bugs. Going to add debugs to the logic to hopefully capture the exact point for failure.

**Comment by Samuel38** [comment]
We've been experiencing the same issue for quite some time on a channel I moderate for. 
Here's an example of the issue happening. 
![image](https://github.com/crowbartools/Firebot/assets/6044734/bb5bf8b4-cef1-42b1-95a9-16f9216190c7)

Looking at the code, I don't see anything obvious either, although I'll note that the API call `doesUserFollowChannelLegacy()` is used, which could become an issue.

**Comment by zunderscore** [comment]
This looks like it may have been fixed in 5.58.0. @Samuel38, can you confirm?

**Comment by zunderscore** [comment]
Marking this as resolved with the follower changes we made in 5.58.0. If this continues to be an issue, please reopen this issue.

**Comment by OmegaXeroxer** [comment]
I've been getting this issue on/and off for the past month as well. In my case, it only happens at the beginning of my streams.
