### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by TheLitFaery** [crowbartools/Firebot#2067]
**Describe the solution you'd like**
I love the TTS feature but would love a feature that allows me to create a reactive PNG that the chat can activate when they use the TTS.
I have been using bikubot that has this kind of feature, but I find your interface and the fact that I can add videos as an effect for my stream much easier and more appealing. It would be great to be able to replace that bot with Firebot completely so I don't have to run both at the same time.

**Additional context**

**Comment by dennisrijsdijk** [comment]
It's better to do this with the OBS Move Filter, reacting to audio levels. Firebot doesn't analyze audio. I don't have a tutorial on hand, but I'll write one out once I get to PC

**Comment by zunderscore** [comment]
As this is really outside of the scope of what Firebot does and an alternate solution has been provided, closing this ticket.
