### ISSUE TITLE
[Bug] UI not updating for Chat as and Effects list. after fresh login

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the ui won't update things like the chat as bot  and effects list until a restart, after new authentication 

### Expected Behavior

authenticating should allow for chat as to send as either the bot or streamer, and the effects list should show all effect elements.  

### Version

5.56.2

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Fixed in 5.60.0
