### ISSUE TITLE
Ban + Block a user

### ISSUE THREAD

**Issue by niuklear** [crowbartools/Firebot#2084]
Since banned users can still view your stream, I think blocking option would be a great addition! From personal experience, banning alone doesn't always save the streamers that's being constantly harrassed

**Comment by brumoen** [comment]
This isn't a function that Firebot would help with, this would have to be a feature that the platform supports.

Use their feedback system here to suggest:
https://twitch.uservoice.com/

**Comment by CKY-** [comment]
added in 5.57
