### ISSUE TITLE
[Feature Request] Ability to see hype train progression in the top bar

### ISSUE THREAD

**Issue by HumanJuke81** [crowbartools/Firebot#2087]
**Describe the solution you'd like**
Enter a clear and concise description of what you want to happen.

**Additional context**

**Comment by zunderscore** [comment]
Related to #1265. Waiting for support from Twitch.

**Comment by InzeNL** [comment]
There already is support from Twitch by using [EventSub Subscriptions](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types/)

Twurple (used for PubSub), also has [an implementation for EventSub](https://www.npmjs.com/package/@twurple/eventsub-ws) (there is also [EventSub over HTTP](https://www.npmjs.com/package/@twurple/eventsub-http), but websockets make more sense for FireBot)

**Comment by InzeNL** [comment]
I could create a separate feature request to set up the basis for EventSub subscriptions, which this feature can be built on top of?

Perhaps, after that, there's also the possibility to work on other EventSub features that aren't yet covered by PubSub.

This is, unless there is a reason not to use EventSub. In which case, let me know

**Comment by zunderscore** [comment]
We cannot use EventSub over HTTP (Webhooks) because Firebot does not expose a public, named HTTPS endpoint.

We will eventually release this as part of our implementation of EventSub over WebSockets, but we cannot currently because this is still in beta from Twitch. We don't release beta Twitch features as we don't want things to suddenly break for end users. Twitch tends to change beta features quickly and sometimes with little or no notice.

**Comment by InzeNL** [comment]
I only *just* saw that the Websocket side of EventSub is still in beta. In that case, it absolutely makes sense to wait for now.

**Comment by dennisrijsdijk** [comment]
Adding to this, polls/predictions on dashboard may also be nice, but would make it more cluttered if multiple things are happening at once

**Comment by ebiggz** [comment]
The original ask has technically been met with 5.60.0 as the progress is displayed in the dashboard activity feed. I've updated the title here to reference the top bar instead of the dashboard as thats the most appropriate place for it to go

**Comment by zunderscore** [comment]
Released in v5.61.0
