### ISSUE TITLE
[Bug] there is a collision with setObjectProperty[object, propertyPath, value]

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

setObjectProperty[object, propertyPath, value] has 2 variables named the same. 
https://github.com/crowbartools/Firebot/blob/2c4fe4bf5b3169e2a209e46c71ee9810cf267dcd/src/backend/variables/builtin/object-set-property-raw.js#L10

### Expected Behavior

setObjectProperty[object, propertyPath, value]
rawSetObjectProperty[object, propertyPath, value]
should be different 

### Version

5.57

### What operating system are you using Firebot on?

Windows 10

**Comment by SReject** [comment]
This is a typo; the two are:
`$setObjectProperty`
`$rawSetObjectProperty`
