### ISSUE TITLE
[Feature Request] Variable for quote as object

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2104]
**Describe the solution you'd like**
Add in a variable (or extend the current quote variable) to return a quote object. 

**Additional context**
N/A

**Comment by CKY-** [comment]
this is great I just used it 
```#$quoteAsObject[null, id], $quoteAsObject[null, creator]: $quoteAsObject[null, originator] $quoteAsObject[null, text] [$quoteAsObject[null, game]]```
will get random for each property 
there is no way to get a Count of Quotes to do a random from and to 

but supplying the # will get the correct info for all prosperities


I think this would be easier to have a count for random?

**Comment by dennisrijsdijk** [comment]
Count of quotes would be unreliable as users can delete quotes in the middle, and quote ID recalculation isn't forced
