### ISSUE TITLE
[Feature Request] Ad Event Triggers (Start Soon, Ads Running, Ads End)

### ISSUE THREAD

**Issue by kitlivingstone** [crowbartools/Firebot#2111]
**Describe the solution you'd like**
Ads help pay the bills and all, however they are annoying and being able to see when ads are running is rather helpful for the streamer to know quickly.  Adding an event trigger that can trigger chat, a cup of coffee gif overlay, or even a link to a sub page would be helpful.  It also just sucks answering someone's question only to have them tell you that ads ran during the answer and now you have to repeat it.

**Event Triggers suggested:**
- Ads start soon (configurable time)
- Ads running
- Ads end

**Additional context**
Streamer bot has some of this functionality already, and it's been addressed through some rather creative methods as well (https://www.youtube.com/watch?v=e5B7ZNGtkac), but having this feature built into Firebot would be nice.

**Comment by zunderscore** [comment]
Twitch currently provides no way for third-party apps to hook into their Ad Manager information or settings, and we would need API support from them to properly implement this. There are ways to have Firebot manage your ad breaks today (via Timers or Scheduled Effect Lists and the **Ad Break** effect), but that doesn't interface at all with Twitch's Ad Manager feature.

I would highly suggest upvoting suggestions related to this on Twitch's UserVoice site (see examples [here](https://twitch.uservoice.com/forums/310213-developers/suggestions/45849550-create-api-endpoints-for-ads-and-the-ads-manager) and [here](https://twitch.uservoice.com/forums/310213-developers/suggestions/44843572-eventsub-subscription-type-advertisement-started)).

In the meantime, I'll mark this as blocked until we get official API support from Twitch.

**Comment by Samuel38** [comment]
There is no a [Get Ad schedule endpoint](https://dev.twitch.tv/docs/api/reference/#get-ad-schedule) being beta tested in the Twitch API. 
This could allow to reopen this issue and address it.

**Comment by zunderscore** [comment]
Released in v5.62.0
