### ISSUE TITLE
[Feature Request] Skip remaining duration on Play Video/Play Sound effects when Clear Effects used on overlay/overlay is refreshed

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Video Player Effect is unaware of Refreshing of the overlay OR Clear Overlay Effect and will wait for the duration of play 

Edit: 09/18/2203 
 there's no callback from overlay on clear

### Expected Behavior

overlay gets cleard/refreshed execution continues 

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Released in v5.62.0
