### ISSUE TITLE
[Bug] $rawArrayLength unexpectedly returns 0 on a raw array

### ISSUE THREAD

**Issue by TheBlackParrot** [crowbartools/Firebot#2122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to figure out some way to work around [object Object] issues with $rawTopMetadata and thought i could probably just use a Loop effect and manually fetch entries in it, but I can't, as $rawArrayLength returns 0 on a raw array (from $rawTopMetadata) that should have around 10-15 entries on a fresh install.

### Expected Behavior

$rawArrayLength[$rawTopMetadata[throws]] should be returning anything but 0

### Steps To Reproduce

1. Add a loop effect that sets random metadata variables on all users in the viewer database
2. Add a Log Message effect with $rawArrayLength[$rawTopMetadata[key]] as its output. Output of just $rawTopMetadata[key] has multiple [object Object] entries.

### Version

5.57.0

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
info: GrayenWolf_ -- 63741
debug: Looking and handling replace variables...
debug: Running firebot:set-user-metadata(0adf4290-c615-11ed-9ad5-ed3d3ee52713) effect...
debug: Looking and handling replace variables...
debug: Running firebot:log-message(6b4bdc60-c615-11ed-9ad5-ed3d3ee52713) effect...
info: Ninatela -- 93652
debug: Looking and handling replace variables...
debug: Running firebot:set-user-metadata(0adf4290-c615-11ed-9ad5-ed3d3ee52713) effect...
debug: Looking and handling replace variables...
debug: Running firebot:log-message(6b4bdc60-c615-11ed-9ad5-ed3d3ee52713) effect...
info: AtomzArtzOfficial -- 39971
debug: Looking and handling replace variables...
debug: Running firebot:log-message(54578840-c61c-11ed-a64a-359ad82febf6) effect...
info: 0
```

### Contact Details (Optional)

TheBlackParrot#5285

**Comment by CKY-** [comment]
The $rawArrayLength is working as expected 
the $rawTopMetadata requires $convertToJSON and was added after 5.57.0 
this is known and has been fixed in an upcoming release

**Comment by CKY-** [comment]
after reviewing $convertToJSON was added in 5.57.0 
usage will be $convertToJSON[$rawTopMetadata[key]] 

and then you can use this in a custom variable.

**Comment by zunderscore** [comment]
@TheBlackParrot Checking to see if @CKY-'s suggestion above resolved this issue.

**Comment by zunderscore** [comment]
Closing this as resolved. If this is still an issue, please reopen.
