### ISSUE TITLE
[Feature Request] Ability to change OBS audio monitoring settings 

### ISSUE THREAD

**Issue by MattyCanny** [crowbartools/Firebot#2125]
It would be beneficial to have an effect which allows users to change the audio monitoring setting for a selected audio channel in OBS.

The three OBS Audio Monitoring options are currently: 
- Monitoring off (Default)
- Monitor Only (Mute Output)
- Monitor and Output

**Comment by CKY-** [comment]
For now you can use Send Raw OBS WebSocket Request with 
Function Name:
```
SetInputAudioMonitorType
```
Request Payload:
```
 {
    "inputName": "FireBot Default OverLay",
    "monitorType": "OBS_MONITORING_TYPE_MONITOR_AND_OUTPUT"
  }
  ```
or replace monitorType with one of the following 
  ```
  "monitorType": "OBS_MONITORING_TYPE_MONITOR_ONLY"
  "monitorType": "OBS_MONITORING_TYPE_NONE"
  ```
  if you need firebot to know what setting is being used 

Function Name:
```
GetInputAudioMonitorType
```
Request Payload:
```
  {
    "inputName": "FireBot Default Overlay"
  }
  ```

**Comment by MattyCanny** [comment]
That's amazing, I am very much looking forward to trying this out. Thanks.

**Comment by CKY-** [comment]
> That's amazing, I am very much looking forward to trying this out. Thanks.

following up did this work for you?

**Comment by MattyCanny** [comment]
It absolutely did! I've been using it reliably every stream since you told me about it.

Ive set it up to do the refresh when I connect to twitch. 

Thanks for your help.

**Comment by CKY-** [comment]
Glad to hear ill close this as its working well for you.
