### ISSUE TITLE
[Bug] Pronoun tags aren't showing the correct pronoun tag in the Dashboard

### ISSUE THREAD

**Issue by TheBlackParrot** [crowbartools/Firebot#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have my pronouns set to He/They, but they're showing up as He/Him in the Dashboard
![20230324_025803](https://user-images.githubusercontent.com/8196960/227448081-e9985720-ab0e-403c-9237-06e46b9841a7.png)

### Version

5.57.0

### What operating system are you using Firebot on?

Linux Distro

### Contact Details (Optional)

TheBlackParrot#5285

**Comment by CKY-** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> I have my pronouns set to He/They, but they're showing up as He/Him in the Dashboard ![20230324_025803](https://user-images.githubusercontent.com/8196960/227448081-e9985720-ab0e-403c-9237-06e46b9841a7.png)
> 
> ### Expected Behavior
> _No response_
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Version
> 5.57.0
> 
> ### What operating system are you using Firebot on?
> Linux Distro
> 
> ### Relevant log output
> _No response_
> 
> ### Contact Details (Optional)
> TheBlackParrot#5285

**Comment by CKY-** [comment]
I have looked at this and the pronoun site is reporting 
"login":"theblackparrot","pronoun_id":"hehim"
did you change anything?

**Comment by TheBlackParrot** [comment]
https://pronouns.alejo.io/api/users/theblackparrot reports back with
```
[{"id":"43464015","login":"theblackparrot","pronoun_id":"hethem"}]
```
(forgot to follow up on this, sorry)

**Comment by zunderscore** [comment]
@TheBlackParrot, couple of questions:

1. Does Firebot show your correct pronouns now?
2. When you first noticed the issue, had you changed your pronouns while Firebot was open?

Reason I ask: pronouns are data that rarely (if ever) changes, so when Firebot checks for a chatter's pronouns, it caches the first good value it gets for that user and doesn't refresh it for them again until the app is closed and reopened.

**Comment by zunderscore** [comment]
Closing this as resolved for now. If this continues to be an issue, please reopen and we can investigate further.
