### ISSUE TITLE
Renaming currency doesn't update system command title

### ISSUE THREAD

**Issue by MattyCanny** [crowbartools/Firebot#2129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After renaming an existing curreny, the old title remains in the currency management system commands

Chat messages are also continuing to use the old name when getting a total

![image](https://user-images.githubusercontent.com/128515589/227732788-c3b86eeb-e770-4b36-8ce6-fbecb36dcff2.png)

![image](https://user-images.githubusercontent.com/128515589/227732842-e0a52d64-a2b4-44c1-a85b-050ba29fd6b2.png)

### Expected Behavior

It should rename it all, perhaps I am missing something

### Steps To Reproduce

1. Rename an exisiting currency
2. See whether the title of the currency management system commands title changes
3. See whether 

### Version

Firebot: 5.57.0

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

Discord MattyCanny

**Comment by zunderscore** [comment]
This was resolved and released in 5.61.0
