### ISSUE TITLE
[Bug] addOnlineUser fails for users with localized usernames

### ISSUE THREAD

**Issue by mgway** [crowbartools/Firebot#2131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Localized usernames (i.e. those containing non-ascii characters) can't be looked up using the Twitch `users` API, so `addOnlineUser` fails. Presumably the user's login should be used with this API call instead of the localized/display name. Presumably not related to #2123 as there's no extra space/%20 after the username

(apologies, I only have a screenshot of the log)

![image](https://user-images.githubusercontent.com/556514/228040678-b5e46aa8-b742-471e-9cee-ef7528a318e8.png)

### Version

v5.57.0

### What operating system are you using Firebot on?

Windows 10

**Comment by CKY-** [comment]
it is part of #1247
