### ISSUE TITLE
[Feature Request] Banlist Manager

### ISSUE THREAD

**Issue by Bronmaiky** [crowbartools/Firebot#2132]
A 'Banlist Manager' to use a .txt or URL with a list of 'users' for BAN (mainly for Bots) and we will be able to ban all known bots.

From @CommanderRoot there is a sample https://twitch-tools.rootonline.de/chatban_manager.php

**Comment by Firebottle** [comment]
So, we've added a feature where known bots are separated out in the firebot user list and can easily be banned from there. This feature could also be done with a custom script or even building a one time command using effects we've already built in that would loop through a text file and ban the usernames. 

So, I think we can probably close this one for now. I think building a whole separate interface for this is maybe outside of the scope of the bot at this point in time, but maybe in v6 we could implement something for this.
