### ISSUE TITLE
[Bug] Issues with Playing Videos on Overlay

### ISSUE THREAD

**Issue by awade124** [crowbartools/Firebot#2140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

having issues with paying videos in commands. I use obs with firebot and when i pull the clips via a twitch link, the clips down load full and only play a small part of the video. When I pull it from a video file, no matter the format of the video, the clip freezes and takes a while to finish or doesn't finish at all. This results in the video being frozen on my screen for quite some time. note the videos will play with the new preview section.

### Expected Behavior

I expect the video to play in entirety and then fade out like the code required.

### Steps To Reproduce

1. add video effect
2. choose local file for mp4 or webm files.
3. test file with enabled overlay in obs

### Version

v5.57.0

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

curly#6645

**Comment by dennisrijsdijk** [comment]
Try disabling browser source hardware acceleration in OBS, we've had success with that in the past.

**Comment by awade124** [comment]
I tired doing this and this did not work

**Comment by awade124** [comment]
The biggest issue is that even twitch clips will play the first few seconds and then nothing

**Comment by awade124** [comment]
I found the issue! It was on my side. Apparently there was a virus (herofherlittl.com) that was causing issues. once i found and removed the issue, everything as solved! Thank you so much and I'm so sorry to bother you all!
