### ISSUE TITLE
[Feature Request] Fire Category Changed event when changing category outside of Firebot

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Changing the category from twitch dont seem to raise the category changed event 

### Version

5.57

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Twitch currently does not provide a mechanism to notify when the category is changed outside of Firebot. We can revisit this when EventSub support is added, as we may be able to hook into the `channel.update` event for this. Until then, marking this as blocked.
