### ISSUE TITLE
[Bug] Old Deleted chat message sound file still playing

### ISSUE THREAD

**Issue by firebotuser5** [crowbartools/Firebot#2154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used to have a sound file that would play when someone @ 's me in my twitch chat which is still playing despite it being deleted - or no where to be found in my triggers. I cant find any command anywhere in my Firebot profile which has this event trigger running, yet it is running on command every time. I made a new profile and tested it, and this old audio file does not play. So it is absolutely linked to something in my main profile in Firebot.

Now, I can simply redo all my commands and events in a new profile to fix this issue but figured I would report it as a potential bug. Somehow old sound files and their triggers are remaining even after being deleted. Maybe it is still present somewhere from an old version of Firebot that got updated and made the old sound file trigger hidden? That is my best guess.

Also, when adding another profile it would be nice to be able to copy individual commands over to the new profile instead of having to manually redo them and all the custom data within them all. Maybe there is an option to do this already I'm just not seeing it.

### Version

v5.57.0

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Is this still an issue? If not, I'll close this issue.
