### ISSUE TITLE
[Feature Request] Allow sorting of arrays

### ISSUE THREAD

**Issue by MitsCommitch** [crowbartools/Firebot#2159]
**Describe the solution you'd like**
I'm working on an effect chain for a streamer and part of it involves keeping an array of "guessed numbers". When displaying these to chat, having them sorted would be grand. Given the other existing array operations, I fear there's a reason sort was not included, but it seemed worth requesting. I've set up a rudimentary PR with this, I'll link it in a comment to this request. Fair warning, my JS is awful, so I mostly copied and pasted from existing array commands.

**Comment by zunderscore** [comment]
The new `$evalJs` variable or **Evaluate JavaScript** effect released in 5.61.0 should allow this. Going ahead and closing this.
