### ISSUE TITLE
[Bug] Tier 2 / Tier 3 Sub Role in command filter not being allowed. 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

commands with Tier 2 / Tier 3 Sub Role filter never triggers 

### Expected Behavior

if a Tier 2 / Tier 3 Sub uses a command with the Tier 2 / Tier 3 Sub Role  then the command should trigger. 

### Version

5.57

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Released in v5.62.0
