### ISSUE TITLE
[Bug] $arrayElement returns [object Object]

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using $arrayElement to retrieve an element from a JSON array, [object Object] is returned. When converting that with $convertToJSON it turns into "[object Object]"

### Expected Behavior

using $arrayElement should return a text representation of the element, rather than [object Object]

### Steps To Reproduce

1. Open the developer tools.
2. Create a `Log Message` effect
3. add `$arrayElement["[{}]", 0]` into the effect
4. Press the Test Effect button
5. Look in the console, there should be [object Object]

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 11

**Comment by Timenauter** [comment]
i hope this works, this will complete the integration about firebot-gpt-3.5 api for me
