### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by wizaurus** [crowbartools/Firebot#2171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the button to connect to twitch does not appear so I cannot connect

### Expected Behavior

I should be able to connect to twitch

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Wiz#6945

**Comment by The-Nasuth** [comment]
I am also experiencing this error. In fact the entire left panel of the Dashboard is missing its buttons. You can click where the Connect button is, but it doesn't actually connect.
![Screenshot 2023-05-30 131843](https://github.com/crowbartools/Firebot/assets/113808929/df7b2898-2dcb-4477-a863-257f46237b5e)

**Comment by CKY-** [comment]
@wizaurus @The-Nasuth Close firebot and reopen it.

**Comment by The-Nasuth** [comment]
I did several times and it still didn't work, but eventually part way
through my stream it did start working again.

**Comment by brumoen** [comment]
For issues like this check FontAwesome's status page:

https://status.fortawesome.com/

We are using their Icon pack for our icons and if their website or service has issues sadly so will Firebot.

**Comment by zunderscore** [comment]
Closing as a duplicate of #1829
