### ISSUE TITLE
[Support] Firebot connected, No Scenes/Sources

### ISSUE THREAD

**Issue by FairyFlorra** [crowbartools/Firebot#2184]
I have been using Firebot a while however all of a sudden now, even though it is connected with OBS and the Overlay works as well as commands ect. If I try to make a event with a trigger to manipulate both my scenes and sources, it says there are non and to check if OBS is running (which it is). I tried disconnecting bot completely and re-connecting as well as checking for updates (none). Not sure what else to do from here. Thank you

**Comment by zunderscore** [comment]
Hey, Fairy! Would you mind joining our [Discord](https://discord.gg/tTmMbrG) and creating a thread in our #issues channel? That's the fastest way for one of our Firebot experts to help get you all fixed up.

**Comment by zunderscore** [comment]
@FairyFlorra Did you ever get this resolved? If so, I'll go ahead and close the issue.
