### ISSUE TITLE
[Feature Request] Pronoun variable 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2187]
can we have a variable that will return the viewers pronouns from pronoun picker, 
 if a pronoun is set by the user return it OR return empty and cache it for that sesion, 
 this can be use full for text strings to say that person did a thing 
 
$prounouns[target] =>[he/him]
$prounouns[target, 1] => he
$prounouns[target, 2] => him

because in grammar  you say "He did a thing" not "Him did a thing"

get the cached per session or ask the service to return a new.

**Comment by JOELPOG** [comment]
so basically you want a variable where the users can set their pronouns like $setPronouns[he/him, she/her, they/them] and well this is stored in the DB and when the var is called you want to return the same pronouns which will have the format as 
```
$prounouns[target] =>[he/him]
$prounouns[target, 1] => he
$prounouns[target, 2] => him
```

the `target` placeholder being the username of the user...
is that right?

**Comment by CKY-** [comment]
@JOELPOG 
> so basically you want a variable where the users can set their pronouns like $setPronouns[he/him, she/her, they/them] and well this is stored in the DB and when the var is called you want to return the same pronouns which will have the format as
> 
> ```
> $prounouns[target] =>[he/him]
> $prounouns[target, 1] => he
> $prounouns[target, 2] => him
> ```
> 
> the `target` placeholder being the username of the user... is that right?
Sorry I did not see this reply 
that is for the most part correct 

$prounouns[$target, subject] => he
$prounouns[$username, object] => him

but without the db part, firebot cashes the pronoun from a third party site that is an extension. 
to not get into Subject | Object using the array number would do the same thing. 

but when used in a command one can have an output that is 

go follow @JOELPOG $prounouns[$target, 1] is amazing. 

there are other uses of this as well 

this can be expanded into the realm of first second and third persons  

[Common personal pronouns in standard Modern English](https://mogai.miraheze.org/wiki/Pronoun)
Person | Number/Gender | Subject | Object | Dependent possessive (determiner) | Independent possessive | Reflexive
-- | -- | -- | -- | -- | -- | --
First | Singular | I | me | my |  mine | myself
 -- | Plural | we | us | our | ours | ourselves
Second | Singular | you | your | -- | yours | yourself 
 -- | Plural | --  | --  | -- | --  | yourself 
-- | -- | -- | -- | -- | -- | yourselves
-- | Masculine | he | him | his | -- | himself
-- | Feminine | she | her | -- | hers | -- | herself
Third | Plural | it | -- | its | -- | itself
-- | they | them | their | -- | theirs | -- | themself / themselves
-- | they | them | their | -- | theirs | -- | themself / themselves


how ever you run into multilingual issues where this only applies to the english language

$prounouns[$username, second, masculine, subject] => he
or 
$prounouns[$username, subject] => he

I personally think this is way overboard but most of it can be just read from the pronoun endpoint and nothing needs to be stored  outside of waht is already cached

**Comment by Firebottle** [comment]
I've created this variable and is in a PR. I'm keeping it simple and only using what is available from the pronoun site. There will definitely be gaps like "his", but unless that gets requested heavily then this is probably good enough for most.
