### ISSUE TITLE
[Bug] Automatically deduct currency in Restrictions not removing the currency

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

CC: Jarminx discord
With the Automatically deduct currency from user if restrictions pass setting checked nothing happens 

### Expected Behavior

remove the amount shown in the amount field

### Version

5.57

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Fixed in 5.61.0
