### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by MaxPK** [crowbartools/Firebot#2197]
**Describe the solution you'd like**
I would like to be able to quickly post on say a friends discord (where i cannot get a webhook) ane be able to post self-promo on their server when i go like (ie start streaming on obs) 

**Additional context**
I know there is a way to auto post in discord but you need a webook to do so. Im talking about doing it without a webhook.

**Comment by CKY-** [comment]
I would like to be able to quickly post on say a friends discord (where i cannot get a webhook) ane be able to post self-promo on their server when i go like (ie start streaming on obs)
I know there is a way to auto post in discord but you need a webook to do so. Im talking about doing it without a webhook.

This would be more for discord, a webhook is what they offer and what we can use.

**Comment by brumoen** [comment]
There is a reason for the Webhook requirement for this, and it's also against Discord's TOS to interact with Discord without using their available API's. In this case Webhooks, so this feature is not something we can or will implement.
