### ISSUE TITLE
[Bug] Custom Viewer Roles do not update when usernames are changed on Twitch

### ISSUE THREAD

**Issue by huds601** [crowbartools/Firebot#2203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use Viewer Roles to keep track of a one-time redemption for sticker giveaways. When the user redeems the channel point reward, it adds the role to them to that, if they try to redeem again, it will reject the redemption and refund the points.

I noticed that one of my viewers was able to redeem a second time, and they had recently changed their Twitch username.

Their old name was cowboyknuckles, their new name is CBK_x.

However, in the Custom Role, they are still showing as cowboyknuckles, but only appear as CBK_x in my viewers database. While one of the 2 roles I use is applied the one they redeemed before changing their name is no longer applied to their account.

![Profile](https://github.com/crowbartools/Firebot/assets/42800359/630314e8-2fc5-4a9d-b062-952f494c1fcb)
![Custom Role](https://github.com/crowbartools/Firebot/assets/42800359/b0d18fd4-e1ff-43ab-83ca-ea75575c4f3f)

### Expected Behavior

Custom roles should follow users post-name change

### Steps To Reproduce

1. Add a Twitch user to a custom role
2. Change the username of the Twitch user

### Version

5.57.0

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Discord: huds601

**Comment by CKY-** [comment]
part of #2198

**Comment by JOELPOG** [comment]
one possible fix for this could be the use of userID tracking rather than username tracking
which means that instead of assigning the roles to the usernames (which can be changed) we can assign the same to the userID (which cannot be changed even after  changing the username)

**Comment by Firebottle** [comment]
Tagging as v6 based on the info in #2198

**Comment by zunderscore** [comment]
Released in v5.62.0
