### ISSUE TITLE
[Support] 

### ISSUE THREAD

**Issue by BuddyDGreeson** [crowbartools/Firebot#2207]
**Help Request**
Enter a clear and concise explanation of the issue you are having or the thing you would like help with.
is the keybind feature bugged i cant get my effect to trigger when pressing the keybind , i can click the test and it shows my effect but the keybind want trigger it

**Comment by CKY-** [comment]
I am not quite sure what you are referring to with keybinding or how you are trying to use it.. 
but i will take a stab in the dark and assume that you are referring to 
HotKeys? 
This is listed in the left hand tabs to control firebot itself. 

Things to keep in mind with hotkeys:
Firebot cannot override hotkeys that are already reserved by other apps.
Firebot cannot detect if a hotkey is already in use by another app.
If you bind a hotkey to a single letter, you will not be able to type that letter in other applications.


In some cases an application needs to have focus or the hot key will not register. 

 if this did not help please join the [discord](https://discord.gg/tTmMbrG) and start a new issue referencing "[Support] #2207 HotKeys not working"
