### ISSUE TITLE
[Feature Request] Effect Queue improvements

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2213]
**Describe the solution you'd like**
Currently on the effect queues page, you can't see or adjust a queue's status (active or paused) or clear the queue. Pausing/resuming and clearing effect queues is currently possible through effects, so it would be nice to see feature parity in the UI.

I believe it'd also be benefitial to be able to see how many items are currently in the queue on this same page.

**Additional context**
N/A

**Comment by zunderscore** [comment]
Released in 5.58.0
