### ISSUE TITLE
[Bug] Twitch rewards not always detected

### ISSUE THREAD

**Issue by soycypher** [crowbartools/Firebot#2215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Sometimes it detects the twitch rewards and do the action as expected and sometimes it doesnt.

### Version

Firebot: 5.57.0

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
a
```

**Comment by CKY-** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Sometimes it detects the twitch rewards and do the action as expected and sometimes it doesnt.
> 
> ### Version
> Firebot: 5.57.0
> 
> ### What operating system are you using Firebot on?
> Windows 10
> 
> 
> ### Contact Details (Optional)
> _No response_

What service created the reward?

**Comment by soycypher** [comment]
It was created on Firebot so I can turn it off and on with commands

**Comment by soycypher** [comment]
I tried with event effects and didnt detect the reward properly
