### ISSUE TITLE
[Feature Request] Expand ExtraLife integration

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2229]
**Describe the solution you'd like**
Iterate on the extralife integration to include support for:
- getting goal information
- getting milestones info
- top donator

API docs: https://github.com/DonorDrive/PublicAPI

**Comment by ebiggz** [comment]
Updated title and description to include more details and link to api docs

**Comment by Firebottle** [comment]
- Top X donors (with a warning that this often shows real names)
- X number of incentives ($10 - I play with one hand!)
- Incentive by dollar amount.
- Next milestone (get current raised amount and find the next milestone)
- Fundraising goal
