### ISSUE TITLE
[Bug] Follower notifications not working

### ISSUE THREAD

**Issue by 2by4est** [crowbartools/Firebot#2230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my activity feed is not picking up on my follower notifications.

### Expected Behavior

My Follower event should set off an animation on obs. My activity feed should pickup on my follow activity.

### Steps To Reproduce

1. trigger follower on twitch account
2. look at activity feed

### Version

5.57

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

lileran#4152

**Comment by Firebottle** [comment]
Hello! Sorry about this! It is a known issue and we'll have it fixed in the next update.
