### ISSUE TITLE
[Bug] play random video from file 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the video player is ignoring the effect.videoType  "Random From Folder"
Line https://github.com/crowbartools/Firebot/blob/5cfad945242c05867f887d24861c396c83cece06/src/backend/effects/builtin/play-video.js#L462
is missing an or check || effect.videoType === "Random From Folder"
and data.videoDurration is never set so the video is ignored. 

### Expected Behavior

to play a random video from file 

### Version

5.58.0

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
Fixed in v5.58.1
