### ISSUE TITLE
Change OBS Scene [Bug] 

### ISSUE THREAD

**Issue by gabo30** [crowbartools/Firebot#2252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to add an OBS scene change through Firebot, although it shows the available OBS scenes, but when selecting and wanting to save the "add" button does not change to "save" and a "Please Select a Scene" card appears.

### Version

5.58.1

### What operating system are you using Firebot on?

Windows 11

**Comment by dennisrijsdijk** [comment]
Please try the nightly build from https://github.com/crowbartools/firebot-nightly as it should already have a fix in place

**Comment by gabo30** [comment]
@dennisrijsdijk 
How do I install that version in Windows 11?

**Comment by dennisrijsdijk** [comment]
> @dennisrijsdijk 
> How do I install that version in Windows 11?

Go to the releases page and download the .exe file

**Comment by gabo30** [comment]
Thank you very much, I leave the link for anyone interested. I'm going to try it and then I'll tell you how it went.
https://github.com/crowbartools/firebot-nightly/releases/tag/v5.58.1-nightly-23.09.30
