### ISSUE TITLE
[Bug] Fully qualified youtube video's fail to play when manipulating the overall url.

### ISSUE THREAD

**Issue by Sam-Beynon** [crowbartools/Firebot#2260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a a list of random effects that play video's, if you fully qualify the youtube URL instead of providing an ID, the system passes the wrong value to the YT embed framework.
See the setup in the [attached zip](https://github.com/crowbartools/Firebot/files/13041679/Test.zip) for a reproducible scenario.

![Example of the user displayed error](https://github.com/crowbartools/Firebot/assets/9073058/773c7159-962d-4c4d-97ca-864666b220d8)

![Example of the network request made from the overlay](https://github.com/crowbartools/Firebot/assets/9073058/24da6fa2-1a7a-4f16-bf15-6f8eaf345462)

As you can see, the URL is malformed, passing in a fully qualified youtube URL, instead of extracting the id from the provided url and constructing a valid embed url.

i.e.
`https://www.youtube.com/embed/https://www.youtube.com/watch?v=NrQIG99IZQ0?autoplay=1&controls=0&start=67&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&origin=http://localhost:7472&widgetid=2`

should actually be 
`https://www.youtube.com/embed/NrQIG99IZQ0?autoplay=1&controls=0&start=67&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&origin=http://localhost:7472&widgetid=2`

Originally reported by `Brutal Sue`

### Expected Behavior

The URL should be correctly formatted 
i.e.
`https://www.youtube.com/embed/https://www.youtube.com/watch?v=NrQIG99IZQ0?autoplay=1&controls=0&start=67&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&origin=http://localhost:7472&widgetid=2`

should actually be 
`https://www.youtube.com/embed/NrQIG99IZQ0?autoplay=1&controls=0&start=67&showinfo=0&rel=0&modestbranding=1&enablejsapi=1&origin=http://localhost:7472&widgetid=2`

### Steps To Reproduce

See attached Setup file.

### Version

5.58.1

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

CorporalGigglesworth

**Comment by zunderscore** [comment]
This appears to be fixed in 5.59.2. Can you confirm?
