### ISSUE TITLE
[Bug] Incorrect audio driver in native Ubuntu version

### ISSUE THREAD

**Issue by Deminosa** [crowbartools/Firebot#2261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, I have a problem with the audio on Ubuntu. Unfortunately, the corresponding audio outputs are not displayed to me like with other applications.

I have Pipewire installed as well as PulseAudio and JACK.
The problem existed even before I installed Pipewire and JACK.

In the appendix you can see what exactly I mean.
My system information is also stored.

![System Info](https://github.com/crowbartools/Firebot/assets/24417089/7653d1f7-fb59-41f7-9f12-5468744f4a99)
![Screenshot Audio](https://github.com/crowbartools/Firebot/assets/24417089/5ffa9b68-0af5-4e6e-b9d7-a4703e5e7584)

### Expected Behavior

![Discord Audio Output](https://github.com/crowbartools/Firebot/assets/24417089/d53380bd-8d52-4fae-92dc-3d757c1ab86a)
![Mixxer Audio Output](https://github.com/crowbartools/Firebot/assets/24417089/b078c908-141e-4cd5-b892-1b5c7d4d0b2b)

It would be nice if, for example: JACK would be available.

### Steps To Reproduce

Install Ubuntu Natively

### Version

5.58.1

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
Unfortunately there is nothing in the log that would be interesting from my point of view.
```

### Contact Details (Optional)

@deminosa

**Comment by zunderscore** [comment]
In v5.59.0, we had some major updates to Electron which may address this. Can you test again with >= v5 59 0 and let us know if you're still having this issues?

**Comment by Deminosa** [comment]
With this new Version i have no Window Options or anything see pic
[Firebot Logs 1.txt](htt
![No WIndow Pic](https://github.com/crowbartools/Firebot/assets/24417089/0b2ed2ab-c6ca-4973-b96b-5da52a66c862)
ps://github.com/crowbartools/Firebot/files/13722938/Firebot.Logs.1.txt)
[Firebot Logs 2.txt](https://github.com/crowbartools/Firebot/files/13722939/Firebot.Logs.2.txt)

**Comment by dennisrijsdijk** [comment]
Can you grab the logs from the terminal?

**Comment by dennisrijsdijk** [comment]
Looks like issues related to your graphics driver. Make sure it's up to date and properly installed. How are you starting the bot exactly?

**Comment by dennisrijsdijk** [comment]
Please join the Firebot discord, create a thread in the Issues forum and ping @dennisoti, makes it easier to discuss and look into things.

**Comment by Deminosa** [comment]
OK thread now exists: https://discord.com/channels/372817064034959370/1166592468372963410

**Comment by brumoen** [comment]
Removed the `--no-sandbox` and it runs as it is supposed to, also told not to run Firebot with Sudo privileges as that shouldn't be necessary for a user application like Firebot.
- Confirmed via Discord.
