### ISSUE TITLE
[Feature Request]  can you add a coin toss 

### ISSUE THREAD

**Issue by BossRedemption** [crowbartools/Firebot#2272]
**Describe the solution you'd like**
Enter a clear and concise description of what you want to happen.

**Additional context**

**Comment by zunderscore** [comment]
You can use a **Chat** effect with variables to create a simple coin toss command. Something like `You flipped a coin and got $if[$randomNumber[0, 1] == 0, Heads, Tails]`.

This is a little outside of something we'd include in Firebot by default, so closing this request.
