### ISSUE TITLE
[Feature Request] Horror Stories

### ISSUE THREAD

**Issue by BossRedemption** [crowbartools/Firebot#2275]
**Describe the solution you'd like**
we should have a horror story command option for example ! horror story and fire bot  tells a horror story  eather in voice or text that would be cool 

**Additional context

**Comment by zunderscore** [comment]
You can use the **Text-To-Speech** effect along with the source of your choice to create a command that achieves this. If you need help setting something like this up, please join our Discord and one of our community members will be glad to help you.

Unfortunately, this is outside of the scope of something we'd include with Firebot, so closing this request.
