### ISSUE TITLE
[Bug] Chat Replies to commands do not show up in the dashboard chat log.

### ISSUE THREAD

**Issue by SushiKishi** [crowbartools/Firebot#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Edit:** I did search the open issues on GitHub and didn't see anything relevant, then I clicked over to Discussions and found [this post](https://github.com/crowbartools/Firebot/discussions/1806) from June 2022. If I were a bettin' man, I'd bet this is basically the same issue, and due to API limitations the replies can't show up in Firebot at all.

If this is the case, can that please be added to the tooltip for the  "Send as reply?" checkbox?  Right now it just says "Replying only works within a Command or Chat Message event," maybe we can add "Note: Chat replies will not display in the Firebot Dashboard; the reply will only be visible in the [standard/default/some adjective] Twitch Chat."

If not, the original post follows:

I was looking through the Discord for help with something else, and noticed at least two threads related to an issue I've also been having for a while: the chat log on the dashboard does not show replies to your chat messages sent *from* the dashboard.

If !test is set to have the bot sent a chat message *as a reply* with "Test received!" with a 60-second cooldown on the command:

If I use the command in the Twitch popout chat, then again in Twitch Popoout before the cooldown, then AGAIN in the Dashboard:
**--Popout Chat sees:**
----"Test received!" as a reply to its own 1st command
----"Cooldown in X" as a reply to its own 2nd command
----No response to the message from the Dashboard.

**--Dashboard Chat sees:**
----"Test Received!" sent by the bot after the 1st Popout command
----"Cooldown in X" sent by the bot after the 2nd Popout command
----No response to its own message.

If I use the command twice from the Dashboard, then again from the Popout chat:
**--Popout chat sees:**
----No response to the first command from the dashboard
----No response to the second command from the dashboard
----"Cooldown in X" to its own message from popout (therefore, the command DID fire, or it wouldn't be on cooldown)
**--Dashboard Chat sees:**
----No response to the first command sent form Dashboard
----No response to the second command sent from Dashboard
----"Cooldown in X" after the command from the Popout chat.

The confusion in the Discord threads I saw were related to whether or not the command was set up correctly or executing properly. It is -- the bot is performing the correct response and going on cooldown afterward. The issue is solely with whether or not a chat message sent as a reply *to a message sent from the Firebot dashboard* is visible in the Firebot dashboard, and it is not.
![image](https://github.com/crowbartools/Firebot/assets/98235961/9e2141e3-569c-42dc-95a7-da7a0aebe8ab)
![image](https://github.com/crowbartools/Firebot/assets/98235961/cd13b8df-576b-41d2-9576-6c10222e31a6)

### Expected Behavior

Replies to a chat message sent from the dashboard are also visible in the dashboard; or, if this is not a bug, better clarity on what to expect when using the command from the dashboard (which is no response). I keep forgetting this issue happens but didn't post before now because I always assumed it was just me, or that the dashboard is just a summary and a full-fledged chat experience so it was working as intended.  But seeing a few posts in Discord asking about this exact issue makes me thing it's either not working right, or more clarity is needed.

### Steps To Reproduce

Set up a command with a "Chat Message" event, and tic the "Send as reply" box. Use the command in the dashboard, then again in a "standard" Twitch chat/popout chat (to test if the command went on cooldown).

### Version

5.58.1

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

SushiKishi

**Comment by zunderscore** [comment]
So... This is a complex problem. While we're connected to Twitch chat, an event is fired for EVERY chat message in the channel EXCEPT for messages Firebot sends from the streamer account. Because we don't receive the event, we don't know the unique ID of the message that Firebot sent to Twitch. And without that message ID, we can't reply.

I'll look into this to see if there's some kind of workaround we can implement, but I'm fairly certain that this is something that we'll have to revisit once we get chat over EventSub sometime next year.
