### ISSUE TITLE
Show HTML's animated image sources play in sync [Bug] 

### ISSUE THREAD

**Issue by Zilarrezko** [crowbartools/Firebot#2293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently when an img source is given an animation each instance of the animation is in sync with each other.

### Expected Behavior

When an animation plays I expect that instance to be played from the beginning. Normally this wouldn't be a problem, but when placing a random position for the animation depending on the intention of the animation it should be played from the beginning.

### Steps To Reproduce

`<img src="<input_file>" style="top: $randomNumber[0, 500]px; left: $randomNumber[0, 500]px;">`

### Version

5.59.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

jesse.coyle@tutanota.com

**Comment by CKY-** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Currently when an img source is given an animation each instance of the animation is in sync with each other.
> 
> ### Expected Behavior
> When an animation plays I expect that instance to be played from the beginning. Normally this wouldn't be a problem, but when placing a random position for the animation depending on the intention of the animation it should be played from the beginning.
> 
> ### Steps To Reproduce
> `<img src="<input_file>" style="top: $randomNumber[0, 500]px; left: $randomNumber[0, 500]px;">`
> 
> ### Version
> 5.59.2
> 
> ### What operating system are you using Firebot on?
> Windows 10
> 
> ### Relevant log output
> _No response_
> 
> ### Contact Details (Optional)
> [jesse.coyle@tutanota.com](mailto:jesse.coyle@tutanota.com)

this is a limitation of HTML and websites try your code at 
https://codepen.io/
or
https://jsfiddle.net/

if you would like your animation to start at different times you will need to use a sprite sheet

**Comment by Zilarrezko** [comment]
Hmm I was afraid of that. Honestly #2070 would be perfect for the use case, but not in a general sense. I think you're right, doing the animation with bitmaps manually might be the play.

**Comment by SReject** [comment]
This is a limitation of browsers and not something we can fix.
