### ISSUE TITLE
[Feature Request] Updated custom script template & Types

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2304]
**Describe the solution you'd like**

Update the typings to be in-line with 5.60 when it releases, and bring the template up to node 18 with the required webpack versions, plugins and typescript.

**Additional Context**

The script template and typings are horribly out of date, causing compile errors between node 18 and webpack 4
Additionally, typings haven't been updated since 5.53.2

**Comment by CKY-** [comment]
resolved in 5.60.1
