### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Quexp** [crowbartools/Firebot#2345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Started having disconnection issue today (1st stream since update)
- Restarted Firebot, no success
- Uninstalled and reinstalled from Github download (and restored backup).  Tried again from Firebot website.
- Issue still there so gave up

A couple of steps I tried were from a Discord thread in your server but I don't know what else to do.

### Expected Behavior

For viewer list, chat, and commands to work

### Steps To Reproduce

1. Open Firebot and verify Twitch, OBS, Streamlabs connected
2. "Disconnected from chat, trying to reconnect..." message appears

### Version

- Firebot: 5.60.1

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
no log that I know of
```

### Contact Details (Optional)

Discord: quexp

**Comment by zunderscore** [comment]
This appears to be an environmental issue rather than a bug, so I created [a thread in Discord](https://discord.com/channels/372817064034959370/1193436299856723988) for further troubleshooting. Closing this issue.
