### ISSUE TITLE
[Feature Request] A real stream deck plugin

### ISSUE THREAD

**Issue by lublak** [crowbartools/Firebot#2364]
**Describe the solution you'd like**

It is currently possible to trigger actions via a web request.
But the complete feedback is simply missing here. I can also simply use a macro button.
Stream Deck also allows the display of information.
A plugin would be necessary here. (possibly via websocket?)
So displaying variable values would be very practical here. And as a button click the execution of actions. You could also implement a toggle, for example. The variable would then contain 0 or 1, which would then also be displayed on the button. (Simply text 0/1). And when you press the button, an action is executed and the variable is changed.
It would also be practical to display a title above it.

![grafik](https://github.com/crowbartools/Firebot/assets/44057030/b778229d-3f83-4127-a4c2-793fd9a50c5c)

Aktion = Preset List Name
![grafik](https://github.com/crowbartools/Firebot/assets/44057030/a0ce2f59-768f-4110-aa25-81b22774513f)

**Comment by dennisrijsdijk** [comment]
already planned, no ETA

**Comment by lublak** [comment]
@dennisrijsdijk Nice to see :)  I haven't found anything about it. So I thought I'd add it as a feature request. And the rule always applies: it comes when it comes.

**Comment by SReject** [comment]
A streamdeck plugin is not planned as it is beyond the scope of Firebot.

However, Firebot has a robust HTTP api that anyone from the community could leverage to produce such a plugin for StreamDeck
