### ISSUE TITLE
[Bug] SetMode event has an odd issue displaying the chat message in firebot

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

firebots dashboard is not showing the chat message for when follow only has been removed, This may be a me issue however twitch chat shows it 
![image](https://github.com/crowbartools/Firebot/assets/8982158/62445b83-a176-45bf-8778-29f7aef40af8)
![image](https://github.com/crowbartools/Firebot/assets/8982158/5105e743-7f44-483d-8ef3-8811f7d0d4e9)

![image](https://github.com/crowbartools/Firebot/assets/8982158/fd0c5347-2713-424d-9297-f4ec7ecea59f)

I have a chat mode changed event that has a chat message effect with 
$chatMode 
$chatModeDuration 
$chatModeState
and nothing more.. 

cool thing is that the enabled works 

![image](https://github.com/crowbartools/Firebot/assets/8982158/af8c024d-2907-4d1b-9654-ea19cda3097e)

### Expected Behavior

the chat display to match what twitch chat shows 

### Version

5.61 dev

### What operating system are you using Firebot on?

Windows 10

### Relevant log output

```shell
nothing shows in the log as if the chat message is not sent to firebot.
```

**Comment by zunderscore** [comment]
Unable to repro this on latest 5.61 dev. Closing as completed.
