### ISSUE TITLE
[Feature Request] custom command visibility

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2400]
**Describe the solution you'd like**
Please add a visibility option to the context menu of the commands so that you dont have to edit everyone to hide it...

**Comment by dennisrijsdijk** [comment]
To add to this, it would be nice to have a toggle in settings for "new custom command visibility" as I've found myself having to update almost every command to disable it from sending.

**Comment by zunderscore** [comment]
Released in v5.62.0
