### ISSUE TITLE
[Feature Request] clean up the autoid of quotes please

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this is not causing any crashes as far as i can tell but it is filling the file

{"_id":"__autoid__","seq":18}
{"text":"twss","originator":"C_K_Y","creator":"C_K_Y","game":"Minecraft","createdAt":"2024-02-19T17:31:03.724Z","_id":18}
{"_id":"__autoid__","seq":19}
{"text":"twss2","originator":"C_K_Y","creator":"C_K_Y","game":"Minecraft","createdAt":"2024-02-19T17:33:02.671Z","_id":19}
{"_id":"__autoid__","seq":20}
{"text":"twss3","originator":"C_K_Y","creator":"C_K_Y","game":"Minecraft","createdAt":"2024-02-19T17:33:06.931Z","_id":20}
{"_id":"__autoid__","seq":21}
{"text":"twss4","originator":"C_K_Y","creator":"C_K_Y","game":"Minecraft","createdAt":"2024-02-19T17:33:12.469Z","_id":21}

### Expected Behavior

not to keep the autoid  on each entry 

### Steps To Reproduce

add a quote look in the quote file

### Version

5.61.2

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
This isn't causing an issue with the quote database and is creating a negligible amount of extra data in the file. Doing cleanup would be effort for essentially no gain. Therefore, closing this issue.
