### ISSUE TITLE
[Bug] textPadStart and textPadEnd vars are miscategorized as $replace

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

textPadStart and textPadEnd both have their base usages set to replace, rather than textPadStart/End, making it more difficult to find the variables.

### Expected Behavior

These variables should show up as textPadStart/End instead of $replace

### Steps To Reproduce

1. Open any blue $vars button
2. Look for textPad
3. See $replace instead

### Version

5.61.2

### What operating system are you using Firebot on?

Linux Distro

**Comment by zunderscore** [comment]
Released in v5.62.0
