### ISSUE TITLE
[Bug] Renaming a quick action causes a visual error and no data update

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Renaming a quick action shows an on-screen error and doesn't update the name in the UI, but does in the backend. Restarting the bot updates the data.

### Expected Behavior

Renaming a quick action should not show an error, and data should update properly in the frontend.

### Steps To Reproduce

1. Create a quick action
2. Rename the quick action

### Version

5.61.2

### What operating system are you using Firebot on?

Linux Distro

**Comment by zunderscore** [comment]
Released in v5.62.0
