### ISSUE TITLE
[Feature Request] Edit Effect Test Effect 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

  metadata for the effect runner is missing the userid and useridname, when testing an effect the result is string empty 

### Expected Behavior

to show appropriate
userid and uiseridname when testing effects that use the variables  

### Version

5.61

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Released in v5.62.0
