### ISSUE TITLE
[Bug] auto disconnected alert not refreshing on connect

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

auto disconnect not alert is not being told to remove it self on some connections. 
![image](https://github.com/crowbartools/Firebot/assets/8982158/9ef9fbbb-6729-4d27-95ac-00db8f7386b0)

### Expected Behavior

only show the disconnected from chat alert when unable to recover 

### Version

5.61

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Released in v5.62.0
