### ISSUE TITLE
[Bug] preset arguments not converting data proper 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in a preset effect with value1 and value2 arguments 

result: $if[$OR[$#value1, $#value2], When_true, When_false]

supplying true or false or 1 or 0 returns true 
put this in a custom variable and it converts fine  

### Expected Behavior

being able to consume an argument variable un altered 

### Version

5.61.2

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Preset effect list arguments only pass values as strings, therefore you must do a comparison to a `$true` or `$false` (e.g. `$if[$OR[$#value1 == $true, $#value2 == $true], When_true, When_false]`). Therefore, this is working as designed.
