### ISSUE TITLE
[Bug] Clip EffectOuput is not populating the clip url

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

please make it so that the effectOuput var contains the URL to the clip 

### Expected Behavior

have the url to the clip not just the twitch stream link 

### Steps To Reproduce

create a clip while live and log the ouput it will return blank 

### Version

5.61

### What operating system are you using Firebot on?

Windows 10

**Comment by zunderscore** [comment]
Released in v5.62.0
