### ISSUE TITLE
[Bug] Extension messages do not trigger commands

### ISSUE THREAD

**Issue by Skarnivorous** [crowbartools/Firebot#2433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When an extensions sends a message to chat (which displays as a message sent from the extension name) Firebot commands do not trigger.

### Expected Behavior

Commands should trigger when chat command is sent from an extension.

### Version

5.61.2

### What operating system are you using Firebot on?

Windows 11

**Comment by Skarnivorous** [comment]
This is where the feature was first requested and closed as implemented. https://github.com/crowbartools/Firebot/issues/1238

**Comment by zunderscore** [comment]
Converting this to a feature request. The original request was for extension messages to appear in the chat feed, but not to trigger commands/events.

**Comment by Skarnivorous** [comment]
Haha I guess there's a use case either way 😭

**Comment by zunderscore** [comment]
Released in v5.62.0
