### ISSUE TITLE
[Bug] No run.sh or other installer in latest Linux release

### ISSUE THREAD

**Issue by Tarliman** [crowbartools/Firebot#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The tar.gz file for the latest Linux version has no installer script. It has no launch script. It has no documentation in the file or on your site. Release is not usable. 

### Expected Behavior

Download should contain an installer or launcher script.
Devs should write doc for their code. 

### Steps To Reproduce

Download the file.
Open it.
Attempt to install or launch.

### Version

5.61.2

### What operating system are you using Firebot on?

Linux Distro

### Relevant log output

```shell
No log created as no code was executed.
Linux distro is MX Linux, current patchlevel.
```

### Contact Details (Optional)

andrew.ragland@gmail.com

**Comment by dennisrijsdijk** [comment]
Crowbar's team is primarily made up of windows users, so Linux documentation hasn't been a priority.

To run the bot, download the tar.gz, extract it in a folder, cd into the folder (as you must run it from the working directory) and run the `Firebot v5` executable.

If you find it still won't launch when running from terminal, please paste your logs into this issue.

**Comment by zunderscore** [comment]
Release notes for both the latest stable release and latest beta release have been updated with Linux instructions and future builds will include the updated instructions. Closing this as completed.
