### ISSUE TITLE
[Feature Request] Add FLAC filetypes to Random from Folder on Play Sound Effect

### ISSUE THREAD

**Issue by arblane** [crowbartools/Firebot#2448]
**Describe the solution you'd like**
Add FLAC audio filetypes to the 'Random from Folder' option on 'Play Sound' Effect. 

**Additional context**
Currently FLAC audio files are supported singularly on the 'Local' option, as seen in the preset filetypes list on the select file dialog.
![image](https://github.com/crowbartools/Firebot/assets/121884837/adc0403f-826e-42a1-b0b6-e64a9f9aeb63)

Firebot version 5.61.2

**Comment by zunderscore** [comment]
Released in v5.62.0
