### ISSUE TITLE
[Bug] Toggle All Connections in Toggle Connection effect only toggles Twitch

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using a 'Toggle Connections' effect set to 'All Connections', only Twitch is toggled.

### Expected Behavior

All connections should be toggled, rather than just Twitch

### Steps To Reproduce
If using another integration with connection like StreamElements, skip to step 4

1. Download and install the script from https://github.com/dennisrijsdijk/firebot-script-hyperate/releases/tag/v1.0.0-rc2
2. Enable the script in the bot
3. In Settings > Integrations > Hyperate, set the ID to `internal-testing`
4. Create a 'Toggle Connections' effect
5. Set the mode to 'All Connections'
6. Run the effect. 
7. Observe only Twitch toggling.

### Version

5.61.2 & 5.62-beta2

### What operating system are you using Firebot on?

Linux Distro

**Comment by zunderscore** [comment]
Released in v5.62.0
