### ISSUE TITLE
[Bug] Channel Reward redemption not triggering

### ISSUE THREAD

**Issue by DrizzintahL** [crowbartools/Firebot#2457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Users are redeeming channel point redemptions on Twitch while the channel is live and it's showing up in chat (that grey chat/twitch system text) that it's being redeemed but Firebot isn't getting triggered.

![image](https://github.com/crowbartools/Firebot/assets/139507939/d47eea59-20dc-4b01-bd42-17441dad4b4c)
![image](https://github.com/crowbartools/Firebot/assets/139507939/f90aa662-5617-4e08-9ccd-04011b2d6274)
![image](https://github.com/crowbartools/Firebot/assets/139507939/3077d4b1-f7a5-4c91-8373-06e5c209e5f2)

Chat is the first effect and it's not even posting that.  Firebot is connected with 3 green checks in the lower left. (OBS, Twitch, Stream Elements)

I clicked a STOP ALL button I have, which is Effect -> Clear Effects -> Overlay (ALL), Sounds, Effect Queues (ALL) and redeemed another reward myself and it still didn't trigger. (I figured maybe an effect queue somewhere got caught up, but that doesn't seem to be the case)

### Expected Behavior

Expected that any redemptions of Channel Rewards should trigger Firebot.  

### Steps To Reproduce

This is the third time Firebot has caught up on channel point redemptions (multiple, some I've had for months, some are new, doesn't seem to be a single "new effect" or anything like that, I can't find any pattern to reproduce this.

### Version

5.61.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

DrizzintahL on Discord

**Comment by CKY-** [comment]
is the GFX queue enabled?

**Comment by DrizzintahL** [comment]
Yes, this is an inconsistent issue, I can restart the bot and it works again.

**Comment by zunderscore** [comment]
I'm looking into this issue. There are some related issues with maintaining a longer term connection to Twitch's EventSub system that will be fixed in a future version, but no ETA yet.

**Comment by DrizzintahL** [comment]
I believe I made a mistake and this may have been related to Amazon Polly TTS, I've changed it back to default TTS and it's been good so far, will report back if that was hiccuping or if it was something else.  My oversight >_<

**Comment by zunderscore** [comment]
Released in v5.62.0
