### ISSUE TITLE
[Feature Request] Subcommand Name in Deletion confirmation

### ISSUE THREAD

**Issue by GrandpaCelery** [crowbartools/Firebot#2458]
The current delete subcommand popup reads "Are you sure you want to delete this subcommand?" for each confirmation, a total of 2.

I would love to have the actual subcommand name I'm deleting in the popup text, it can be hard to track/see if you're deleting the right one and the prompt currently only specifies you're deleting a subcommand, not which one.

**Comment by zunderscore** [comment]
Released in v5.62.0
