### ISSUE TITLE
[Feature Request] Better Fallback subcommand UX

### ISSUE THREAD

**Issue by GrandpaCelery** [crowbartools/Firebot#2459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The fallback subcommand is not visible for editing when no other subcommands have been defined.
Creating another subcommand makes both appear, removing said subcommand makes both disappear.
The fallback subcommand isn't actually deleted, just not visible. Making a new subcommand after will have the fallback command reappear as it was.

### Expected Behavior

Create fallback subcommand
See fallback command in UI

### Steps To Reproduce

1. Create fallback subcommand
2. See fallback command in UI
3.  Fallback not visible until another subcommand is created.

### Version

5.62.0-beta3

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

Discord: grandpa_celery

**Comment by zunderscore** [comment]
Released in v5.62.0
