### ISSUE TITLE
[Bug]# subcommand text showing on other subcommand after deletion visual bug

### ISSUE THREAD

**Issue by GrandpaCelery** [crowbartools/Firebot#2460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you have multiple subcommands and one of them is a any number # subcommand
When you delete the # subcommand the "#" is shown behind the subcommand name underneath it
It doesn't actually edit the name, saving and reopening clears it and show the subcommands correctly.

### Expected Behavior

When deleting the number # subcommand it is removed.

### Steps To Reproduce

1. Create a Number subcommand
2. Create an additional custom subcommand
3. Delete the Number subcommand
4. The "#" is now behind the name of the remaining subcommand

### Version

5.62.0-beta3

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

Discord: grandpa_celery

**Comment by zunderscore** [comment]
Released in v5.62.0
