### ISSUE TITLE
[Bug] Cooldown Effect Visual Bug

### ISSUE THREAD

**Issue by GrandpaCelery** [crowbartools/Firebot#2462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When selecting a Single Command Selection Type, after selecting a command from the dropdown, the Cooldown base/sub command choice appears.

When switching to a Command With Tag Selection Type **after** selecting a single command from the dropdown the Cooldown choices remain.

When selecting a Command With Tag Selection Type from the beginning the Cooldown choices don't appear.
It looks to be a visual bug and the actioned behavior seems to confirm that when selecting a subcommand to be disabled after having switched to With Tag that functionality doesn't work.

I have made a feature request seperately as I was hoping that we could specify subcommands even on Tag cooldown #2461 

### Expected Behavior

When switching from Single Command to Commands With Tag, after having specified a subcommand to be affected. The cooldown command/subcommand choices remain on the screen. Commands With Tag doesn't allow for specifying subcommands at all therefore the choice should not be shown.

### Steps To Reproduce

1. Add a Cooldown Command Effect
2. Select Single Command
3. Specify a command from the dropdown
4. Cooldown choices appear
5. Switch to Commands With Tag
6. Cooldown choices remain but aren't functional

### Version

5.62.0-beta3

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Discord grandpa_celery

**Comment by zunderscore** [comment]
Released in v5.62.0
