### ISSUE TITLE
[Feature Request] Add or change variable copy to use short hand

### ISSUE THREAD

**Issue by arblane** [crowbartools/Firebot#2465]
**Describe the solution you'd like**
It would be nice to either add or modify the variable copy functionality to copy as short hand.

**Additional context**
For example on the HTTP Request effect...
![image](https://github.com/crowbartools/Firebot/assets/121884837/b1c00f47-bc7f-4a52-8267-49c7bacdd79a)

**Comment by CKY-** [comment]
arblane i think your going to like this closing as duplicate of #2466
