### ISSUE TITLE
[Bug] Unicode display name issue

### ISSUE THREAD

**Issue by SeriousX** [crowbartools/Firebot#2469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found an issue with users that have Chinese symbols as names. Thi is second user i see in my chat.
The problem is that his Twitch name is "ハンサム" but when he sends messages his name is shown as "ハンサム (anaikero)".
Twitch has Name and Shown name. (as i understand) so user makes a symbolic name but twitch adds a translation to his name for common english users.

FireBot sees user as "ハンサム" in Viewers.
But when user Plays a game he post it as view name "ハンサム (anaikero)" and bot cannot add currency to "ハンサム (anaikero)" as such user doesnt exist. 

### Version

latest as there is no way not to update

### What operating system are you using Firebot on?

Windows 10

**Comment by dennisrijsdijk** [comment]
This is something we've been working on for v5.62. I'd recommend checking out the beta (make backups first!!!) to see if that'll help with your issue. You can find the beta under the releases tab on the github.

**Comment by zunderscore** [comment]
Released in v5.62.0
