### ISSUE TITLE
[Feature Request] `$userInChat` variable

### ISSUE THREAD

**Issue by Oceanity** [crowbartools/Firebot#2477]
**Describe the solution you'd like**
I am currently trying to make commands that only work when a specific chat bot I do not control is currently in my chat reading activity, and it does not announce itself when it connects, so it'd be nice to have a `$userInChat` var that queries `/helix/chat/chatters` to see whether or not a particular Twitch user is in chat.

**Comment by Oceanity** [comment]
Thankies! :> 💜

**Comment by zunderscore** [comment]
Released in v5.62.1
