### ISSUE TITLE
[Feature Request] $isAdBreakRunning variable

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2480]
**Describe the solution you'd like**
Add a variable that returns $true when an ad break runs, and $false when there isn't one.

**Additional context**
I've seen some people poll the $secondsUntilNextAdBreak variable in a timer to update an onscreen timer, or send out *multiple* messages for upcoming ads. However, while the ad break is happening, this behavior should be paused or handled differently.

**Comment by arblane** [comment]
I would like to see this implemented as well. I have some timed events that would benefit from not running during an ad break.

**Comment by zunderscore** [comment]
Released in v5.62.1
