### ISSUE TITLE
[Feature Request] Better UX for full text custom command search 

### ISSUE THREAD

**Issue by dennisrijsdijk** [crowbartools/Firebot#2481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The commands search bar searches through the entire command (eg. in effects, mod restriction), rather than just the command trigger.

### Expected Behavior

The search should only search for the title (maybe also the regex description if regex trigger is enabled?) of the command

### Steps To Reproduce

1. Create a new simple command. Make sure the title does **not** contain the text "Sheep"
2. Add the text "Beep Beep I'm A Sheep"
3. Save the command
4. Search the word "Sheep" in the commands list
5. Observe this new command showing up in the search result when it shouldn't

### Version

v5.62.0

### What operating system are you using Firebot on?

Linux Distro, Windows 11

**Comment by zunderscore** [comment]
Released in v5.62.1
