### ISSUE TITLE
[Bug] The "add to textfield" button in the Variable Menu does not work in the Show Text effect 

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

using WYSIWYG variables are not insertable with the + button 

### Expected Behavior

it add the selected variable 

### Version

5.62

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
Released in v5.62.1
