### ISSUE TITLE
[Bug] Ad Break timer doesn't include hours

### ISSUE THREAD

**Issue by huds601** [crowbartools/Firebot#2485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ad Break timer added in latest version does not account for hours on Ads Manager if you run additional ads before the next break is due.
![image](https://github.com/crowbartools/Firebot/assets/42800359/d06a6c24-cdff-4301-9e6e-83a331c79991)

### Expected Behavior

Timer should show hours

### Steps To Reproduce

1. Start a stream
2. Run a 3 minute ad
3. Wait 5 minutes after ads finish to run ads again
4. Next ad break will be in 1+ hours, but Firebot will only show minutes and seconds

### Version

5.62.0

### What operating system are you using Firebot on?

Windows 11

**Comment by zunderscore** [comment]
Released in v5.62.1
