### ISSUE TITLE
Unable to see the "custom rewards" when creating new event

### ISSUE THREAD

**Issue by RageBoy009** [crowbartools/Firebot#2491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When creating a event and select trigger on Channel Reward Redemption i don't see them in the filters " Reward is "select one" only shows a list w/o any names.

### Expected Behavior

I should see the rewards like before.

### Steps To Reproduce

Create a event with trigger being reward redemption and try to add a filter with "Reward" "is" and when u click on "select one" u see an empty list.

### Version

5.62.1

### What operating system are you using Firebot on?

Windows 11

**Comment by SReject** [comment]
Just to be sure, was the reward create within firebot?

Twitch limits the rewards external apps (like firebot) can access to only rewards created by the respective app.

**Comment by RageBoy009** [comment]
yep its on every reward, even the ones i just created in firebot, atm im using the "reward name is" option and add the name, its just not really convenient
