### ISSUE TITLE
[Bug] Run Command Effect argument not empty

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#2503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 run command effect returns undefined rather then an empty argument. 

### Expected Behavior

when a run command effect has no arguments it should return a null or string empty to remove the arguments that are sent from the command rather than string undefined

this may not be the issue just the observation. 

### Steps To Reproduce

create 2 commands one with chat $arg[all] add a run command effect to the other calling the first command with no arguments or user. 

### Version

5.62

### What operating system are you using Firebot on?

Windows 10

**Comment by dennisrijsdijk** [comment]
When adding an argument, then removing it (making the arguments textbox empty) it works as expected, sending an empty string rather than a string undefined
