### ISSUE TITLE
[Feature Request] Custom WebSocket output

### ISSUE THREAD

**Issue by SonicXVe** [crowbartools/Firebot#2514]
**Describe the solution you'd like**
The only websocket that seems to be supported is OBS. It would be nice to be able to send events to custom websockets on different ports for applications that aren't explicitly supported by Firebot.

**Additional context**
Some ancillary applications for handling stream events and logic like VNyan and Macrograph support sending/receiving websocket events and it would be convenient to be able to tie existing functionality together along with things that Firebot does uniquely well that are missing in other applications.

**Comment by dennisrijsdijk** [comment]
You should use Firebot's scripting engine for this use case. It'll allow you to make a websockets connection of your choice and interact with it as you choose.

**Comment by zunderscore** [comment]
We also use WebSocket connections for integrations like StreamElements and Streamlabs, plus a few other third-party integrations not included with Firebot. So it's definitely something Firebot can/does do.

However, the ability to use arbitrary WebSocket connections probably isn't something we would add to Firebot core functionality, as that's more specialized and complicated to maintain than sending single HTTP requests. As Dennis mentioned, this is definitely a use case for a plugin/custom script, though. If there are specific integrations you're looking to add (like the ones you mentioned), we have a [template project](https://github.com/crowbartools/firebot-custom-script-starter) that can help you get started building out a custom script for whatever integrations you'd like.

For the time being, however, closing this issue as this isn't something we would add to Firebot core.
