### ISSUE TITLE
Missing Icons[Bug] 

### ISSUE THREAD

**Issue by AndrewHatters** [crowbartools/Firebot#2529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Immagine 2024-04-25 210012](https://github.com/crowbartools/Firebot/assets/97824818/a838cbce-b831-4e85-ac0a-c7691522217a)
I hopened the software after dinner, i tried to restart the pc and nothing changed

### Version

5.62.1

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

cacaoamaro (discord account)

**Comment by zunderscore** [comment]
This is an issue with the Font Awesome icon library that we use, not in Firebot itself. Font Awesome is aware of the issue and working to resolve it. You can track the status on [their status page](https://status.fortawesome.com/)

We're also exploring ways to work around this issue in future releases and have an issue open for that already, which you can track here: #1829
