### ISSUE TITLE
[Bug] Clean counter file when deleted

### ISSUE THREAD

**Issue by florian-luce** [crowbartools/Firebot#2535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

From FireBot, if I create a counter, since I delete it, the local files are not deleted (...\Firebot\v5\profiles\profilName\counters\counterName.txt)

### Expected Behavior

When I delete a counter from the "Counter" menu. The associated counter file is deleted in order to maintain consistency between the physical files and the configuration, and to maintain general optimization logic.

Or suggest deletion if we wanted to delete the local file or make it configurable in the general configuration

### Steps To Reproduce

1) In "Counters" menu, create new counter
2) Use this counter
3) In "Counters" menu, delete the counter
4) Check in the counter file in ..\Firebot\v5\profiles\profilName\counters\counterName.txt

### Version

5.62.1

### What operating system are you using Firebot on?

Windows 10 (Windows_NT 10.0.19045)

**Comment by CKY-** [comment]
added in version 5.67
