### ISSUE TITLE
[Feature Request] Update Inactive Viewer Time when using Channel Points

### ISSUE THREAD

**Issue by florian-luce** [crowbartools/Firebot#2537]
**Describe the solution you'd like**
When a user use a Channel Points Reward, from the dashboard, the user always appears with the orange status (lurking)
While it is active and should appear green, depending on the time set in the options.

**Additional context**
1) User have orange status (is AFK - lurking)
2) User use Channel Point (no write in chat)
3) User is still have orange status (lurking) -> While it should be green here

**Comment by codehdn** [comment]
I think I've got a fix for this but gave up my affiliate status last month and have no way to test the change. Following the code I do believe this should work, if anyone is able to take a look and verify, I will put up the pr once confirmed by someone who is affiliate. https://github.com/codehdn/Firebot/commit/1812e12bbadc1536417da0a3aa5822fe357930dc
