### ISSUE TITLE
[Support] Firebot Won't Install

### ISSUE THREAD

**Issue by XacerPT** [crowbartools/Firebot#2564]
**Firebot Won't Install**
I had Firebot installed, but today trying to open it gave an error, and now reinstalling keeps giving an error, and I can't solve it, can someone help me?
I also tried reinstalling from previous versions but it didn't work anyway
![Captura de ecrã 2024-05-24 131506](https://github.com/crowbartools/Firebot/assets/29576552/1e7fe16e-63e3-446a-9431-02acb9e48323)
[SquirrelSetup.log](https://github.com/crowbartools/Firebot/files/15434120/SquirrelSetup.log)

**Comment by CKY-** [comment]
you can join the [discord ](https://discord.gg/crowbartools-372817064034959370 )and post an issue
are you trying to install as admin?

**Comment by XacerPT** [comment]
yes I've run it as an administrator but it always gives this error, I've even cleaned everything from the old appdata installation and it still doesn't work

**Comment by CKY-** [comment]
and what happens when you run normal?

**Comment by XacerPT** [comment]
It's always the same

**Comment by CKY-** [comment]
delete the SquirrelSetup.log file

**Comment by CKY-** [comment]
run without AS administrator 
and start sharing screenshots so I can see where install is falling

**Comment by CKY-** [comment]
also delete C:\Users\xfvmx\AppData\Local\Temp\.squirrel-lock-DA5F3EA83DEC514AD7ED5886B06FF547B66989E5

**Comment by XacerPT** [comment]
i deleted the whole folder from "C:\Users\xfvmx\AppData\Local\SquirrelTemp" , I didn't find it "C:\Users\xfvmx\AppData\Local\Temp.squirrel-lock-DA5F3EA83DEC514AD7ED5886B06FF547B66989E5".
[SquirrelSetup.log](https://github.com/crowbartools/Firebot/files/15434389/SquirrelSetup.log)
![Captura de ecrã 2024-05-24 133815](https://github.com/crowbartools/Firebot/assets/29576552/e6f9ab33-5225-473a-971a-e5dd21e55c7a)

**Comment by CKY-** [comment]
the log is still complaining about that file do you have an antivirus that is not windows defender

**Comment by XacerPT** [comment]
I misunderstood, I now deleted the temp folder everything I had and managed to delete it inside, and tried again but it's still the same
[SquirrelSetup.log](https://github.com/crowbartools/Firebot/files/15434514/SquirrelSetup.log)

**Comment by XacerPT** [comment]
No, I only have Windows Defender

**Comment by CKY-** [comment]
add an [exception ](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26)to the install file

**Comment by XacerPT** [comment]
It's still the same (I already had a folder that's excluded from Windows Defender so I was quick to test it)

**Comment by CKY-** [comment]
the install file? 
and you are not running as administrator correct?

**Comment by XacerPT** [comment]
yes

**Comment by CKY-** [comment]
can you record a video of what happens when you open the file and post it?

**Comment by XacerPT** [comment]
https://youtu.be/0PBxMdYn3nE

**Comment by XacerPT** [comment]
I've already figured out the solution.
Solution:
Add  your user to the temp folder with all the permissions.
You can see your user using whoami in the command line.

**Comment by XacerPT** [comment]
![solution](https://github.com/crowbartools/Firebot/assets/29576552/f96fcb55-a915-4c9b-ba0f-92b579ddd4d8)
