### ISSUE TITLE
[Support] With update to 5.62.1 all custom role assignments are deleted

### ISSUE THREAD

**Issue by DontCallMeChicken** [crowbartools/Firebot#2590]
I haven't used Firebot for about 6 months because I haven't been live. A few days or week ago, I updated Firebot from version _v5.58.1_ to the current version _5.62.1_.

Now I noticed that all custom roles assigned to the respective users have been deleted from the user database.
The roles created are still there, but are no longer assigned to any user. The roles are all still created in the `custom-roles.json` and are also displayed within Firebot under _"Viewer Roles"_.

Is there a way to restore the custom roles?

- Excerpt `custom-roles.json`:
```
{
    "d7012a50-1b43-11ed-9f55-470e1fb35f76": {
        "id": "d7012a50-1b43-11ed-9f55-470e1fb35f76",
        "name": "Geschmeidig",
        "viewers": []
    },
    "62a74990-1b44-11ed-9f55-470e1fb35f76": {
        "id": "62a74990-1b44-11ed-9f55-470e1fb35f76",
        "name": "Chaostruppe",
        "viewers": []
    },
    "7ae57850-43f9-11ed-ad67-eda6f232f1f9": {
        "id": "7ae57850-43f9-11ed-ad67-eda6f232f1f9",
        "name": "Ehrenvogel",
        "viewers": []
    },
     …
}
```

- User database: 
An example entry from the database. I have changed user-related data with "*".
```
{"username":"*********","_id":"*********","displayName":"*********",
"profilePicUrl":"https://static-cdn.jtvnw.net/jtv_user_pictures/*********-profile_image-300x300.png",
"twitch":true,"twitchRoles":["sub","vip"],
"online":false,"onlineAt":1702071443201,"lastSeen":1702081985158,
"joinDate":1662923323640,"minutesInChannel":15477,"chatMessages":8289,
"disableAutoStatAccrual":false,"disableActiveUserList":false,"disableViewerList":false,
"metadata":{},"currency":{"2b16b630-318a-11ed-8b28-b763965e79c7":100,"0a0dc3d0-54ed-11ed-8550-4de96cbabc47":0,
"9fe48ce0-55c4-11ed-8195-353763c7a397":0,"d0232ab0-55c4-11ed-8195-353763c7a397":0}}
```

- Additional Information:
Firebot Version: 5.62.1 (before: 5.58.1)
OS: Linux Distribution

**Comment by dennisrijsdijk** [comment]
You should also still have a `customroles.json` file. If you log in, then restart, does that sync?

If not, you'll have to pull the file from the latest backup

**Comment by DontCallMeChicken** [comment]
> You should also still have a `customroles.json` file. If you log in, then restart, does that sync?

I have an outdated customroles file under this path:
`.config/Firebot/tmp/restore/profiles/Main Profile/roles/customroles.json`
The "customroles.jason" is from August 2022. So it is not up to date at all. :)

**Comment by DontCallMeChicken** [comment]
> If not, you'll have to pull the file from the latest backup

There is also no `customroles.json` file in the backups. Unfortunately, I no longer have any backups from using Firebot version _5.58.1_.

**Comment by CKY-** [comment]
was this fixed?
