### ISSUE TITLE
[Bug] "Play Sound" effect does not respect "Audio Output Device"

### ISSUE THREAD

**Issue by ShawnDeviron** [crowbartools/Firebot#2596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "Play Sound" effect does not appear to respect the Audio Output Device field.

### Expected Behavior

When selecting another Audio Output Device, the sound should be played to only that device.

### Steps To Reproduce

1. Create and Event for "Chat Message (Twitch)".
2. Create an Effect for "Play Sound".
3. Choose File for sound clip
4. Select Audio Output Device (other than system default)
5. Test Effect (or let effect happen naturally)

### Version

5.62.1

### What operating system are you using Firebot on?

Windows 11

### Contact Details (Optional)

ShawnDeviron

**Comment by ShawnDeviron** [comment]
I forgot to mention, I am using Voicemeeter Potato with virtual audio inputs and outputs. The effect seems to be playing on my system default.

**Comment by CKY-** [comment]
> I forgot to mention, I am using Voicemeeter Potato with virtual audio inputs and outputs. The effect seems to be playing on my system default 

try changing the 
setting>general> sound output device

**Comment by ShawnDeviron** [comment]
Hello,

Thank you for your response. I have made this change, but the results
remain consistent. It does not play to the selected audio sources.

Thanks,


Shawn Thoms

Phone: (570) 807-6290

Email: ***@***.***

**Comment by phroggster** [comment]
I can recreate this in Windows 10, but **only** if I manually edit the Windows "App volume and device preferences" settings to redirect **all** Firebot audio to a non-default device. If I reset the Window's audio routing settings to defaults, the Firebot Play Sound (etc.) effect's Audio Output Device selection is properly utilized.

@ShawnDeviron I would also suggest editing your prior comment here, as your phone number is now publicly visible on a web page that does not require authentication to view.

**Comment by CKY-** [comment]
@ShawnDeviron can you join the [discord ](https://discord.gg/crowbartools-372817064034959370)

**Comment by CKY-** [comment]
windows 11 uprated the audio sources again restarting the windows audio service and resetting the audio devices in the control panel with some audio remapping  voiceMeater fixed this issue 
[Microsoft support](https://support.microsoft.com/en-us/windows/fix-sound-or-audio-problems-in-windows-73025246-b61c-40fb-671a-2535c7cd56c8)
In the search box on the taskbar, type services, then select it from the results.

Select each of the following services, select and hold (or right-click), select Restart, and then select Yes: 

- Windows Audio

- Windows Audio Endpoint Builder

- Remote Procedure Call (RPC)
