### ISSUE TITLE
[Support/Bug] Intermittent Blurry Text in App

### ISSUE THREAD

**Issue by phroggster** [crowbartools/Firebot#2639]
v5.62.1 app text frequently, but intermittently, gets fairly blurry in Windows 11. This was evident on-stream, and (reportedly) in-person, but only evident in Firebot. Overlay text appeared normal, as did other text and applications visible on screen. 

[Discord thread](https://discord.com/channels/372817064034959370/1265824195980427324) includes a screen shot, and further system information.

**Comment by phroggster** [comment]
Nvidia FXAA being globally-enabled can cause this issue, as discussed in Github Desktop [issue 17444](https://github.com/desktop/desktop/issues/17444#issuecomment-1736417091), which provides a solution: set "Antialiasing - FXAA" to "Off" in the Nvidia Control Panel either by default in "Global Settings", or for Firebot individually in "Program Settings." However, using Firebot-specific application settings will likely revert this setting after application updates.

**Comment by zunderscore** [comment]
As there is a workaround and this is not an issue specific to Firebot, closing this.
