### ISSUE TITLE
[Bug] Streamer Account Logged Out after Putting Host PC to Sleep

### ISSUE THREAD

**Issue by Rvby1** [crowbartools/Firebot#2646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After you put the host PC for firebot to sleep, it will log out of the streamer account upon rebooting. The bot account is never logged out and maintains an active connection without any issues. This does not happen if Firebot is closed when the PC goes to sleep.

(More documentation here: https://discord.com/channels/372817064034959370/1234647354750271528)

### Expected Behavior

When you put the PC to sleep, your streamer account should stay logged in, just like the bot account.

### Steps To Reproduce

1. Log in to a streamer account using Firebot
2. Put the host PC to sleep 
3. Wake up the host PC
4. Note that your streamer account has been logged out

### Version

v5.62.1

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

Rvby on Discord

**Comment by CKY-** [comment]
```
[2024-07-31 19:31:56.0162] - debug: [v5.63.0-beta1]  
{
  message: 'connect ECONNREFUSED ::1:4453',
  stack: 'Error: connect ECONNREFUSED ::1:4453\n' +
    '    at OBSWebSocket.onError (C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\firebot\\app-5.63.0-beta1\\resources\\app.asar\\node_modules\\obs-websocket-js\\dist\\json.cjs:751:17)\n' +
    '    at callListener (C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\firebot\\app-5.63.0-beta1\\resources\\app.asar\\node_modules\\ws\\lib\\event-target.js:290:14)\n' +
    '    at WebSocket.onError (C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\firebot\\app-5.63.0-beta1\\resources\\app.asar\\node_modules\\ws\\lib\\event-target.js:230:9)\n' +
    '    at WebSocket.emit (node:events:517:28)\n' +
    '    at emitErrorAndClose (C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\firebot\\app-5.63.0-beta1\\resources\\app.asar\\node_modules\\ws\\lib\\websocket.js:1033:13)\n' +
    '    at ClientRequest.<anonymous> (C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\firebot\\app-5.63.0-beta1\\resources\\app.asar\\node_modules\\ws\\lib\\websocket.js:880:5)\n' +
    '    at ClientRequest.emit (node:events:517:28)\n' +
    '    at Socket.socketErrorListener (node:_http_client:501:9)\n' +
    '    at Socket.emit (node:events:517:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)',
  code: -1
}```
here is the error that accompanies this

**Comment by Rvby1** [comment]
Hey, I'm realizing I should probably comment this here as well. Some change in a recent update seems to have brought this issue back. Numerous users are reporting this problem on the Discord, and I am as well. @ebiggz
