### ISSUE TITLE
$obsSceneName variable not working [Support] 

### ISSUE THREAD

**Issue by ThatNerdyGuyHD** [crowbartools/Firebot#2660]
**Help Request**
Enter a clear and concise explanation of the issue you are having or the thing you would like help with.

I have been using firebot for a little bit now. I had a channel point redemption where is checks to see if I am on a certain obs scene and if I am, it will switch to another scene. If not, it would send a chat message and refund the points. It was working perfectly fine last week and now it doesnt work anymore. None of the coding has been changed, and it always goes to the otherwise variable no matter what scene I am on. Any help would be great... are the variables different now? Thank you! 

The following 4 files have a visual of the issue:

![help1](https://github.com/user-attachments/assets/1f8c14e2-32c9-4aa3-92cc-813cbc1234a5)
![help2](https://github.com/user-attachments/assets/f772f709-b604-44a2-9a8e-17647473793c)
![help3](https://github.com/user-attachments/assets/7cd7b1f6-e622-441a-b206-30b4a28370ae)
![help4](https://github.com/user-attachments/assets/5861a34a-e079-4fd8-98bb-99ef711c797d)

**Comment by dennisrijsdijk** [comment]
Make sure the OBS Websocket is still enabled and connected. I've noticed that updating to 30.2 has wiped my websocket settings, which would be consistent with a failure like this

**Comment by ThatNerdyGuyHD** [comment]
I did, I reset it a couple of times. I can try it again real quick
