### ISSUE TITLE
[Bug] JSON Array no longer parses after 5.63.0

### ISSUE THREAD

**Issue by TheLoneUs** [crowbartools/Firebot#2773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have a preset effect that calls the Twitch API and then parsed the JSON response for an ID. This stopped working with the `5.63.0` version, I believe caused by https://github.com/crowbartools/Firebot/pull/2651

### Expected Behavior

I should be able to get array elements from JSON.

### Steps To Reproduce

Here is a preset effect that is affected that worked prior to `5.63.0`. (I had to change the file extension to upload, but this is a firebot setup for a preset effect)
[Twitch ID 2.json](https://github.com/user-attachments/files/16830715/Twitch.ID.2.json)

Essentially this appears to happen for any similar JSON response when trying to access a specific field.

### Version

5.63.2

### What operating system are you using Firebot on?

Windows 10

### Contact Details (Optional)

I will respond to Github emails.

**Comment by phroggster** [comment]
I might be missing something here, but the Firebotsetup (JSON) file linked only has one event in it that triggers upon startup, connects to integrations, and then runs two other preset effect lists. It doesn't seem to include the preset effect lists that do anything with JSON parsing.

Depending upon what your preset effect lists are actually doing, it would be helpful to include the JSON data file that you're working upon here in this bug report, in addition to any impacted preset effect lists that are doing the actual loading/parsing.

**Comment by TheLoneUs** [comment]
That should be everything need to replicate the issue. When firebot starts up it reaches out the the API and gets the JSON data, however, it is unable to assign anything in the custom variable assignment step by referencing the array keys as it did prior to this update.

**Comment by TheLoneUs** [comment]
My mistake, I uploaded the wrong file. I updated the original message with the correct file.

**Comment by phroggster** [comment]
Try `$objectWalkPath[$convertFromJSON[$effectOutput[httpResponse]], data.0.id]` instead of `$arrayElement[$arrayElement[$arrayElement[$convertFromJSON[$effectOutput[httpResponse]],data],0],id]` in your Custom Variable assigning to "twitchUserId".

You're seemingly using `$arrayElement` to get properties from objects that aren't arrays, and I'm sorry that my changes totally broke this unintended use case.

**Comment by phroggster** [comment]
Oops, you can also use this much simpler and offline-capable variable as well:

>$userId[$streamer]

**Comment by TheLoneUs** [comment]
Thank you, I didn't know about the object walking!

**Comment by phroggster** [comment]
You're welcome. I'm going to go ahead and close this report, but let me know if I also messed up anything in your emote-parsing preset effect list and we can reopen it.
