### ISSUE TITLE
[Feature Request] The COMMANDS view `Search commands` should support aliases as well

### ISSUE THREAD

**Issue by mikebaz** [crowbartools/Firebot#2836]
**Describe the solution you'd like**
When searching in the `Search commands` text box, I would like the search to look for aliases as well.  

**Additional context**
When doing maintenance on commands, I sometimes search for the alias, as that's the first thing that comes to mind.  For example, I have a command with a trigger of `!dontlikekids` that also has an alias of `!ftk`.  I would like to be able to find it with `ftk` in the `Search commands` text box.

**Comment by phroggster** [comment]
Click the button to the right of the search field, and it'll open a menu with a checkbox labelled "Full Text Search." Check that checkbox, and aliases, as well as all of the effects and filters inside of the commands, will be searchable.

![Untitled](https://github.com/user-attachments/assets/b337731f-4b6f-4de3-b01b-7ef7c8c6e512)

**Comment by phroggster** [comment]
How did I get a "not planned" closed status, what? Are you doing OK today Github?

**Comment by mikebaz** [comment]
thank you!
