### ISSUE TITLE
[Feature Request] Ability to change Go Live Notification for Twitch

### ISSUE THREAD

**Issue by gvysmily** [crowbartools/Firebot#2854]
**Describe the solution you'd like**
Would like an Effect to let me set Go Live Notification

**Additional context**
Want to change this:
![image](https://github.com/user-attachments/assets/bf1a0757-8250-423d-8446-d7a2078b8004)

Can't find it in effects:
![image](https://github.com/user-attachments/assets/fa040bda-7a86-417c-82f2-56fdf589d5cc)
![image](https://github.com/user-attachments/assets/22dab3a7-5ca3-4128-b16d-ef94a64f4b8b)

**Comment by zunderscore** [comment]
Unfortunately, Twitch does not provide third party apps the ability to change this via the API and currently has no plans to.

You can upvote [this suggestion](https://twitch.uservoice.com/forums/310213-developers/suggestions/39703660-live-notification) on their UserVoice site to encourage them to enable that functionality.

As this cannot be done, closing this issue. If Twitch adds this ability in the future, we can reopen/revisit.
