### ISSUE TITLE
[Feature Request] Throne integration 

### ISSUE THREAD

**Issue by omgkf** [crowbartools/Firebot#2869]
**Describe the solution you'd like**
Connection to Throne 

**Additional context**
To be able to connect to Throne in Intergrations to be able to use firebot for alerts and notifications

**Comment by zunderscore** [comment]
Unfortunately, Throne does not have nor have they announced plans for a public developer API. If they publish one, we'll be glad to look into integrating it into Firebot. At this time, however, closing this issue.

**Comment by zunderscore** [comment]
Throne recently added webhook support. This is now available via plugin here: https://github.com/zunderscore/firebot-plugin-throne
