### ISSUE TITLE
[Feature Request] Multiplatform Support

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#546]
Implement whatever is needed in order to get the app fully functional on:
- [x] Windows
- [x] Linux
- [ ] Mac

We are looking for tech-savvy Mac users to help us in preparing Firebot for MacOS. If you willing, please contact us via our [discord](https://discord.gg/DegW792)

**Comment by SReject** [comment]
We are looking for tech-savvy Mac users to help us in preparing Firebot for MacOS. If you willing, please contact us via our [discord](https://discord.gg/DegW792)

**Comment by Firebottle** [comment]
I think it might be time to go ahead and close this since windows and linux are options now. We can open a new ticket for Mac for v6 consideration.

**Comment by ddomino007** [comment]
What exact kind of help is needed?

**Comment by hypertexthero** [comment]
A macOS version would be lovely!
