### ISSUE TITLE
In App Dev Lab

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#547]
We need to implement a dev lab in Firebot itself and remove our dependency on the Mixer dev lab. The goal of this issue will be to implement a grid system that saves out a usable JSON controls file, complete with the effects on the button.

- [ ] Drag and Drop button grid.
- [ ] Ability to add new buttons to the grid.
- [ ] Ability to delete buttons from the grid.
- [ ] Ability to duplicate any button or scene on the grid.
- [ ] Supports mobile, tablet, and desktop sizes.
- [ ] Button sizes match mixer dev lab contraints.
- [ ] Buttons can't overlap.
- [ ] Button effects are successfully paired with the button json.
- [ ] Ability to import a board from the mixer dev lab for a starting base.

**Comment by JoeZwet** [comment]
couldn't you just iframe this?
