### ISSUE TITLE
Chat Window Spoilers

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#548]
This will be a few quality of life improvements for the chat window.

- [ ] Spoiler Filter list, the ability to build a list of words you'd like to display a "spoiler block" over. The spoiler block should be removed when moused over so the user can see full text. 
- [ ] Spoiler Filter on action, the ability to put spoiler tags over messages that have been deleted from bans, timeouts, etc...

**Comment by ebiggz** [comment]
I think @ThePerry-2015 has finished some of the work for this already. Assigned him to it.

**Comment by Firebottle** [comment]
This was added into v4 and I imagine it'd make its way into v5 when we merge.
