### ISSUE TITLE
Spark Exempt Rewrite

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#551]
We need to completely rewrite the spark exemption functionality. Right now it's tied to which groups are currently active on interactive. In needs to be completely separate from that.

- [x] Ability to give spark exemption to individual users by name.
- [x] Ability to give spark exemption to default groups (moderators, staff, etc...)
- [x] Spark exemption should not be tied at all to groups being active in interactive, similar to how it is now.

**Comment by KensonPlays** [comment]
How about an extension? Ability to exempt specific scenes?

**Comment by Firebottle** [comment]
I actually took care of the main problem in v4. Spark exemption should no longer be tied to active groups. Spark exempt scenes could be cool. It might be something we add after we get the rest of these core v5 features finished.
