### ISSUE TITLE
User Database

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#555]
The user database will hold all of our user information. This is most likely going to be the most used and access database. No pressure.

- [x] Users added to database as they join chat.
- [x] All users have an internal database ID that will never change.
- [x] Users are not duplicated if they rejoin.
- [x] Database is capable of cleanly associating an unknown number of columns with the user.
- [x] Add new GUI interface for showing viewers from database (and later points, hours, etc).
- [x] GUI should allow searching for a specific user.
- [ ] GUI should allow deleting a specific user from the database.
- [x] GUI should allow editing a specific bit of info in the database.

**Comment by ebiggz** [comment]
This is heavily reliant/related to #543

**Comment by Firebottle** [comment]
This should be done for the most part. I imagine we'll be adding to it as we work on everything else.

**Comment by LastMageTV** [comment]
I'm going to go ahead and close this one. The minimum viable product for v5 release is done. We are tracking stats in the backend accurately from what I've seen. 

What we really need is a GUI that allows people to easily edit these stats. However, that can come later after the v5 initial release. The current GUI is pretty bad and not easy to work with.
