### ISSUE TITLE
Live Events Rewrite

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#556]
The live events are a little weird right now. They need to be organized better. We could also use a few more alert types.

- [x] Live events should be grouped by sets. Each set should allow for one live event of each type. IE: One follow, one sub, etc...
- [x] If you have multiple live events of the same type, all of them should run on that event.

**Comment by ebiggz** [comment]
For the second bullet point, I think this will largely be solved by the "click and drag to position in overlay" feature. My vision of that feature its to have it where, when you click on it to open the click and drag interface, it will show you all the effects that show stuff in the overlay. For example, if the Event has a "show text" and "show picture" effect and you opened the "overlay position" tool (or whatever we call it), you'll see both the text and the picture there and you can drag them around to fit however you want.

**Comment by ebiggz** [comment]
We probably also need to give the user the option to have an Event be "queued" that way they they dont overlap each other. This will be tricky tho, as we will need to find a good way to determine how long an Event's list of effects will take to run so we know when to run the next one in the queue.

**Comment by Firebottle** [comment]
I keep assigning this to myself, reading what you wrote, and then thinking "oh crap there is no way I can do that."

But I'll at least get the grouping stuff done.

**Comment by ebiggz** [comment]
Yeah we can tackle the fancy overlay position-er later as that will probably be best to do after or at the same time as the overlay rewrite. Either way, we collectively got this!
