### ISSUE TITLE
[Feature Request] Stream Management

### ISSUE THREAD

**Issue by MageEnclave** [crowbartools/Firebot#557]
Quality of life features.

- [ ] Ability to change stream title from within Firebot GUI.
- [ ] Ability to change stream game from within Firebot GUI.
- [ ] Ability to change audience settings from within Firebot GUI.

**Comment by ebiggz** [comment]
Note, this is now possible (even in v4) via commands including via the chatfeed. Not sure if that satisfies this completely tho.

**Comment by Firebottle** [comment]
Heya @Twizted-Native , since all of this functionality is already available via chat commands (and chat is built into the app) we don't see this as super high priority. However, it will likely find it's way into the app at some point.

**Comment by LastMageTV** [comment]
This would be a good entry level issue. The biggest problem would be finding a good place to put it in the app.

We already built our own functionality to change some of this, so post in discord if you start on this and we can get you better details about where that is located.
