### ISSUE TITLE
Reserved system commands

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#561]
We need a set of system commands that are pre-built similar to other bots common commands. 

- [x] !commands - returns list of commands
- [ ] !steam - returns steam entry for current game
- [x] !uptime - returns uptime of current stream.
- [x] Ability to add more system level commands in the future. (example !quote, !quote add X)
- [x] Ability to Assign permissions
- [x] Ability to disable each system level command.

**Comment by ebiggz** [comment]
For this, we will need to have a proper "System" or "Built In" section in the GUI so the user has visibility on what is available. 
User should be able to do the following to system commands:
- Edit active state
- Add additional effects on top of built in effects/behavior
- Assign permissions
