### ISSUE TITLE
Online Sync

### ISSUE THREAD

**Issue by LastMageTV** [crowbartools/Firebot#565]
We need a way to sync up certain systems to be viewable online somewhere. Mods and viewers use these online sources to see what things are available or to view old quotes. Perhaps google spreadsheets.

- [x] Quotes
- [x] Commands
- [ ] Queue list?
- [ ] Viewer list w/ options to show points or hours?

**Comment by Firebottle** [comment]
For this, we decided to go with a middle man service. We send the json over to it for quotes and commands and then use the website to display this json.

Anyone working on this one will need access to the site itself to upload files and such. A good deal of the basics are built, but this needs a lot of testing.

**Comment by LastMageTV** [comment]
Going to go ahead and make this as finished, and split the others out later on.
