### ISSUE TITLE
[Feature Request] Help Page

### ISSUE THREAD

**Issue by Firebottle** [crowbartools/Firebot#566]
We need a more prominent help page. This should give users basic info on where to go for help, where to see tutorials, etc...

- [ ] Discord Link
- [ ] Link team crowbar website.
- [ ] Instructions (or button) that can zip of log files and prepare them to be sent to a dev.
- [ ] Firebot twitter feed.
- [ ] Mixer error notifications. This would be the same thing we show in the notification bell.

**Comment by LastMageTV** [comment]
This would be a good entry level issue! That would be creating a new "help" page in Firebot. It will have instructions on how to get home, some easy ways to get log files, mixer alerts, and just general helpful information.

**Comment by Firebottle** [comment]
Closing this as I believe it is outdated and we'd want to use the website anyway for this info.
