### ISSUE TITLE
Back To Previous  (vs specific group)

### ISSUE THREAD

**Issue by KensonPlays** [crowbartools/Firebot#599]
## What version of Firebot are you running?
4.10.5

## Please describe the issue or feature requests in as much detail as possible.
Feature Request:

It would be cool if you could have a button 'Go back to Previous' -- So I can have a specific scene available for moderators and regulars, but I don't want the regulars going to the mod scene, of course.

**Comment by KensonPlays** [comment]
Not if you use Firebot here and restrict it to "Moderators" or defined users, etc.

**Comment by ebiggz** [comment]
I have two custom scripts that replicate this behavior, which I gave to Kenson. I think it wouldn't hurt to have it built in so we can leave this ticket open, but it will remain a low priority while we work on V5.

**Comment by Firebottle** [comment]
This can probably be merged in with #552 . That issue handles rewriting the group and scene change stuff. I'll get it added over there.
