### ISSUE TITLE
Firebot is crashing PUBG

### ISSUE THREAD

**Issue by jeffleachtv** [crowbartools/Firebot#601]
Hi folks,

I'm running Firebot v4.10.5

Sporadically Player Unknown's Battlegrounds will crash and the crash report says that a Firebot file is responsible. I'm assuming that PUBG's latest anti-cheat patch might be to blame, but is there any way to fix this?

Many thanks

**Comment by Firebottle** [comment]
Hi! There have been a few instances of PUBG's anti cheat throwing a false flag on Firebot. It doesnt happen to everyone (only one other report out of everyone playing pubg) and I'm not sure how to go about recreating it. If you can, please report Firebot as a false positive to the company.

**Comment by MjolnirDWS** [comment]
Firebottle, do you know how to report the false positive to Battleye? I tried looking it up but can't find it. This is happening to a friend that is streaming pubg on mixer and trying to use firebot as well.

**Comment by Firebottle** [comment]
@MjolnirDWS I would report it here: https://www.battleye.com/contact/

It's likely due to one of two things:
1. The game control emulation in Firebot, which would allow you to "bot" certain games.
2. The exe is not signed. (We're hoping to purchase a cert for v5. They're pretty expensive.)

**Comment by Firebottle** [comment]
I havent seen this issue pop up for a long time. Closing.
