### ISSUE TITLE
Controller vibration

### ISSUE THREAD

**Issue by JesterJFool** [crowbartools/Firebot#606]
I was watching another streamer, and they made a comment about their controller vibrating... It made me think it would be really cool to have a "vibrate controller" feature. As a streamer who plays a lot of jump-scare games, this additional feature would give viewers more of an ability to interact directly with me, and maybe make me jump when my controller suddenly starts vibrating at the same time as one of my noises goes off. I feel like a lot of jump-scare and/or horror game players would enjoy giving this feature to their viewers. I'm sure there could be other interesting uses for the feature as well.

**Comment by Firebottle** [comment]
This would be a very cool feature.

**Comment by Firebottle** [comment]
Going to go ahead and close this one. I don't think we'll be able to get to this one anytime soon as we focus on core features. But I'll make note of this to maybe add in down the line.
