### ISSUE TITLE
When i put the time for my interactive buttons it does not work! the only time i get is 13M cool down on the button no matter what time i put in! 

### ISSUE THREAD

**Issue by iBRooTaLkilla** [crowbartools/Firebot#610]
## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ThePerry-2015** [comment]
Your computer clock is most likely out of sync.
Go to https://time.is  and see what it says about your clock:
On my end it says: `Your clock is 0.1 seconds behind.`

I'm pretty sure on your end this is off by at least 30-60 seconds.
Get your computer clock synchronized  and it should be all good.


- Right click on the clock down in your systray
- Adjust time/date
- Additional date, time & regional settings (on the right side)
- Set the time and date
- Internet Time
- Change settings
- Choose `time.nist.gov` and then push Update now.

The time server can be which ever service you like that offers a NTP service like ntp.org

**Comment by Firebottle** [comment]
Closing as it's been over a week without a response.
