### ISSUE TITLE
hi there i am having a problem with firebot v4.11.1 not connecting my interactive board.

### ISSUE THREAD

**Issue by dean8t3** [crowbartools/Firebot#612]
hi there i am having a problem with firebot v4.11.1 not connecting my interactive board, stuff i have tried is signed out and signed in and uninstalled and re installed but all have failed, not sure if this will help but got it from the log file:
```
19:17:46 GMT+0100 (GMT Summer Time) [v4.11.1] ERROR: Error syncin scenes | message=Packet was cancelled or socket was closed before a reply was received.
19:17:46 GMT+0100 (GMT Summer Time) [v4.11.1] ERROR: | message=Packet was cancelled or socket was closed before a reply was received., level=error, stack=Error: Packet was cancelled or socket was closed before a reply was received., message=Packet was cancelled or socket was closed before a reply was received.
19:17:46 GMT+0100 (GMT Summer Time) [v4.11.1] ERROR: (Renderer) Error creating scenes on Mixer.
```

**Comment by Firebottle** [comment]
Are you still having this issue? We might have to troubleshoot this on discord as it could be complicated. Likely there is something in your setup causing the scene creation to fail when starting interactive.
