### ISSUE TITLE
v4.11.1 - New cooldowns not overwriting shorter cooldowns, people abusing interactions

### ISSUE THREAD

**Issue by Kylix-Tyfurious** [crowbartools/Firebot#613]
## What version of Firebot are you running?

4.11.1

## Please describe the issue or feature requests in as much detail as possible.

When someone uses an interaction on my board, it is suppose to cooldown other interactions for 30s, but if an interaction is already at, say 3s, and someone uses another interaction, the 3s doesn't go back to 30s.

They are essentially able to use multiple interactions at one time, which is what I'm trying to avoid.

This wasn't an issue in previous versions, so I'm not sure what's causing it now. I checked my button settings and didn't see anything out of the ordinary, but if it's a mistake on my end, please advise me on how to fix it. One of my viewers today showed me how messed up it was by timing the cooldowns to where he could use 4 interactions on top of each other.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Is this still an issue? It should be working the way you want. We've written it so that it'll always push up the cooldown if possible. Even if there were a mixer issue, Firebot should be keeping count of cooldowns internally as well. 

Can you check https://time.is for me and make sure your clock is synced on the computer running Firebot?

**Comment by Kylix-Tyfurious** [comment]
Just went into my settings and synchronized my clock to "time.windows.com" and rechecked the link you gave me. It still says that my clock is 1.0 seconds ahead for some reason. 

I checked my board again today (off stream) and the cool downs still aren't overwriting.

Any ideas?
