### ISSUE TITLE
Viewers cannot hear interactive sound

### ISSUE THREAD

**Issue by the-spudinator** [crowbartools/Firebot#614]
## What version of Firebot are you running?

4.11.1

## Please describe the issue or feature requests in as much detail as possible.
 My viewers cannot hear the sounds of my interactive buttons. I stream directly through my xbox and use lightstream as well. I have sounds connected to each button as well. Do I need OBS to make these interactive buttons to work? 

 Fix a sound issue or potential setup error.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Sound plays through either the Firebot app itself, or you can choose to send it to the overlay locally or to another machine on your network.

I don't think you'll be able to use the sound features when streaming through Xbox and using lightstream.
