### ISSUE TITLE
Trouble with keypresses not ending Version 4.11.1.0

### ISSUE THREAD

**Issue by TheDayZStreamer** [crowbartools/Firebot#615]
Version 4.11.1.0

I am having trouble with Firebot not correctly responding to input keys.  The game that I am attempting is Star Citizen.  I am connecting with my mixer interactive board Star Citizen, with version number 109865. 

After some trouble, I was able to get partial working keys.  The problem is that when a viewer would press a key, this key would remain depressed.  I was using W keypress for throttle up, and S keypress for throttle down.  I tried with delays before and after the keypress, but it seems to be stuck in some kind of loop.  After pressing down throttle by viewer a single time, the reverse throttle would be stuck on.  I could press forward throttle on my actual game machine, and the reverse would still be activated.

I attempted with having the reverse key selected on and off, and with key press held on and off.  Neither were successful at fixing this neverending press.  When I would have the emulated key press C for chaff, it would shoot out all of my chaff one after another.  

Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
I believe you stopped by discord right? Did you get this fixed?

Not every game handles emulated controls well. However, we've had some people that have seen success when using autohotkey scripts. You can hop in our discord to get some feedback on that if you're still having issues.
