### ISSUE TITLE
Feature Request: Song Request & Point System

### ISSUE THREAD

**Issue by Twizted-Native** [crowbartools/Firebot#617]
#### If you're reporting an issue, *please* fill out & do the following questions. If you leave them blank the issue may be closed due to lack of information.

Connection to youtube or Spotify so our viewers can request song this goes hand in hand with a point system that would be really helpful as well
## What version of Firebot are you running?

Current Version

## Please describe the issue or feature requests in as much detail as possible.

It would make it to where our viewers can request songs and the in channel currency can make it to where our viewers want to earn hours and be in chat more, this can also give possibility for mini-games with the currency and a whole more, like giveaways, betting and a lot of other fun stuff to do to help people stay interested.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Points systems are already on our list for v5. We've been tossing around the idea of song requests, but it'll make its way in much later. It's not a huge priority right now as we work on main features.

**Comment by Twizted-Native** [comment]
actually i just checked all updates and point system isnt in there i even checked em all
