### ISSUE TITLE
[Feature Request] If/Then and Loop Effect

### ISSUE THREAD

**Issue by Checkmarks** [crowbartools/Firebot#618]
It would be nice to see an If/Then effect and a Loop effect in Firebot for more advanced uses without needing to resort to custom scripts.  The effect could have parameters of If (INSERT ANY VARIABLE) is TRUE/FALSE then run any effect or variable or do nothing.  Put together with a Loop effect I think we could see a lot of advanced uses of Firebot without the need for activating custom scripts.

**Comment by ebiggz** [comment]
For awhile now I've been flirting with the idea of a "Conditional Effect" which would be the If/Then/Else you mentioned, however it's continued to dog me whenever I get serious about implementing it as I get trapped in the rabbit hole of complexity required with the current code base. As such, I am waiting to implement it in V5 which should make the task much more feasible. 

I had not considered a Loop Effect tho which I think is a great idea. I want to add as many easy to use "logic control effects" as I can to go with the already available Delay, Random, and Effect Group effects.

**Comment by BFG42** [comment]
So this is something I am looking for specifically I would like to call someone out if they press the button 3 times by posting a message in chat. I figured this pertained to the logic part of this request so I posted this in here.

**Comment by BFG42** [comment]
The ability to have something else happen if someone or anyone pushes a certain amount of times would be awesome.

**Comment by ebiggz** [comment]
These features are finally available in v5. Closing this out.
