### ISSUE TITLE
Fire Bot + Obs Problem

### ISSUE THREAD

**Issue by AISHIITERU** [crowbartools/Firebot#620]
hello everyone

i finally got a capture card hooked up to my xbox one
and im using OBS + streamjar + firebot 
i am only having one issue !
every time i activate my firebot effects they keep showing in the left top corner of my stream !
and i dont see any way to edit the location ? how can i change the location of the button effect? 
i hope someone can help me with this since i been searching on google but no luck finding the solution
im pretty much new to this so wanna get it right

**Comment by AISHIITERU** [comment]
that might be my problem im using a older version of firebot since the guide i used did only explain the older version and not the newer version

**Comment by ThePerry-2015** [comment]
Then I would suggest that you download and install the latest version of Firebot, currently 4.11.3, remove the old overlay and adds the new overlay by url:
`http://localhost:7473/overlay`
And make it just as big as your stream resolution and adjust the effects as you want them to show up. Some experimenting on the different settings and you should figure out most of them pretty quick.. ;)

**Comment by AISHIITERU** [comment]
i downloaded the new firebot and deleted my old overlay and added the new firebot overlay i also re done all my buttons but when i click on play it doesnt show up in obs like it should ?

**Comment by AISHIITERU** [comment]
it tells me overlay running but not connected ?

**Comment by ThePerry-2015** [comment]
Go into the browser source in OBS and click the refresh cache button at the bottom. 
For future reference start Firebot first, then start OBS. This ensures that OBS doesn't fail when trying to access the overlay.

**Comment by AISHIITERU** [comment]
i finally got it to work thank you ! i had to just refresh my browser and restart my pc quickly then open firebot and obs and now they are showing now just figuring out the pixels to have the triggers show between middle top and middle right
