### ISSUE TITLE
Tooltip Issues

### ISSUE THREAD

**Issue by Checkmarks** [crowbartools/Firebot#621]
## What version of Firebot are you running?
4.11.3

## Please describe the issue or feature requests in as much detail as possible.
Tool tips for buttons become null on desktop after switching scenes on mixer.com.
Sometimes tool tips for one button get placed on another button that has a completely different tool tip when switching scenes. (switching user groups in firebot)

**Comment by ebiggz** [comment]
This is actually a bug on Mixer's end. This is almost always the case with interactive UI bugs on Mixer's site. When firebot changes the scene for example, its simply sending a "change scene" event with the scene name to Mixer and Mixer does the rest (ie animates scene change and shows the buttons for the new scene).  I believe you will want to report any issues you see on that front on this Mixer maintained repo: https://github.com/mixer/cdk-preact-starter
