### ISSUE TITLE
Add "webm" for video overlays

### ISSUE THREAD

**Issue by codymiller360** [crowbartools/Firebot#624]
## What version of Firebot are you running?

v4.11.4

## Please describe the issue or feature requests in as much detail as possible.

I am trying to use streamlabs obs, and everything works just fine, but the video commands. it works just fine in regular obs so that is what i am using. i guess what needs to be added is webm support on firebots end, or mp4 support on streamlabs end. so i am requesting both :) thank you guys!

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ThePerry-2015** [comment]
WebM videos are already supported in Firebot. :) 
We have reached out to StreamLabs regarding MP4 and that's apparently not happening in the near future due to coding issues.
