### ISSUE TITLE
Bot Won't Whisper? v4.11.4

### ISSUE THREAD

**Issue by MrTrend** [crowbartools/Firebot#625]
## Please describe the issue or feature requests in as much detail as possible.
Bug Report: Everything works great on FireBot, except for one exception. When I set commands up to talk/whisper chat when a button is pressed, as BOT, it returns this error: 

"There was an error sending a whisper to chat as the bot. If you are testing a chat button, please make sure Interactive is connected."

The Interactive is connected fine and every other button works, except any button I've setup with my BOT. The problem is new, so not sure what's going on or how to fix it. I can fix it by making it post on my streamer account, but I don't want to have to resort to that.

**Comment by Firebottle** [comment]
Heya! First step would be to re-log into the app. Try that and let us know if it fixes the issue!

**Comment by ebiggz** [comment]
Whoops. This was resolved in Discord last night. I forgot to close this out.
