### ISSUE TITLE
Unable to use buttons until banned

### ISSUE THREAD

**Issue by ChocolateToe** [crowbartools/Firebot#627]
## What version of Firebot are you running?

I am using v4.11.4

## Please describe the issue or feature requests in as much detail as possible.

One of my mods was unable to press any of the interactive buttons. He could on other accounts, but not that one. I unmodded him and remodded him, but it made no difference. 

This morning when he still couldn't press any buttons, I added him to the banned list. When I did that, he was able to press buttons whilst ON the banned list. When I removed him from that list, he was still able to press buttons. But it was the fact that while on the banned list, he had access to the buttons.

Please could you look into this and see why it is not working properly, or if it is just the once.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

I did.

**Comment by ebiggz** [comment]
Hey @ChocolateToe - realize this is two months too late, but we will definitely look into issues with banned users still being able to use the board!
