### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by GrimlockePrime** [crowbartools/Firebot#628]
Love the program I have been using it for the better part of 2 years,

I would love to see a Currency system (with Ranks), a Quote System, and games because I feel like Mix it up and Scorpbot are edging ahead with that but you got them with how simple the system works

**Comment by ThePerry-2015** [comment]
Hi, we have just recently started branching into the chatbot stuff and we are currently working on adding more stuff, which you can see/follow here:
https://github.com/crowbartools/Firebot/projects/8

**Comment by ebiggz** [comment]
Glad you are enjoying it so far @GrimlockePrime ! As Perry said, we are hard at work on the next big version which will eventually include all the things you listed. Coincidentally, we are actively building out the Currency system as we speak. Thanks for the suggestions!
