### ISSUE TITLE
the interative buttons on firebot are not connecting

### ISSUE THREAD

**Issue by KyFaVortex** [crowbartools/Firebot#631]
## What version of Firebot are you running?

v4.13.2

## Please describe the issue or feature requests in as much detail as possible.
the interactive buttons are not working
because I here that fire bot isn't working for other streamers and the don't like its of if that would also be fixed

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
What?

**Comment by ebiggz** [comment]
Going to close this issue due to inactivity and because the initial issue description is difficult to even understand.
