### ISSUE TITLE
Can't create Events

### ISSUE THREAD

**Issue by stryd3r50** [crowbartools/Firebot#632]
## Please describe the issue or feature requests in as much detail as possible.

Will not let me create events for some reason.,

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
Hi @stryd3r50 ! Sorry for the delay in replying. 

Do you have alot of events saved up? If not, try deleting the file firebot saves events too and restarting the app. You can locate the file with these steps:

1. Open Firebot
2. Go to Settings > Open Root Folder
3. Follow the path `/user-settings/live-events/`
4. Delete the file `events.json`
5. Restart Firebot

If you have alot of events saved that you dont wanna lose, you'll need to send us that `events.json` file so we can fix it manually. :)

**Comment by stryd3r50** [comment]
I actually have no events saved so i will try that delete file

**Comment by ebiggz** [comment]
Sounds great. That should resolve your issue, so I'll go ahead and close this ticket. Let us know if you run into any more problems. Thanks!
