### ISSUE TITLE
Event Not Showing

### ISSUE THREAD

**Issue by Kdog57** [crowbartools/Firebot#636]
## What version of Firebot are you running?
4.13.13

## Please describe the issue or feature requests in as much detail as possible.
 Bug Report: Trying out possibly putting new events into my stream. They are now active, but i cant see any of them on the event list/tab, just made 2 on trial, and now i cant turn them off. Only thing visible is the new event button. Side note, I couldn't find what all the external apis do anywhere, thats what i was trying to test out ...
![firebot](https://user-images.githubusercontent.com/43193922/45399921-fd00ef00-b617-11e8-8e56-6857bb789964.png)
 Feature Request: Possible way to do giveaways through the bot? -->

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
@Kdog57 Sorry for not getting around to this! We'll work on being faster with github messages. Could you let us know if  you got this fixed? We have a discord channel as well where we are very active if you need real time support.
