### ISSUE TITLE
Clicking buttons on webpage does not trigger

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [crowbartools/Firebot#637]
## What version of Firebot are you running?
4.17.1

## Please describe the issue or feature requests in as much detail as possible.

Buttons to not work when clicked. I noticed that when I reverted back to version 4.15.1 it worked, however as soon as I restarted it of course updated and I can no longer press any buttons. Everything works as expected when pressing the buttons manually in the program. This seems to be a communication issue or an issue with Season 2.

I've run though all the troubleshooting steps outlined and a few of my own. Ive got it running on debug mode right now if you need anything

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
@Alynntheyelloweyed  Sorry for not getting around to this! We'll work on being faster with github messages. Could you let us know if  you got this fixed? We have a discord channel as well where we are very active if you need real time support.
