### ISSUE TITLE
Feature Request: Button to send message to chat feed

### ISSUE THREAD

**Issue by lolrenee** [crowbartools/Firebot#638]
This is a pretty simple request.  I run a dual PC setup and use the Firebot chat feed to monitor chat. At the moment, the only way to send a message (i.e. sending a /timeout or /ban message) is to hit "enter" on your keyboard.  I'm simply asking for an additional "send" button so that I can moderate my chat using only my mouse, if necessary. A "mention" option when you click on someone's name would also be super useful for me.

At the moment, the Firebot chat feed is one of the best I've seen, especially with the recent updates with Skills.  Thank you so much for your continuous work on it!

**Comment by ebiggz** [comment]
These are great suggestions @lolrenee , thank you!

**Comment by ebiggz** [comment]
These changes (a send button and a "mention" option in the Message Actions popover) have been implemented and will be available in the next release.

**Comment by ebiggz** [comment]
This has been released in v4.18.0
