### ISSUE TITLE
Feature request Custom spark amounts 

### ISSUE THREAD

**Issue by Skubadoe** [crowbartools/Firebot#640]
For a feature request one of my friends is a partnered streamer on mixer (https://mixer.com/BigCrafter Go follow great streamer btw). Donating sparks takes a long time if you don't have the exact amount that the stickers donate at, The request that i would like to see is the ability for viewers to donate custom amounts whether it is through the interactive or the chat, it would be a great feature i think.

**Comment by Firebottle** [comment]
Hi! Big Crafter should be able to create a button in Firebot that costs more than the stickers through the Mixer dev lab. There are a lot of streamers who have a "spark dump" button that is just an expensive button  for that exact purpose!

**Comment by DragynsLair** [comment]
Hello! I utilize a combination of a Text Field, a Button and a Custom Script to allow a viewer to set then send the spark amount that they want to donate.  Have your partnered streamer contact me if they want details.
