### ISSUE TITLE
Accessibility issues with screen reader

### ISSUE THREAD

**Issue by SightlessKombat** [crowbartools/Firebot#641]
## What version of Firebot are you running?

4.18.3

## Please describe the issue or feature requests in as much detail as possible.

n/a

I am a gamer without sight and stream using a screen reader, a piece of software that turns synthesised text and controls, when labelled correctly, into synthesised speech.  Adding in additional accessibility, including labelling the "gear icon" correctly in the chat feed to modify chat settings would assist the userbase at large in more easily using Firebot.  Also, adding easily accessible information on what commands can be used in the chat events tab as well as how to create sounds for events with users involved, for example, would make it less frustrating for everyone to start using the program effectively.

This is kind of a bug report and feature request all-in-one, so apologies for that.  However, I wanted to make you aware that my screen reader (Non-Visual Desktop Access, NVDA for short) running on Windows 10 version 1809, can't see any text in the chat feed, even when I've connected to my own stream and put in text myself.  By can't see it, I mean that even if it is there, there is no indication of text having been displayed on screen when using the arrow keys to navigate the area where it theoretically should be.

I am happy to provide further clarification on this if you wish though I am new to GitHub so I apologise for any errors I've made.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792
Discord is unfortunately completely inaccessible to screen readers at present.  If this changes in the future I will look at using this method of communication but for now, it's off-limits.

**Comment by SightlessKombat** [comment]
@Firebottle Thanks very much for the quick response and glad you're looking into this. Having access to a chatbot is all I really need to get fully off the ground streaming and I have everything else ready. Should you want me to test builds for screen reader accessibility, I'd be happy to discuss that with you as well so that I can get streaming on a schedule as quickly as possible (with games like Crackdown 3 and Mortal Kombat 11 coming out soon that I plan to be involved with).

Lok forward to seeing what you have in store and keep up the good work; yours is the most accessible chatbot I've found so far.

**Comment by Firebottle** [comment]
Update: We've made several adjustments to make firebot more accessible for screen readers. We'll continue to make these updates to make Firebot as accessible as possible for everyone, including multiple languages.

I'm closing this for now as we've already made a good deal of these changes.
