### ISSUE TITLE
Resync clears sparks and Tooltip

### ISSUE THREAD

**Issue by Shadowmaginis** [crowbartools/Firebot#643]
## What version of Firebot are you running?

V4.18.4

## Please describe the issue or feature requests in as much detail as possible.

I noticed that every time I use the Resync Board option under "Change Board" I loose the spark cost and Tooltip for each of the buttons I've created. They seem to stay through closing and opening the app, but resyncing deletes them. 

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Hello @Shadowmaginis ! This is a known issue. The workaround is to put the spark costs and tooltips into the Mixer dev lab if this is going to be a permanent change. Changing the spark cost and tooltip inside Firebot should be used for temporary fixes until you can make the actual change in the dev lab.
