### ISSUE TITLE
Audio file loading issues

### ISSUE THREAD

**Issue by NickParks** [crowbartools/Firebot#644]
## What version of Firebot are you running?

4.18.4

## Please describe the issue or feature requests in as much detail as possible.

Audio/sound file is saying the song is 2:55 but it's actually 1:54 long. When the song hits about 1:45 play time the FireBot display jumps from "1:40/2:55" to "2:40/2:55" before ending.

Wild.

Reproduced by making an audio source, saving it, then going back into the effect and changing the audio file to a different one.

https://imgur.com/a/V1KCt76

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Hello! If you have not fixed the issue I'd recommend hopping into our discord. There is a link at the bottom of your issue and on our website. Thanks!
