### ISSUE TITLE
overlay turns blue when using commands

### ISSUE THREAD

**Issue by Rem-ag** [crowbartools/Firebot#645]
## What version of Firebot are you running?

v4.18.4

## Please describe the issue or feature requests in as much detail as possible.

using ANY command even if it is an invalid command, the overlay screen turns blue and wont stay alpha/green

This is a pic of my firebot window AFTER the error 

https://i.imgur.com/aYudg7b.png

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Hi! Sorry for the delay. Did you get this resolved? If not, it might be best to hop into our discord. There is a link at the bottom of your ticket as well as on our site.

**Comment by Rem-ag** [comment]
Yes unfortunately I moved away from firebot. It just kept creating problems
for me that I couldn’t solve

**Comment by Firebottle** [comment]
Okay. I'll go ahead and close this then for now. Sorry for the lack of response on github. We've moved most support over to discord and need to update a few areas of the site and app to list that as the main support area.

If you ever decide to come back to Firebot and run into any issues, please hop into discord and let us know. All of the devs keep eyes on those channels regularly.

Happy streaming!

**Comment by Rem-ag** [comment]
Sounds good thanks brother
