### ISSUE TITLE
Chat event cooldown to way to add one

### ISSUE THREAD

**Issue by DS9Fireblade** [crowbartools/Firebot#648]
Release v4.19.0

Not as much of an issue but more of a suggestion, i was hoping to make an event for when a raid happens. Uses the chat to pick up the word raid and then triggers the event which is a chat message and a video overlay. obviously i don't want the video overlay to be continuously spammed as multiple people write in the word. hope this makes sense and if anyone know of a way to already implement this i would appreciate the help.

**Comment by Firebottle** [comment]
This will be possible in v5.
