### ISSUE TITLE
Websocket error?

### ISSUE THREAD

**Issue by awrebels** [crowbartools/Firebot#649]
Trying to narrow down an issue potentially/tangentially related to some transcoding issues I'm getting. This error shows up in the log any idea how to fix it? 

07:32:21.184: obs-browser: WebSocket connection to 'ws://localhost:8080/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED (source: /Roaming/Firebot/firebot-data/overlay/js/reconnecting-websocket.js:209)

**Comment by brumoen** [comment]
Seems like something is blocking OBS from accessing your Firebot Overlay Web Socket Port, you haven't by any chance changed the Overlay Web Socket Port in Firebot -> Settings -> Advanced?
![image](https://user-images.githubusercontent.com/4147439/58858060-fedb7880-86a6-11e9-862d-43c048ccdc76.png)

**Comment by awrebels** [comment]
It's still set to 8080. I guess a good old uninstall reinstall may be in order? or should I attempt to change ports

![image](https://user-images.githubusercontent.com/28576527/58880311-9dff7080-86a5-11e9-904a-9d50e196ac47.png)

**Comment by ThePerry-2015** [comment]
Have you tried opening the overlay in for example Chrome and opened the Developer Console to see if it behaves the same there?

Try to trigger events/effects in Firebot while the overlay is loaded in Chrome to see if it reacts or not. 

Does the Overlay indicator in the lower left corner turn green when you access the overlay in OBS and/or Chrome?
![image](https://user-images.githubusercontent.com/25306770/58940187-2864d480-8779-11e9-919a-902f7fef1136.png)

![image](https://user-images.githubusercontent.com/25306770/58940176-1daa3f80-8779-11e9-8818-9a438817dc98.png)

Have you checked if your firewall is blocking connections to Firebot / port 8080?

**Comment by awrebels** [comment]
Yea I've never seen the overlay indicator not connected. The effects still work fine. I checked the firewall and it seems that firebot is in there and allowed for any udp/tcp ports. I changed the port from 8080 to 8081 back to 8080 and it seems that I am not getting the error anymore but I haven't tested it during a stream yet.
