### ISSUE TITLE
Firebot doesn't use my Bot in chat

### ISSUE THREAD

**Issue by NeoFletcher** [crowbartools/Firebot#650]
## What version of Firebot are you running?

4.19.0

## Please describe the issue or feature requests in as much detail as possible.

Firebot keeps using my streamer log in in chat instead of my bot. It's been like this for weeks and logging my bot in and out doesn't work nor does resetting anything. I've had this problem before in the past and sometimes it goes away but it's not this time.

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ThePerry-2015** [comment]
This is a known issue and we have made multiple attempts on solving it, but so far none of them have fixed the problem. A temporary solution seems to be to just disconnect Firebot and reconnect it again. If you keep an eye on the Chat Feed view while connecting you should see both your streamer and bot account in the list if it successfully connects the bot account. There shouldn't be any need to re-auth your bot account every time it happens, just a simple reconnect of Firebot should help.

**Comment by Firebottle** [comment]
Going to go ahead and clear this one out. I haven't seen this issue at all in v5 yet, which is what the new focus is on right now.
