### ISSUE TITLE
Show Event Text not displaying?

### ISSUE THREAD

**Issue by awrebels** [crowbartools/Firebot#651]
Trying to get the Show Event effect to display text on screen during an event specifically a new subscriber. I have the default and a custom overlay in OBS. The text only displays on the default regardless of the overlay instance selected. Additionally the positioning doesn't seem to make sense. I tried make it full width (1920x1080) and then position using either presets or custom and it doesn't seem to want to follow the position outlined.

If I could at least get the custom overlay to work then I can drag the text to the appropriate position. Any ideas why it is not displaying on custom overlay instances?

thanks!

**Comment by brumoen** [comment]
Do you still have this issue?
Have you tried opening the custom overlay URL in Chrome or any other browser just to see if it works there?

I can't seem to replicate this, I know for a fact that Strwb uses a Firebot Custom Overlay for her subscriber and host events. She has this setup both in XSplit and StreamLabs OBS and her effect is using the Show Text effect
I can only test with follower events myself as I'm not partnered, but as far as I can see it plays the follower-animation I've setup as an Event to whatever Custom Overlay I've set it to show up in.

Tested both the Show Text and Show HTML effect with OBS Studio, StreamLabs OBS and XSplit.

**Comment by awrebels** [comment]
Yea it seems to not trigger when someone subs and also there is still the issue with being able to select the overlay instance that it should appear on. Currently it stays on default and won't change. 

I'll set one up for follower as well for testing purposes. thanks

**Comment by Firebottle** [comment]
Going to go ahead and mark this as a bug for more research. We've moved focus over to v5 and I'm not sure if this is an issue there or not, but it'll be good to look into.
