### ISSUE TITLE
Innacurately(?) reporting inactive group on scene change

### ISSUE THREAD

**Issue by Cr0wnogo** [crowbartools/Firebot#652]
## What version of Firebot are you running?
4.19.1

## Please describe the issue or feature requests in as much detail as possible.
Board ID 341502 "crows"
1) Set up new group called "temp"
2) Assign it to scene "default" in scene settings
3) Create effects that add user to group "temp", change scene, and add user to group "default"
4) Set up three more user groups called "board2" "board3" "board4" and rename "temp" to "board1" _without_ changing effects that refer to group "temp"
5) Change scene change button to the following effects: Add user to group "board1" and change scene to scene "board1" (repeat for board2, board3, and board4)

Result: Every time a user changes a scene, the following error message displays.
https://i.imgur.com/a53N5Ej.png

**Comment by Firebottle** [comment]
This should be fixed in v5! Going to go ahead and close for now as v4 is "complete".
