### ISSUE TITLE
[Feature Request] Cooldown Groups for chat commands.

### ISSUE THREAD

**Issue by Krymerra** [crowbartools/Firebot#653]
I want to add shortcuts to my soundboard / video-board so people don't need to scroll endless pages of emote buttons. I figured chat commands could do the trick except for the fact they lack cool-down groups which is the only effective way to keep people from spamming emotes/sounds. I do hope you could add this feature. Thank-you for your time.

**Comment by Firebottle** [comment]
In v5 you can set cooldowns on all chat commands. @Krymerra are you trying to create a chat command that outputs an emote?

**Comment by LastMageTV** [comment]
Closing due to no response.
