### ISSUE TITLE
Overlay: Running, but nothing connected

### ISSUE THREAD

**Issue by joshmann1** [crowbartools/Firebot#654]
## What version of Firebot are you running?

4.20.0

## Please describe the issue or feature requests in as much detail as possible.
 I have set up board id 406086 and the overlay is showing up on Mixer, but none of the buttons work. Also, while in the Firebot window, under the connections section of the bottom left corner i see the following:

 ![image](https://user-images.githubusercontent.com/13295436/64352593-ec345080-cfc1-11e9-8a79-942277cb847c.png)

When mousing over the Yellow icon i see this: 
![image](https://user-images.githubusercontent.com/13295436/64352645-04a46b00-cfc2-11e9-9203-6dab2f340916.png)

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Please request support in our discord channel and we'll try to help you out! You can find a link to the discord at crowbartools.com!
