### ISSUE TITLE
Auto Disconnect | Error Message

### ISSUE THREAD

**Issue by Ukzs** [crowbartools/Firebot#655]
## What version of Firebot are you running?
v4.20.0 Is the version i am using.

Issue i am getting.

When i try to connect Firebot i get the Error message "error with startup modification loop" then the bot will disconnect, i get that say error message when i try to connect. I cannot seem to find a fix for this error when searching on the internet. All steps asked for to set up the bot has been done correctly just a connecting issue. Sometimes the bot connects but then when loading the Mixpay board on mixer i get the "Waiting for the game to be ready..." and the board never loads.

When i started to install the dashboard the first time i got an error message so i uninstalled the bot and reistalled it and i did not get the error message again i just got the above error message and i am still getting that error.

**Comment by Firebottle** [comment]
Please request support in our discord channel and we'll try to help you out! You can find a link to the discord at crowbartools.com!
