### ISSUE TITLE
[Feature Request] Allow mixer teams members to be treated as groups in firebot.

### ISSUE THREAD

**Issue by ghost** [crowbartools/Firebot#656]
## What version of Firebot are you running?

I AM RUNNING     v4.21.0

## Please describe the issue or feature requests in as much detail as possible.

**We currently have followers staff subscribers etc. as groups but we dont have mixer teams as groups in firebot.(mixer allow each channel to make teams).It will help in creating various interactive features once we have the option of the team to be treated as groups, for example, when a user/viewers joins a team he/she automatically becoming part of group on firebot so we can create nice interactives for them .
Thanks i have summed up nicely i think but if any confusion exists then i will try to further elaborate.**

**Comment by Firebottle** [comment]
Note that the user who requested this has been deleted on github. But, it's still a good idea.
