### ISSUE TITLE
feature request- Allow joystick /controller inputs to be emulated on PC 

### ISSUE THREAD

**Issue by ghost** [crowbartools/Firebot#657]
## What version of Firebot are you running?

i am running v4.21.0 

## Please describe the issue or feature requests in as much detail as possible.

**### We know we can emulate mouse and keyboard on PC under firebot but we can't emulate controller inputs on pc .On console share controller is built in but not on pc. I think it can be a very nice addition to game control feature on firebot.It will allow us to attach multiple controllers and create co op couch like gameplay possible with audience in game like FIFA20 ,playing games like that using mouse or keyboard is not ideal.
I Appreciate  all the work inside firebot, just a little more and we make everyone happy.**

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Closing as the user has been deleted according to github.
