### ISSUE TITLE
can not complete install

### ISSUE THREAD

**Issue by greatbigjay** [crowbartools/Firebot#660]
## What version of Firebot are you running?
4.21.0

## Please describe the issue or feature requests in as much detail as possible.
after install, when it launches all i get is a big white box with firebot in the top left corner with ther version number. i am running windows 10 and have tried uninstall and reinstall, re downlowded the installer. tried the previous version, but nothing works. i have tried installing into a windows 8 pc and it launches after install to the setup screen no problem

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by Firebottle** [comment]
Are you on a 32bit version of Windows?

**Comment by greatbigjay** [comment]
i know the win 8 is for sure.....now you have me wondering about my win 10 laptop....i will check in a couple of hours and post it

**Comment by greatbigjay** [comment]
64 bit on both i attached what i am getting. it launches right to this instead of the welcome to firebot get started screen everytime i try
![Untitled](https://user-images.githubusercontent.com/12600259/70587211-9655e280-1b86-11ea-8afd-39a2aed3eeeb.jpg)

**Comment by greatbigjay** [comment]
any ideas?

**Comment by Firebottle** [comment]
@greatbigjay I'm not really sure, but I'm leaning towards this being an antivirus issue or something on the local machine causing issues.
