### ISSUE TITLE
Firebot for MacOS and/or Linux

### ISSUE THREAD

**Issue by sushihangover** [crowbartools/Firebot#661]
## What version of Firebot are you running?

Master branch of repo

## Please describe the issue or feature requests in as much detail as possible.

I'm wondering if you have any guide/instructions to setup Firebot on macOS.

TIA, Robert

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by LastMageTV** [comment]
Unfortunately, firebot does not currently run on Mac. But with the v5
rewrite we are expecting to be able to bring firebot to Mac and linux a bit
after it's initial release.

**Comment by sushihangover** [comment]
@LastMageTV 

Thanks for the info. 

Is there a roadmap/timetable for v5 somewhere? TIA.

**Comment by LastMageTV** [comment]
V5 beta is very soon. But no time table other than that.

**Comment by LastMageTV** [comment]
Closing as I just realized this duplicates #546
