### ISSUE TITLE
[Feature Request] Implement way to show top X currency, hours, etc...

### ISSUE THREAD

**Issue by LastMageTV** [crowbartools/Firebot#665]
We need a way for people to be able to see the top X number of people with X thing in the database. Mostly we need this for currencies and viewtime. However, if this can be generic enough to pull the top X from any column in the viewer database then this could be super useful.

**Comment by LastMageTV** [comment]
ebiggz and I talked about this a bit. He suggested that this could just be a variable where you pass the currency name and how many people you'd like to get back. This would return a comma separated list of user names and the points. EX: TheLastMage (12,412), ebiggz (10,223), etc...

99% of people are only going to want this for currency and view time, so we might just implement those two.

**Comment by ebiggz** [comment]
top currency variable is done. Just need one for hours now.
