### ISSUE TITLE
[Feature Request] Sequential Effect

### ISSUE THREAD

**Issue by mito551** [crowbartools/Firebot#788]
**Describe the solution you'd like**
An Effect that would play one from the list of effects one by one with each call. For example, a command that has sequential effect, inside of it 4 chat effects. The first chat effect outputs "1" in the chat, the second one - "2", and so on. When the command is run for the first time, it only runs the first chat effect and that outputs in chat "1". The second time the command is run, it outputs "2". It maybe should have a settings to say how many effects are there?

**Additional context**
There's a thing like that in Doom Snapmap :P
I was thinking of making a social media, and a label rotator like that: recent embers, recent subs, etc.

**Comment by brumoen** [comment]
This is kind of effect is already in Firebot, which was informed to the poster in Discord earlier today.
