### ISSUE TITLE
[Feature Request] song requests

### ISSUE THREAD

**Issue by eldon113** [crowbartools/Firebot#789]
**Describe the solution you'd like**
I'm sure this has already been mentioned but i would like a way for viewers to request songs from spotify, youtube, ect.. but i want it to be a mixplay button. 

**Additional context**
i currently use another bot that can do it through chat commands but i'm trying to maximize spark usage on my channel. Also my end goal would be to get firebot as my only running bot program using mixer currency for all my channel interactions

**Comment by brumoen** [comment]
We have been discussing this internally, and so far we are still on the fence about it. Mostly because Mix-It-Up are removing the feature in their next big update, https://mixitupapp.com/songrequests, we might just as well drop the plans for this.

**Comment by LastMageTV** [comment]
Pinning this as our main "song request" issue. What is linked above is currently our stance as well, mainly for the same reasons. API limits and violating terms of service on various platforms. Because of those reasons, we are not currently planning song request features.

**Comment by ebiggz** [comment]
Going to close this since it is not planned. It will still remained pinned.
