### ISSUE TITLE
Non partner clips not being downloaded or posted to chat

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [crowbartools/Firebot#832]
As part of the current test for non-partner clips I have used firebot and mixitup as testers. 

Firebot does send the request to mixer and mixer does create the clip.

Firebot does not post the link to chat, nor did it download the clip to the computer.

The location was configured in setting and both boxes for downloading and posting to chat were checked.

**Comment by ebiggz** [comment]
@Alynntheyelloweyed These issues should be resolved in v5.13.4 :)
