### ISSUE TITLE
[BUG] Firebot doesn't play the sound through mixplay

### ISSUE THREAD

**Issue by MrsFunktipus** [crowbartools/Firebot#836]
**Describe the bug**
Under Effect the play sound it only plays through the firebot app and not through the actual mixplay so nobody can hear it

**Expected behavior**
How can it play through the mixplay?

**Firebot Version:**
v5.12.2

**Comment by ebiggz** [comment]
Unfortunately playing sound directly through MixPlay is not a feature that MixPlay (and therefore Firebot) supports. 

The sound effect feature is intended to be captured by broadcasting software on a PC (such as OBS or XSplit)
