### ISSUE TITLE
[Feature Request] Support MixPlay projects with custom DevLab version IDs

### ISSUE THREAD

**Issue by tiedyedguy** [crowbartools/Firebot#871]
Right now your version_id / share code are hardcoded in file: https://github.com/crowbartools/Firebot/blob/b2d204e474ff9e64875b122fd7b8c3aec48fe136/backend/interactive/mixplay.js

const FIREBOT_MIXPLAY_VERSION_ID = 334620;
const FIREBOT_MIXPLAY_SHARECODE = "moo33cku";

Can these instead be settings that can be changed?  That way we can build our own interactive and still use your bot as the game client.

**Comment by ebiggz** [comment]
Hi @tiedyedguy , thanks for creating a ticket for this. We absolutely want to support custom devlab mixplay project ids. 

Enabling this functionality will require a bit more than just making those hardcoded id's configurable, as the UI also needs to be updated to be able to handle this appropriately . I think this is everything that would need to happen before we could release:
- Add setting in **Settings** > **Advanced** called "Enable Advanced MixPlay Projects"
  - Surface a "Update MixPlay World" effect when setting enabled
- When that setting is enabled, the **Create New Project** modal will have an option to create a "Regular" or "Advanced" Project. 
  - If you select "Advanced", you have to provide a DevLab Project Id. 
  - The grid editor would not be available in "Advanced" projects.
- The **Create/Edit Control** modal will need to be different for "Advanced" projects
  -  It will let you define the Control ID and the Control Type.
  -  It will let you define other properties manually (akin to the Meta properties editor in the dev lab where you can add strings, numbers, etc)
  - It will let you specify which Input Events the control should trigger effects on.
- The **Update Control** effect will need to be updated for "Advanced" projects
- The **Change MixPlay Scene** effect will not work for "Advanced" projects and will need to be hidden within these projects.

**Comment by tiedyedguy** [comment]
Hey ebiggz!

I love all of this!  

A few thoughts:

- The grid editor would not be available in "Advanced" projects.  

Instead of just disabling it, how about a warning that the grid editor on Advanced projects that control placement has to be taken care of in the interactive? There has to be some level of required knowledge of MixPlay if you are going down the advanced route.  The grid is a nice way of assigning some of those properties of the controls, especially if you start with the preact template or copy the default interactive.  I'm debating in my head the actual usefulness now, but still a thought.  

- If you select "Advanced", you have to provide a DevLab Project Id. 

Optionally a share code also please. This would allow someone to make interactive for others to use in firebot.  Which is my ultimate goal :).

- It will let you define the Control ID and the Control Type.

Why not just keep Control Name as the Control ID?  Do you map control names to a random control id somewhere in this code that I'm missing?  

- It will let you specify which Input Events the control should trigger effects on.

I get where you are going with this one as assign effects to each control event that comes, but that seems overkill.  I mean, shoot for the stars, hit the moon and all that, but that one seems ambitious.    If you just look for the events at message level you can get all events for a control.  And again, as I type this out if you aren't already watching for things on message level that adds in it's own complication anyway.  

Thanks for your effort in this!

**Comment by tiedyedguy** [comment]
Thank you for all your work, but I think I can close this request :(
