### ISSUE TITLE
[Bug] Viewer Arrived Event Does Not Allow Filters

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#916]
**Describe the solution you'd like**
When using the 'Viewer Arrived' Event, allow for Filters based on Specific Usernames, View Roles (in Firebot), and Roles on Twitch (Mod, VIP, etc).

**Additional context**
As a workaround for others until/if this feature is added, you can recreate this by adding a Conditional Effect to your Viewer Joined Event and filtering Users that way.

**Comment by SReject** [comment]
Moved into compendium
