### ISSUE TITLE
[Feature Request] expression evaluator?

### ISSUE THREAD

**Issue by CKY-** [crowbartools/Firebot#918]
Pass values through the expression evaluator that have been loaded from an external source. 

Create a text file that has something like this 
$user Slaps $arg with a raw fish
$user Licks $arg On the knee
$user Pokes $arg $radomnumber[20, 200] on the wrist to be annoying.
$user violates $arg;s safespace
 
on command read from file random line

**Comment by ebiggz** [comment]
Sounds like we could accomplish this with a variable that evaluates expressions passed into it. Ie:
```
$evalVars[ $readFile[foobar.txt] ]
```

**Comment by ebiggz** [comment]
Closing as this was added a couple months ago.
