### ISSUE TITLE
[Feature Request] Add the ability to filter specific users from the viewer list.

### ISSUE THREAD

**Issue by Sam-Beynon** [crowbartools/Firebot#922]
@TwinklingPlays I would very much be able to hide users from appearing.. no bans, no nothing.. just hiding them, or categorizing them to "bots" and they show at the bottom of the viewerlist. i know they arent harmful, im just tired of seeing their names in my chat when i know they do 0 for me.

**Comment by MageEnclave** [comment]
To be honest, I think the viewer list is extremely low priority. The viewer list is something that, while sometimes useful, doesn't have much of an impact on the most important pieces of Firebot. I just want to be transparent in saying that it may be a bit before we get to adding it back, much less being able to filter it like this.

**Comment by Firebottle** [comment]
PR has been opened for this issue. It will allow you to hide users via their user modal.

**Comment by TwinklingPlays** [comment]
> 

awesome - twitchinsights keeps their bot list updated. That could be used to check usernamed on there and then categorize them in firebot based on that.

**Comment by TwinklingPlays** [comment]
No hiding pls - or settings at the very least.
