### ISSUE TITLE
[Bug] Celebrations do not show if specifying a Show Image size in same Event.

### ISSUE THREAD

**Issue by Alynntheyelloweyed** [crowbartools/Firebot#930]
**Describe the bug**
If you have an event with both a celebration and an image/gif, and you specify the size of the image/gif the celebration cannot be seen. Using a fully transparent image does show the fireworks, so likely the celebration is happening behind the image.

**To Reproduce**
Have an event with the following two things
1 Show Image/Gif
2 Celebration

If you specify width and height for the image, you do not see the celebration fireworks with an opaque image
If you remove the specified height and width, you see the fireworks in front of the image.

**Expected behavior**
Firework Celebration should still be visible if you specify the size of the image/gif if it is set up to run second in the list.

**Screenshots**

**Firebot Version:** 
v5.18.0

**Computer OS:**
Windows 10 1909

## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by MageEnclave** [comment]
@Alynntheyelloweyed hm, I can't seem to reproduce this. Below are the steps of things I did to setup the combination you listed. Can I get some screenshots of your setup maybe? Or use the share effect feature and send me a link. I can confirm however that Fireworks will show being images.

Here's what I did:
- Setup a command !test.
- Add effect of Show Image/GIF.
- Had image show in the preset center of screen.
- Set image with and height. (500x250)
- Set duration to 10 seconds.
- Saved the image effect.
- Added a celebration effect. Set duration to 20 seconds.
- Open overlay in browser window.
- Run command in chat.
- I was able to see both the fireworks and the image.

![image](https://user-images.githubusercontent.com/17416635/97211189-a968a580-178c-11eb-8fb0-17886fc88990.png)

**Comment by Alynntheyelloweyed** [comment]
Hello,
                So this was put in several version iterations ago, and I had since worked around it by creating a second overlay and specifying the fireworks to show up on the top overlay. I would have to recreate it back to its initial state and check again. There have been several updates and I have built a new computer since I submitted this bug.

Differences in my scenario

Was set via a channel point awards
Image was set to 1920X1080

However, this could have been inadvertently fixed in a later update. I forgot about it once I did the work around.

**Comment by MageEnclave** [comment]
Ah, I understand. I didn't read well enough. This should be updated in the next release if the PR is approved.
