### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by veedeeiot** [crowbartools/Firebot#942]
**Describe the bug**
When channel points event are set and users in chat redeem those points multiple times in succession, the events play over top of each other without a delay. This occurs even with a delay set that is supposed to prevent it from happening. The streaming site is Twitch.

**Expected behavior**
When an event is selected to play, that event plays then any other event selected at the same time is played after the initial event has ended.

**Firebot Version:**
version 5.19.1

**Computer OS:**
Windows 10
## Contact Us!
Did you know that we have a help channel in discord as well? https://discord.gg/DegW792

**Comment by ebiggz** [comment]
If you have a Delay effect as the last effect in the effect list, this works as expected. The next version of Firebot adds a new Queue Type called "Custom" which allows you to specify the duration of a given effect list to ensure the queue waits the appropriate amount of time. This should be a more intuitive design vs using the Delay effect.
