### ISSUE TITLE
[Feature Request] New Text/Number Variable Type '$text'

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#957]
**Describe the solution you'd like**
A new $text (my placeholder name) variable type that would have support for several uses:
- Get a specific character from an input ($textGet[input, 5]) would result in 't' being output
- Give a range of characters to grab ($textGet[input, 3, 5]) would result in 'put' being output
- A Contains that can be used to output a True/False ($textContains[input, put]) would output true/1. ($textContains[input, test]) would output false/0.

**Comment by ebiggz** [comment]
This has been added with `$textSubstring` and `$textContains`
