### ISSUE TITLE
[Feature Request] Viewer UI & Viewer Database Enhancements

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#971]
**Describe the solution you'd like**
- If Mixer Viewer data exists, present a new option (defaulted to On) which hides Mixer viewers from the Viewer list. If no Mixer Viewer data exists, hide this in the UI.
- New Database Setting option for User Cleanup:
-- Purge Users Who Haven't Been Active In X Days
-- Purge Users Where View Time Is Less Than X Hours
-- Purge Mixer Viewer Data Which Has Not Been Migrated. This option should be hidden if no Mixer Viewer data exists or if the function purges Mixer Viewer Data.

Nice to Haves:
- New Event Types called 'Viewer Banned' and 'Viewer Timed Out'
- New Effect To Allow Viewer Data Purge. Use case here is on Ban, remove User from Database

**Comment by ebiggz** [comment]
This has been added. Check out Settings > Database > Purge Viewers
