### ISSUE TITLE
[Bug] Give Currency Effect Not Respecting 'Give to All Online Users'

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#972]
**Describe the bug**
The 'Give Currency to All Online Users' is ignoring the Viewer Setting 'Don't Allow on Active User Lists'.

**To Reproduce**
1. Create Command and Effect to give currency to all online users
2. Set an Active Viewer to 'Don't allow on active user lists' to true
3. Run command - User will still be given currency.

**Expected behavior**
User should be ignored (this specifically is problematic for Bot User accounts)

**Comment by ebiggz** [comment]
This should of been fixed with recent updates. Let me know if there's further issues.
