### ISSUE TITLE
[Bug] Cooldown Effect Doesn't Correctly Apply to Sub-Commands

### ISSUE THREAD

**Issue by heyaapl** [crowbartools/Firebot#975]
**Describe the bug**
When the 'Cooldown Effect' is used to apply a Cooldown (tested via User Cooldown) on a command that has a sub-command, the sub-command does not respect the applied cooldown.

**To Reproduce**
1. Create a command with a sub command (!spin [number])
2. Use a Cooldown Effect as part of the command (!spin [number]) on use
3. Attempt to use !spin [number] again, and the sub command will not follow the cooldown applied via the Effect

**Expected behavior**
The sub-command should respect the applied cooldown.

**Firebot Version:**
5.25

**Comment by ebiggz** [comment]
Resolved with recent update.
